---
output:
    bookdown::word_document2:
      toc: false
      fig_caption: yes
    reference_docx: style_template.docx
---

```{r, include=FALSE}
# Script to summarize seed fates

knitr::opts_chunk$set(message = FALSE, 
                      error = FALSE, 
                      warning = FALSE, 
                      fig.pos = "H", 
                      table.placement = "H",
                      fig.height = 8,
                      fig.fullwidth = TRUE)
```

```{r, include=FALSE}
library(compareGroups) #to export tables into single files
library(magrittr)
library(flextable)# xtable and kableExtra do not render .docx. flextable() and set_caption() allows cross-referencing in the knitted document. 
library(officer)
# other table features here: https://ardata-fr.github.io/flextable-book/ 
library(emmeans) #need `emmeans` loaded before `here`
#library(here)
library(data.table)
library(readr) # for read_csv()
library(tidyverse) #for pivot_wider() and ggplot2
library(lme4)
library(nlme)
library(ggResidpanel)
library(ggthemes)

theme_set(theme_bw())
```

```{r, include=FALSE}
## Read seed column data  
seed_column <- readRDS("../2-Data/Raw/seed_column_19_list.RData")

seed_column_round <- readRDS("../2-Data/Raw/seed_column_19_list_poisson.RData")

```

```{r, include=FALSE}
## Apply over-winter decaying
```

```{r, include=FALSE}
## Apply tillage
```

```{r AMATA-female-recruit, echo=FALSE}

AMATA_recruit_cohort <- readRDS("../2-Data/Raw/six_cohort_female_emerge_list_raw.RData")

AMATA_recruit_cohort
```