---
output:
    bookdown::word_document2:
      toc: false
      fig_caption: yes
    reference_docx: style_template.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(purrr) # for map2()
```

Scenario 1 settings:

Using the 2019 seedbank stratum-based densities as the initial state of the seedbank vertical distribution (model year 1), the following matrices traced how the seed population in model year 1 grow in three rotation systems crossed with two corn weed management regimes. 

```{r}
## Read seed column data  
seed_column <- readRDS("../2-Data/Raw/seed-column-2019-list.RData")

```

```{r post-harvest-tillage}
## Post-harvest tillage
post_harvest_tillage <- readRDS("../2-Data/Clean/post-harvest-tillage.RData")

post_harvest_tillage_pop <- purrr::map2(post_harvest_tillage, seed_column, `%*%`)
```

```{r over-winter}
## Overwinter survival 

overwinter_scenario1 <- readRDS("../2-Data/Clean/winter-seed-survival-scenario1.RData")

over_winter_pop_scenario1 <- purrr::map2(overwinter_scenario1, post_harvest_tillage_pop, `%*%`)
```

```{r spring-till}
## Pre-planting tillage 
spring_tillage <-  readRDS("../2-Data/Clean/pre-planting-tillage.RData")

spring_tillage_pop_scenario1 <- purrr::map2(spring_tillage, over_winter_pop_scenario1, `%*%`)
```

```{r emerge-scenario1}
## Emergence 
emergence_scenario1 <- readRDS("../2-Data/Clean/emergence-prop-scenario1.RData")

spring_pop_scenario1 <- purrr::map2(emergence_scenario1, spring_tillage_pop_scenario1, `%*%`)
```

```{r summer-survive-senario1}
## Seed survival and plant survival 
#### seed survival 

summer_seed_survival_scenario1  <- readRDS("../2-Data/Clean/summer-seed-survival-scenario1.RData")

#### plant survival
female_survival <- readRDS("../2-Data/Clean/female-survival-rate-cohort-equal.RData")
#### combine seed and plant survivals into one matrix with element-wise multiplication 

summer_survival_scenario1 <- purrr::map2(summer_seed_survival_scenario1 , female_survival, `*`)

summer_pop_scenario1 <- purrr::map2(summer_survival_scenario1, spring_pop_scenario1, `%*%`)
```

```{r fecund-scenario1}
## Fecundity scenario 1

fecundity_2019 <- readRDS("../2-Data/Clean/fecundity-mean-19-cohort.RData")

## After one model year, using 2019 fecundity rate, and before post-harvest tillage application, what are the seed densities? 
fall_pop_scenario1 <- purrr::map2(fecundity_2019 , summer_pop_scenario1 , `%*%`)

## How does this one-year cycle translate to rotation-specific dynamics?
```


```{r fecund-scenario2}
## Fecundity scenario 2

fecundity_2018 <- readRDS("../2-Data/Clean/fecundity-mean-18-cohort.RData")

fall_pop_scenario2 <- purrr::map2(fecundity_2018 , summer_pop_scenario1 , `%*%`)
## After one model year, using 2018 fecundity rate, and before post-harvest tillage application, what are the seed densities? 
```



```{r post-harvest-tillage-pop}
# https://stackoverflow.com/questions/68342613/use-lapply-to-multiply-two-lists-of-matrices-in-r

post_harvest_tillage_pop <- purrr::map2(post_harvest_tillage, seed_column, `%*%`)
```

```{r overwinter-pop}
```