---
title: "Fecundity matrix organization"
output: html_document
---

```{r, include=FALSE, message=FALSE}
library(tidyverse)
library(readr)
library(emmeans)
library(here)
library(nlme)
library(data.table)
library(moments) #for skewness and kurtosis
```

```{r fecund-18, include=FALSE}
fecundity18 <- read_csv("../2-Data/Raw/fecundity_18.csv", 
    col_types = cols(Biomass = col_number(), 
        Seed = col_number()), na = "empty")

fecundity18$Crop_ID <- factor(fecundity18$Crop_ID, 
                              levels = c("C2", "S2",
                                         "C3", "S3", "O3",
                                         "C4", "S4", "O4", "A4"))

# Make sure that Block, Crop ID, Corn_weed_management, and bt are factors
fecundity18[,c(1:7,10:13)]  <- lapply(fecundity18[,c(1:7,10:13)], factor) 


## Keep complete cases only (389/391 entries), "sb" in fecundity18_sb stands for seed and biomass 
fecundity18_sb <- fecundity18[complete.cases(fecundity18$Seed, fecundity18$Biomass), ]

allcrops.biom.seed.gls <- gls(log(Seed+1) ~ Block + 
                                log(Biomass + 0.005) + 
                      Crop_ID*Corn_weed_management +
                      Crop_ID:log(Biomass + 0.005) +
                        Corn_weed_management:log(Biomass + 0.005) +
                      Crop_ID:Corn_weed_management:log(Biomass + 0.005),
  correlation=corCompSymm(form= ~1 | bt), #identifies each treatment within block
  data=fecundity18_sb)

# Partition plant size and fecundity into 6 bins with hist(log(fecundity18_sb$Biomass), bin = 6)

fecundity18_sb_log <- fecundity18_sb %>% 
  mutate(log_Biomass = log(Biomass + 0.005),
         log_Seed = log(Seed + 1)) %>%
  group_by(Crop_ID, Corn_weed_management) %>% # pool all plants from the same CropID x Corn weed mgt
  mutate(quantile_Biomass = ntile(log_Biomass , 6),
         quantile_Seed = ntile(log_Seed, 6)) %>%
  dplyr::mutate(tag = ifelse(quantile_Biomass == quantile_Seed, "matched", "mismatched"))  # check if Biomass and Seed quantiles are aligned  ONLY 202 are matched.



## Calculate quantile-means, with log and original data
fecundity18_sb_log_quantile_summ <- fecundity18_sb_log %>%
  group_by(quantile_Biomass, Crop_ID, Corn_weed_management) %>%
  summarize(geometric_mean_Biomass = mean(log_Biomass),
         geometric_mean_Seed = mean(log_Seed),
         mean_Seed = mean(Seed)) %>% #
  mutate(matrix_id = paste(Crop_ID, Corn_weed_management, sep = "_")) %>%
  arrange(matrix_id, desc(quantile_Biomass)) #arrange by descending order of biomass because 1) biomass is the reproduction potential parameter, 2) cohorts that were suppressed more frequently by crop management may have their reproduction potential compromised, so arranging by biomass can accommodate this reality

# View(fecundity18_sb_log_quantile_summ)

# Check if all combinations have 6 bins, for 6 cohorts.
#table(fecundity18_sb_log_quantile_summ$Crop_ID, fecundity18_sb_log_quantile_summ$quantile_Biomass)

#range(fecundity18_sb_log_quantile_summ$geometric_mean_Biomass)

# cut(fecundity18_sb_log_quantile_summ$geometric_mean_Biomass, 5)

# Write a list of 8 x 8 matrices, data-based

fecundity_mean_18_list <-  lapply(split(fecundity18_sb_log_quantile_summ, fecundity18_sb_log_quantile_summ$matrix_id),
       function(x)(rbind(cbind(diag(1,2),
                         rbind(matrix(c(x$mean_Seed,rep(0,6)), byrow = T, nrow=2))),
       matrix(rep(0,48), nrow = 6, byrow = TRUE))))

## Save the 18 2018 fecundity matrices as a list 


```

```{r save-fecundity, include=FALSE}
# Estimated marginal means and var of 2018 fecundity 
# Since the effects of corn weed management and crop identity on fecundity were mediated by biomass 
# at = list(log_Biomass = c(-3.35, -1.26, 0.824, 2.91, 5, 7.08), from cut(fecundity18_sb_log_quantile_summ$geometric_mean_Biomass, 5)
# cut(fecundity18_sb$Biomass, 5)
# log_Biomass = c(-3.35, -1.26, 0.824, 2.91, 5, 7.08) is equivalent to list(Biomass = c( 0.04, 0.28, 2.28, 18.36, 148.41, 1187.97)) CAN BE USE TO TEST AN EXTREME CASE

# Refine the cut() to reflect appropriate size bin partitioning, especially the big plants:
fecundity18_sb_ln_whole <- fecundity18_sb %>% 
  mutate(ln_Biomass = log(Biomass + 0.005),
         ln_Seed = log(Seed + 1)) %>%
  mutate(quantile_Biomass = ntile(ln_Biomass , 6),
         quantile_Seed = ntile(ln_Seed, 6)) %>%
  group_by(quantile_Biomass) %>% 
  summarize(grand_mean_Biomass = mean(Biomass))

# New cut: fecundity18_sb_ln_whole$grand_mean_Biomass

seeds_18_emm <- emmeans(allcrops.biom.seed.gls, ~ 
                       Crop_ID * Corn_weed_management | Biomass,
                     at = list(Biomass = fecundity18_sb_ln_whole$grand_mean_Biomass),
                     type = "response")  # 6 bins, as **pooled** by the whole experiment


## convert emmeans output to dataframe
seeds_18_emm_df <- seeds_18_emm %>%
  as.data.frame() %>% #equivalent to print(.,export = TRUE) but more convenient
  rename(mean_seed = response,
         SE_seed = SE) %>%
  mutate(var_seed = SE_seed^2) %>%
  mutate(matrix_id = paste(Crop_ID, Corn_weed_management, sep = "_")) %>%
  arrange(matrix_id, desc(mean_seed)) 

# write.csv(seeds_18_emm_df, "../2-Data/Clean/mean-fecundity-18-cohort-df.csv")

# View(seeds_18_emm_df)

# Write a list of 8 x 8 mean matrices, model based

fecundity_mean_18_list_emm <-  lapply(split(seeds_18_emm_df, seeds_18_emm_df$matrix_id),
       function(x)(rbind(cbind(diag(1,2),
                         rbind(matrix(c(x$mean_seed,rep(0,6)), byrow = TRUE, nrow=2))),
       matrix(rep(0,48), nrow = 6, byrow = TRUE))))

## Save the 18 2018 fecundity matrices as a list 
# saveRDS(fecundity_mean_18_list, file="../2-Data/Clean/mean-fecundity-18-cohort.RData")

## cohort-based variances of fecundity are saved as a diagonal matrix, independent of the seedbank
#fecundity_var_18_list <-  lapply(split(seeds_18_emm_df, seeds_18_emm_df$matrix_id),
#       function(x) rbind(matrix(0,nrow = 2, ncol =8), cbind(matrix(0,nrow = 6, ncol = 2), diag(x$var_seed,6))))
         



# saveRDS(fecundity_var_18_list, file="../2-Data/Clean/var-fecundity-18-cohort.RData")
```


The calculation of fecundity (F) from 2019 aboveground mass (X) data is from [@nguyenImpactCroppingSystem2022], in which each crop identity crossed with corn weed management treatment is of the form $ F = aX + b$ and $Var(F) = a^2Var(X) + Var(b) $. Theoretically, $Var(b) = 0$, but the variance of the error term ($Var(\epsilon)$) has been absorbed into $Var(X)$ and $Var(b)$. 


```{r amata-fecundity-equation, include=FALSE}
fecundity_eq <- read_csv("../2-Data/Raw/fecund_eq.csv")


### import 2019 biomass, Weight here is on the original scale 
female_19 <- read_csv("../2-Data/Raw/female_19.csv") # 1365 entries, no entries for soybeans because of high herbicide efficacy 

table(female_19$Cohort, female_19$Crop_ID, female_19$Corn_weed_management)
# Need to add: 
# A4: cohort 6
# C2: cohorts 4, 5, 6
# C3: cohorts 5, 6
# C4: cohorts 5, 6
# O3: cohort 5
# S2, S3, S4: cohorts 1 through 6


#replace NA with 0, 0 will be corrected by log(Biomass + 0.0005) in the later step

female_19_A4_seed_placeholder <- expand.grid(Crop_ID = "A4",
            Corn_weed_management = c("conv","low"),
            Crop = "alfalfa",
            Year = 2019,
            Cohort = 6,
            Plot = c(17, 22, 39, 41)) 

female_19_O3_seed_placeholder <- expand.grid(Crop_ID = "O3",
            Corn_weed_management = c("low", "conv"),
            Crop = "oat",
            Year = 2019,
            Cohort = c(3, 5, 6),
            Plot = c(11, 23, 38, 48)) 

female_19_O4_seed_placeholder <- expand.grid(Crop_ID = "O4",
            Corn_weed_management = "low",
            Crop = "oat",
            Year = 2019,
            Cohort = 6,
            Plot = c(14, 29, 32, 49)) 

female_19_C2_seed_placeholder <- expand.grid(Crop_ID = "C2",
            Corn_weed_management = c("conv","low"),
            Crop = "corn",
            Year = 2019,
            Cohort = c(3:6),
            Plot = c(19, 27, 35, 45)) 


female_19_C3_seed_placeholder <- expand.grid(Crop_ID = "C3",
            Corn_weed_management = c("conv","low"),
            Crop = "corn",
            Year = 2019,
            Cohort = c(4:6),
            Plot = c(16, 25, 33, 42)) 

female_19_C4_seed_placeholder <- expand.grid(Crop_ID = "C4",
            Corn_weed_management = c("conv","low"),
            Crop = "corn",
            Year = 2019,
            Cohort = c(3,5,6),
            Plot = c(12, 21, 31, 43)) 

## Since all soybeans were unavailable: create placeholders for S2, S3, and S4 separately to hold plot number
## Block and side are not needed because mean weight are 0
female_19_S2_seed_placeholder <- expand.grid(Crop_ID = "S2",
            Corn_weed_management = c("conv","low"),
            Crop = "soybean",
            Year = 2019,
            Cohort = c(1:6),
            Plot = c(13, 24, 34, 44)) 

female_19_S3_seed_placeholder <- expand.grid(Crop_ID = "S3",
            Corn_weed_management = c("conv","low"),
            Crop = "soybean",
            Year = 2019,
            Cohort = c(1:6),
            Plot = c(15, 26, 36, 47)) 

female_19_S4_seed_placeholder <- expand.grid(Crop_ID = "S4",
            Corn_weed_management = c("conv","low"),
            Crop = "soybean",
            Year = 2019,
            Cohort = c(1:6),
            Plot = c(18, 28, 37, 46)) 

# merge crops' placeholders
female_19_all_crops_seed_placeholder <- rbind(female_19_S2_seed_placeholder,
                                        female_19_S3_seed_placeholder,
                                        female_19_S4_seed_placeholder,
                                        female_19_C2_seed_placeholder,
                                        female_19_C3_seed_placeholder,
                                        female_19_C4_seed_placeholder,
                                        female_19_A4_seed_placeholder,
                                        female_19_O3_seed_placeholder,
                                        female_19_O4_seed_placeholder)
# check if all Crop_ID present: yes
# table(female_19_all_crops_seed_placeholder$Plot, female_19_all_crops_seed_placeholder$Crop_ID)

## Fill in weight = 0 (assuming NA = 0) and sex = female
## Rotation, Side, Quadrat, etc. are not filled because those variables are not used at the later steps
female_19_all_crops_seed_placeholder_named <- female_19_all_crops_seed_placeholder %>%
  mutate(Weight = 0,
         Sex = "female")

female_19_blank_crops <- rbindlist(list(female_19, female_19_all_crops_seed_placeholder_named),
                                 use.names=TRUE, fill=TRUE) # now 1509 entries

### estimate 2019 fecundity 
## No Cohort id in the fecundity_eq because it was assumed that all plants across all cohorts in the same crop environment 
## can have their seeds estimated using the same equation
female_19_est <- left_join(fecundity_eq, female_19_blank_crops,
                           by = c("Corn_weed_management", "Crop_ID")) #now 1617 entries, 


 table(female_19_est$Cohort, 
       female_19_est$Crop_ID,
       female_19_est$Corn_weed_management) # missing cohorts 5 and 6 in O3 low; and cohorts 3 in C4 conv
# compare with the original, non-manifested table: all the blanks (0 or missing column) are now 4. 
 table(female_19$Cohort, 
       female_19$Crop_ID,
       female_19$Corn_weed_management) 
 ## check if any NA:
# female_19_est_NA <- female_19_est %>% tidyr::extract(!complete.cases(.), ) # doesn't work consistently

# 252 entries of no observations are incomplete (with the unfilled columns)
female_19_est_NA <- female_19_est[!complete.cases(female_19_est),]

```

```{r amata-fecundity-cohort-19}
# Seed = a * log(Weight) + b
# a = log(Biomass + 0.005)_estimate /// b = (Intercept)_estimate
# log is actually ln

# Y = aX + b with E(X) = m
# https://www.quora.com/Whats-the-mean-and-the-variance-of-Y-aX-b-2-where-X-is-a-random-variable-with-E-X-m 
# m1 = mean(Weight)
# m2 = Var(Weight)
# m3 = 
# m4 = 

##### estimate individual fecundity from weight #####
## How to deal with NAs in corn and zeros in soybean's consequences on var(seed):
# Assume var(constant) = 0 regardless of the number of reps
female_19_est_individual_fecundity <-  female_19_est %>% 
  rename(a = `log(Biomass + 0.005)_estimate`,
         SE_a = `log(Biomass + 0.005)_std.error`,
         b = `(Intercept)_estimate`,
         SE_b = `(Intercept)_std.error`)  %>%
  mutate(var_a = SE_a^2,
         var_b = SE_b^2,
         var_Weight = var(Weight), #m2_ pooled variance of biomass, need cohort-based, CropID x corn weed mgt var later
    Seed_log = a*log(Weight + 0.005) + b,
    var_Seed_log = (a^2)*var_Weight + var_b, #pooled variance of log of number of seeds
    Seed = exp(Seed_log + var_Seed_log/2),
    var_Seed = exp(var_Seed_log))  %>% # pooled variance of number of seeds
  select(Crop_ID, Corn_weed_management, Cohort,
        a,  var_a, var_b, Weight, Seed, var_Weight, var_Seed) # keep relevant columns only 


# female_19_est_individual_fecundity[!complete.cases(female_19_est_individual_fecundity),] #no NAs here.

##### summarize by cohort, crop ID and corn weed management #####
# group by CropID x corn weed management and partition each group into 6 cohorts, assuming that cohort is best represented by individual size 
# plants from the same CropID x corn weed management share the same slope and intercept
# the combination of slope x intercept id is the same as Crop ID x corn weed management id
female_19_est_cohort_summ <- female_19_est_individual_fecundity %>% 
#  group_by(Corn_weed_management, Crop_ID) %>% # pool all plants from the same CropID x Corn weed mgt
#  mutate(quantile_Weight = ntile(Weight , 6), #out because recreating weight-based cohort poses discrepancy
#         quantile_Seed = ntile(Seed, 6))  %>%
    group_by(Cohort, Corn_weed_management, Crop_ID) %>%
  mutate(count_cohort = n(),
         var_Weight_cohort =  ifelse(count_cohort>1, var(Weight), 0),  
         var_Seed_log_cohort = (a^2)*var_Weight_cohort + var_b) 

#  var_Weight_cohort = ifelse(count_cohort>1, var(Weight), 0) calculate within-cohort variance; if the group 
# has only one sample, fill it with 0
# The practice above make consistent variance value filling with R assigning var(4 identical numbers) = 0
# Example: female_19_est_cohort_summ %>%
#     filter(Crop_ID == "C3") %>%
#     group_by(Cohort, Corn_weed_management) %>%
#     select(Weight) %>%mutate(v_Weight = var(Weight))


female_19_est_cohort_sorted <- female_19_est_cohort_summ %>%
   group_by(Cohort, Corn_weed_management, Crop_ID) %>%
  summarize(mean_Seed_cohort = mean(Seed),
            var_Seed_log_cohort = mean(var_Seed_log_cohort),
            var_Seed_cohort = exp(var_Seed_log_cohort)) %>% 
  mutate(matrix_id = paste(Crop_ID, Corn_weed_management, sep = "_")) %>%
  arrange(matrix_id, desc(mean_Seed_cohort)) 




# Save 2019 estimated fecundity as a list
mean_fecundity_19_list <- lapply(split(
female_19_est_cohort_sorted, 
female_19_est_cohort_sorted$matrix_id),
       function(x) rbind(cbind(diag(1,2),
                         rbind(matrix(c(x$mean_Seed_cohort, rep(0,6)), byrow = TRUE, nrow=2))),
       matrix(rep(0,48), nrow = 6, byrow = TRUE))) 

## Save the 2019 fecundity matrices as a list 
# saveRDS(mean_fecundity_19_list, file="../2-Data/Clean/mean-fecundity-19-cohort.RData")


## 2019 cohort-based variances of fecundity are saved as a diagonal matrix, independent of the seedbank
# because this var matrix is a 6x6, the last two columns and the last two rows are zeros 
var_fecundity_19_list <- lapply(split(female_19_est_cohort_sorted, female_19_est_cohort_sorted$matrix_id),
      function(x) rbind(matrix(0,nrow = 2, ncol =8), cbind(matrix(0,nrow = 6, ncol = 2), diag(x$var_Seed_cohort,6))))

# saveRDS(var_fecundity_19_list, file="../2-Data/Clean/var-fecundity-19-cohort.RData")

```