---
title: "Untitled"
author: "Huong Nguyen"
date: "3/24/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
A = list(a = matrix(1:4, 2), b = matrix(2:5, 2))

G = list(a = matrix(10:13, 2), b = matrix(5:8, 2))

M_1 = list(a = matrix(10:13, 2), b = matrix(5:8, 2))

M_2 = list(a = matrix(2:5, 2), b = matrix(5:8, 2))

dlist4 <- tibble::lst(A, G, M_1, M_2)
```

```{r}
lapply(dlist4, function(x) dimnames(x) = list(c("seed","plant"), c("seed","plant")))

lapply(dlist4, function(x) {colnames(x) <- letters[1:2]; x})

lapply(dlist4, function(x) {dimnames(x) = list(c("seed","plant"), c("seed","plant")); x})

Map(function(x) {dimnames(x) <- list(c("seed","plant"), c("seed","plant")); x}, dlist4)

for(i in seq_along(dlist4)) {
        dimnames(dlist4[i]) <- list(c("seed","plant"), c("seed","plant"))
}

rapply(dlist4, function(x) {dimnames(x) <- rep(list(c("seed","plant")), 2); x}, how="list")
```

```{r}

A <- matrix(c(0, .3, 2, .7), nrow=2) # spring transition matrix 
B <- matrix(c(0.5, .3, 3, .7), nrow = 2) # summer transition matrix
C <- matrix(c(0, .3, 4, .7), nrow=2) # fall transition matrix 
D <- matrix(c(0.1, .1, 6, .7), nrow = 2) # winter transition matrix

N0 <- c(Juveniles=1,Adults=10) # initial population
steps <- 12 # number of time steps; each chain of 4 time step representA%*% a year


# combine the stages of our initial population, and a zero matrix 
# with a column for each stage and a row for each time step
N <- rbind(N0, matrix(0, ncol=2, nrow=steps) )
# use a for-loop to project the population each year and store it.
    for(t in 1:steps) {
      N[t+1,] <- A%*%N[t,]
      N[t+2,] <- B%*%A%*%N[t,]
      N[t+3,] <- C%*%B%*%A%*%N[t,]
      N[t+4,] <- D%*%C%*%B%*%A%*%N[t,]
    N[t+5,] <- A%*%D%*%C%*%B%*%A%*%N[t,]

    }
```
```{r}
#apply tillage
prj2g<- lapply(seq_along(prj1g), function(i){
  if(names(prj1g[i]) %in% c("A4_l","A4_c","O3_l","O3_c")) moldboard%*%prj1g[[i]] else 
    if(names(prj1g[i]) %in% c("C2_c","C2_l","C3_c","C3_l","C4_c","C4_l")) chisel%*%prj1g[[i]]
    else notill%*%prj1g[[i]]
})

names(prj2g) <- names(prj1g)


#over-winter survival 
prj3g<-lapply(seq_along(prj2g), function(i){
  if(names(prj2g[i]) %in% c("A4_l","A4_c","O3_l","O3_c")) overwinter_m1%*%prj2g[[i]] else
    if(names(prj2g[i]) %in% c("C2_c","C2_l","C3_c","C3_l","C4_c","C4_l")) overwinter_m2%*%prj2g[[i]]
    else overwinter_m3%*%prj2g[[i]]
})
```