---
output:
    bookdown::word_document2:
      toc: false
      fig_caption: yes
#    reference_docx: style_template.docx
#bibliography: WH-pop-dynamics.bib
---

Crop bio-physiological characteristics and management requirements can affect weed populations’ dynamics differently. One way to examine such differences is to track changes in common waterhemp populations concerning the applied crop management using periodic matrices. We used a chain of six periodic matrices in each of nine crop environments crossed with two corn weed management regimes to project population trajectories in two scenarios of plant fecundity, representing two levels of control efficacy (high and low). Each crop environment identifies a crop species (corn, soybean, oat, or alfalfa) in a rotation (2-year, 3-year, or 4-year). Only corn and soybean received chemical herbicide. Both literature and empirically measured data were used. The crop sequences in the 2-year, 3-year, and 4-year rotations are corn - soybean; corn - soybean - oat intercropped with red clover; and corn - soybean - oat intercropped with alfalfa - alfalfa. Under the high control efficacy scenario, all the waterhemp population size declined at the annualized rate of $\lambda = 0.5$. Under the low control efficacy scenario, waterhemp population sizes increased the fastest in the 2-year rotation ($\lambda = 75$ to $\lambda = 123$) and the slowest in the 4-year rotation ($\lambda = 4$ to $\lambda = 8$). The slower rates of population growth in the more diverse rotation were attributed to declining $\lambda$ in the oat, red clover, and alfalfa crop environments that are cool-season crops. In addition to population projection, we examined the seed production thresholds in the three rotations for stabilizing population size. The 4-year rotation can tolerate higher seed production thresholds than the 2-year rotation.  