---
output:
    bookdown::word_document2:
      toc: false
      fig_caption: yes
      keep_md: true
bibliography: G-intro.bib
csl: apa-no-ampersand.csl 
---

Integrated weed management (IWM), which combines multiple weed control methods based on the sound knowledge of weed ecology and population biology (@buhler1992integrated; @liebmanManyLittleHammers1997), provides reliable weed control methods over the long run (@buhler200250th; @zimdahlNeedHistoricalPerspective2012; @lamichhane2017integrated). However, the complexity and diversity of weed communities and the involvement of numerous components in an IWM program pose difficulties to customization and implementation of weed management programs for specific cases (@buhler2000theoretical; @buhler200250th). First, the existing integrated pest management (IPM) programs for insects are not readily applicable to weeds given the difference in ecology, population biology, and history of adaptation to control measures between insects and weeds (@cardina1999development; @norris1999ecological). Second, individual species of weeds in a crop field may respond differently to each of the applied management practices, such as tillage [@mohler1997weed], Nitrogen fertilizer [@sweeney2008effect], and living leguminous mulch [@hiltbrunner2007response]. Third, the response of the target weed community to each of the applied weed control tactics in an IWM system under different crop rotations and associated management practices are often divergent (@davisWeedSeedbankCommunity2005; @legere2008contrasting; @ryanManagementFiltersSpecies2010; @friedTrajectoriesWeedCommunities2012).  

Few studies (@davisWeedSeedbankCommunity2005; @smithAssemblyWeedCommunities2007) have examined weed community composition in rotations with crop species other than corn (*Zea mays* L.), soybean (*Glycine max* (L.) Merr.), and wheat (*Triticum aestivum* L.), especially in fully phased settings, in which all crop phases within a rotation are present each year to control for the year to year variations in weather conditions and management efficacy @payneDesignAnalysisLong2015}. To fill the information gap of information on weed community composition in cool-season crops, I documented weed community abundance and composition in oat (*Avena sativa* L.), red clover (*Trifolium pratense* L.), and alfalfa (*Medicago sativa* L.) crop environments. Among the most competitive weed species that I observed, *Amaranthus tuberculatus* stood out for its resilience to changing environments making it one of the most noxious weeds in row crops in the US (@horakGrowthAnalysisFour2000; @hagerCommonWaterhempAmaranthus2002a; @hartzlerEffectCommonWaterhemp2004; 
@steckelCommonWaterhempAmaranthus2004;
@johnsonInfluenceGlyphosateresistantCropping2009; @princeBenchmarkStudyIntroduction2012; @tranelHerbicideResistanceAmaranthus2021).    

Hereafter, I refer to “waterhemp”  as the common name for both tall waterhemp and common waterhemp and use *Amaranthus tuberculatus* as the scientific name suggested by @prattAmaranthusRudisTuberculatus2001.  I supplemented the available data on the demographics of waterhemp populations (@mohler1997weed; @prattAmaranthusRudisTuberculatus2001; @costeaBiologyInvasiveAlien2005;
@davisWeedSeedPools2008; 
@heneghanGrowthDevelopmentFive2017; @montgomerySexspecificMarkersWaterhemp2019; @montgomeryMaleSpecificChromosomal2021) with empirically measured data on sex ratio and the relationships of the aboveground mass and fecundity of individual plants in different crop environments. Then, I employed a periodic matrix model to integrate the data from the literature and my experiment to illustrate population trajectories. With sufficient and reliable data, modeling offers a more cost-effective means than empirical experiments @caswellMatrixPopulationModels2001. Finally, I followed up with a simulation to study how waterhemp population trajectories might differ in response to management intervention for seed production reduction. 



This dissertation is comprised of a general introduction (chapter 1), three data chapters (chapters 2, 3, and 4), and a general conclusion (chapter 5). The following paragraphs list the titles of the data chapters and briefly describe the research questions and general approaches in each data chapter.   

*Chapter 2. Weed community composition in simple and more diverse cropping systems.* This study examined how the aboveground and underground weed communities responded to cropping system diversification. We hypothesized that diversified cropping systems, with reduced use of chemical herbicides, would provide weed control equal in effectiveness to the conventional approaches applied in the 2-year corn and soybean system. We assessed weed control efficacy by measuring weed aboveground mass and population densities. Additionally, we measured crop yields, positing that differences in weed aboveground mass and density could be reflected in differences in crop yields. Next, we hypothesized that the weed communities in the more diverse cropping systems would be more diverse, more even, and more species-rich than those in the 2-year corn and soybean system, reflecting a broader range of crop species and their attendant management practices in the more diverse rotations. Finally, we hypothesized that including oat, red clover, and alfalfa in rotations with corn and soybean would reduce the density and aboveground mass of noxious weed species in corn and soybean when the rotations cycles returned to corn and soybean. A randomized complete block, split-plot design with four replications was used to study three different crop rotation systems (2-, 3-, or 4-year) suitable for the United States corn belt. The baseline system was a conventional corn - soybean system. The baseline system was diversified oat, red clover, and alfalfa. Conventional broadcast herbicide and reduced herbicide management regimes were applied in a split-plot manner to corn phases of the three rotations. Weeds were surveyed 4 to 6 weeks before corn and soybean harvests, and 2 to 3 weeks after oat harvest or the last hay cut of the season. The passage of a few weeks between oat and alfalfa harvest and weed surveys allowed physically damaged plants in those crops to grow back to recognizability. Weed aboveground samples were collected from eight quadrats arranged in a 4 x 2 grid throughout each experimental unit (eu). The sample grid was randomized every year in such a way that quadrats were at least 3 m away from plot borders to avoid any edge effect. Individual weed species aboveground and seedbank abundance and whole weed community aboveground and seedbank abundance abundance were measured. Ecological indices were calculated from the abundance data. Crop yields were reported in comparison with the County's and State's averages.   


*Chapter 3. Impact of cropping system diversification on vegetative and reproductive characteristics of waterhemp (**Amaranthus tuberculatus**).* This study examined the population aboveground mass, density and sex ratio, and the relationship between waterhemp's female size and fecundity when the weed grew in association with five crop species (corn, soybean, oat, red clover, and alfalfa) arranged in three cropping systems as detailed in Chapter 2. We hypothesized that the sex ratio of a waterhemp population deviated from parity depending on the environment's favorability, but how much and to which direction the shift would occur would depend on how much the studied population was suppressed. In addition to informing management, individual- and population-level characteristics would provide useful contextual details for sex ratio comparison. Counting seeds for waterhemp fecundity assessment is time-consuming and laborious, so it would be convenient to extrapolate fecundity from plant mass. We hypothesized that regression relationships with which to predict fecundity from plant mass could be identified but that such relationships would differ among treatments, due to differences in crop phenology, crop-weed competition, and management practices. The data for this study was collected from the same experiment design as in Chapter 2. Sex ratio was evaluated by scouting up to 100 plants per eu in 2018 and by scouting eight quadrats per eu in 2019. Individual aboveground mass and fecundity of female plants were recorded in 2019 and used to establish regression equations for estimating plant fecundity from aboveground mass in different management conditions.  



*Chapter 4. Effects of crop rotation on common waterhemp population dynamics: prospective and retrospective analyses.* This study combined available data from the literature with empirically measured data to examine the population dynamics of common waterhemp in different crop environments. The same experiment design as used in Chapters 3 was used in this study. We used a chain of six periodic matrices in each of nine crop environments crossed with two corn weed management regimes to project population trajectories in two scenarios of plant fecundity, representing two levels of control efficacy (high and low). Population sizes were projected in three cropping systems under those two herbicide efficacy levels. In addition to population projection, we examined the seed production thresholds in the three rotations for stabilizing population size via simulation of an unit plot of 1 m$^2$. The seed production thresholds were found by manipulating the plant fecundity of waterhemp in the corn and soybean phases until population sizes were stabilized ($\lambda \approx 1$).  

