---
output:
    bookdown::word_document2:
      toc: false
      fig_caption: yes
    reference_docx: style_template.docx
bibliography: WH-pop-dynamics.bib
---

In arable land, a low-density weed seedbank is highly desired. A weed species' seedbank persistence is often influenced by multiple factors, including burial depth, tillage regime, and crop environment [@steckelTillageCroppingSystem2007]. Common waterhemp (*Amaranthus tuberculatus* (Moq.) J.D. Sauer) is an agronomically challenging weed species [@johnsonInfluenceGlyphosateresistantCropping2009; @princeBenchmarkStudyIV2012] whose high fecundity, high relative growth rate [@heneghanGrowthDevelopmentFive2017], rapid herbicide resistance development [@tranelHerbicideResistanceAmaranthus2021], and extended emergence pattern [@buhlerEmergencePersistenceSeed2001] can help maintain an abundant seedbank [@davisWeedSeedPools2008; @korresSeedbankPersistencePalmer2018]. 

To increase labor use efficiency in waterhemp management, it is helpful to know possible choke points throughout the weed's life cycle, where intervention can substantially reduce the population growth rate. Following the population in full life cycles in different crop environments can help identify the choke points where management could be focused [@caswellMatrixPopulationModels2001]. Combining demographic parameters from multiple sources and organizing them in different scenarios can facilitate the evaluation of population responses without extensive field measurement [@ullrichWeedPopulationDynamics2000; @caswellMatrixPopulationModels2001; @davisCroppingSystemEffects2002]. In addition, retrospective perturbation analysis can be used to examine how a population would change if changes occurred at different points throughout the species' life cycle [@ullrichWeedPopulationDynamics2000; @caswellMatrixPopulationModels2001; @davisCroppingSystemEffects2002].

Interseeding red clover (*Trifolium pratense* L.) with wheat (*Triticum aestivum* L.) followed by spring tillage delayed and reduced giant foxtail (*Setaria faberi* Herrm ) seedling emergence as compared with three other interseeding and tillage timing combinations by fall tillage [@davisCroppingSystemEffects2003]. Cool-season crops, such as oat (*Avena sativa* L.), red clover can be planted early spring, and alfalfa (*Medicago sativa* L.), can be planted early spring or in the fall and overwinter to limit waterhemp's exposure to sunlight at the time of its emergence. Our search of the current literature did not return any information on waterhemp's population dynamics in other cool-season crops so we measured the following characteristics of waterhemp in cool-season crops environments: plant fecundity [@nguyenImpactCroppingSystem2022], soil seedbank density, the timing of seedling emergence and resultant densities, and plant survival. 

Extending a conventional 2-year rotation of corn and soybean to contain oat, red clover, and alfalfa effectively maintained a weed community at a level of abundance that did not coincidence with reduction in crop yields [@nguyenWeedCommunityComposition2022]. The effects of cropping system diversification on common waterhemp abundance were not clearly defined [@nguyenWeedCommunityComposition2022], even though waterhemp's reproductive potentials could be reduced without heavy reliance on herbicides [@nguyenImpactCroppingSystem2022]. A heuristic model for waterhemp population dynamics in corn (*Zea mays* L.) and soybean (*Glycine max* (L.) Merr.) (two warm-season annual crops) with or without a rye (*Secale cereale* L.) cover crop in between the corn and soybean phases indicated that the cover crop would provide minimal suppression of waterhemp population densities. To explore other options for regulating waterhemp population dynamcs, we conducted a prospective analysis using a population matrix approach [@ullrichWeedPopulationDynamics2000; @caswellMatrixPopulationModels2001; @davisCroppingSystemEffects2002]. In addition, we employed a retrospective perturbation analysis to examine how waterhemp population dynamics would change if life history parameters at different points throughout the species' life cycle were altered. 


We employed a periodic matrix model [@cousensDynamicsWeedPopulations1995; @caswellMatrixPopulationModels2001] to study waterhemp population dynamics to accommodate the examination of the effect of various events, i.e., crop management activities, that occur throughout the life cycle of waterhemp on the population change rate, $\lambda$. We used the general equation of $N_{h+1} = A N_h$ [@caswellMatrixPopulationModels2001] to study $\lambda$ from one period to another. The waterhemp populations in our study were depth-structured for the soil seedbank and cohort-structured for plants to accommodate the variation in seed survival [@yenishEffectsTillageVertical1992; @buhlerEmergencePersistenceSeed2001] and emergence rates [@werlePredictingEmergence232014] from different depths, plant survival rates, plant size, and fecundity of different cohorts [@hartzlerEffectCommonWaterhemp2004; @nordbyInfluenceCornCommon2004]. 

Elasticity analysis, which provides a closer look at how changes in $\lambda$ ($\Delta \lambda$) would respond to proportional perturbations in the lower-level demographic parameters (represented by the sub-annual matrix $B_h$ that described the sub-annual responses of the population to weed management practices), can help in evaluating $\Delta \lambda$ to each sub-annual intervention. In addition, since elasticity analysis involves each element $b_{ij}$ of matrix $B_h$, it is more convenient than sensitivity analysis in identifying the contribution of each $b_{ij}$ to $\Delta \lambda$ especially when a $B_h$ matrix involves more than one non-zero element. 

This study examined how waterhemp population dynamics might changes in cool-season crops suitable for the Midwestern USA climates, such as oat, red clover, and alfalfa. The modeling approach here combines demographic parameters from the literature as well as with empirical data from our own field work. We hypothesized that extending a conventional 2-year rotation of corn and soybean with cool-season crops could accelerate depletion of waterhemp seedbanks in the soil.  

