---
title: "Practice stochastic projection"
author: "Huong Nguyen"
date: "3/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(popbio)
data("hudsonia")
```

## Graph population size after x time steps, default at 50 by stoch.projection

```{r}

n <- c(4264, 3,30,16,25,5)
names(n) <- c("seed",  "seedlings", "tiny", "small", "medium" , "large")
```

```{r}
hudsonia #ordered chronologically by time
```


```{r}
## use equal and unequal probabilities for matrix selection
x.eq   <- stoch.projection(hudsonia, n, nreps=1000) # what happen after 1 timestep
#x.eq

hist(apply(x.eq, 1, sum), xlim=c(0, 5000), ylim=c(0,200), col="green",
breaks=seq(0,5000, 100), xlab="Final population size at t=50", main='')
par(new=TRUE)

apply(x.eq, 1, sum)
```


```{r}
x.uneq <- stoch.projection(hudsonia, n, nreps=1000, prob=c(.2,.2,.2,.4))


## use transparency for overlapping distributions - may not work on all systems
hist(apply(x.uneq, 1, sum), xlim=c(0,5000), ylim=c(0,200), col=rgb(0, 0, 1, 0.2),
 xaxt='n', yaxt='n', ylab='', xlab='', breaks=seq(0,10000, 100), main='')
legend(2500,200,  c("equal", "unequal"),fill=c("green", rgb(0, 0, 1, 0.2)))
title(paste("Projection of stochastic growth for Hudsonia
using equal and unequal probabilities"), cex.main=1)
## initial pop size
sum(n)
abline(v=sum(n), lty=3)
```


### 

```{r}
stoch.sens(hudsonia)
```

```{r}
sapply(hudsonia, lambda)
```

```{r}
library(popbio)
data("hudsonia")

hudson <- list(hudsonia[1:2], hudsonia[3:4]) 

set.seed(500)

scenario1_stoch.sens1 <- hudson %>%
  map(., ~{stoch.sens(.)})

scenario1_stoch.sens1[[1]]

scenario1_stoch.sens2 <- map(hudson, ~{stoch.sens(.x)})

scenario1_stoch.sens2[[1]] 


scenario1_stoch.sens3 <- stoch.sens(hudsonia[1:2])

scenario1_stoch.sens3
```

```{r}
# 
stoch.growth.rate(hudsonia)

var2(hudsonia) #calculate the variance of elements at the same ij positions across the `hudsonia` list # might be useful for variance of projection matrices across systems.  
```

```{r}
# how the population grow per year
sapply(hudsonia, lambda)
```

```{r phase-wise-projection-1}
# The model clock starts at post-harvest tillage, when new seeds were incorporated into the soil 
# List periodic matrices in chronologically reversed order for left-multiplication
# Now, with the fecundity rate in 2018

list_phase_scenario2 <- mget(paste0(c("fecundity_2018",
                        "summer_survival_scenario1",
                        "emergence_scenario1",
                        "spring_tillage",
                        "overwinter_scenario1",
                        "post_harvest_tillage")))

phase_wise_project2 <- flatten(tail(accumulate(list_phase_scenario2, map2, crossprod), 1))
```

```{r phase-eigen-projection-2}
phase_wise_project2_eigen <- lapply(phase_wise_project2, function(i){
  popbio::eigen.analysis(i)})
```


```{r phase-wise-projection-1}
# The model clock starts at post-harvest tillage, when new seeds were incorporated into the soil 
# List periodic matrices in chronologically reversed order for left-multiplication

list_phase_scenario1 <- mget(paste0(c("fecundity_2019",
                        "summer_survival_scenario1",
                        "emergence_scenario1",
                        "spring_tillage",
                        "overwinter_scenario1",
                        "post_harvest_tillage")))

phase_wise_project1 <- flatten(tail(accumulate(list_phase_scenario1, map2, crossprod), 1))


```

```{r phase-eigen-projection-1}
phase_wise_project1_eigen <- lapply(phase_wise_project1, function(i){
  popbio::eigen.analysis(i)})
```
