---
output:
    bookdown::word_document2:
      toc: false
      fig_caption: yes
    reference_docx: style_template.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(purrr) # for map2()
```

Scenario 1 settings:


```{r periodic-matrices}

## Pre-planting tillage 
spring_tillage <-  readRDS("../2-Data/Clean/pre-planting-tillage.RData")

## Emergence 
emergence_scenario1 <- readRDS("../2-Data/Clean/emergence-prop-scenario1.RData")

## Seed survival and plant survival 
#### seed survival 

summer_seed_survival_scenario1  <- readRDS("../2-Data/Clean/summer-seed-survival-scenario1.RData")

#### plant survival
female_survival <- readRDS("../2-Data/Clean/female-survival-rate-cohort-equal.RData")
#### combine seed and plant survivals into one matrix with element-wise multiplication 
summer_survival_scenario1 <- purrr::map2(summer_seed_survival_scenario1 , female_survival, `*`)

## Fecundity scenario 1

fecundity_2019 <- readRDS("../2-Data/Clean/fecundity-mean-19-cohort.RData")

## Post-harvest tillage
post_harvest_tillage <- readRDS("../2-Data/Clean/post-harvest-tillage.RData")

## Overwinter survival 
overwinter_scenario1 <- readRDS("../2-Data/Clean/winter-seed-survival-scenario1.RData")


```


```{r fecund-scenario2}
## Fecundity scenario 2

fecundity_2018 <- readRDS("../2-Data/Clean/fecundity-mean-18-cohort.RData")
```


 ### Apply stoch.sens
 
```{r stoch-sens-scenario1}
# Inside `stoch.sens()`: a list of projection matrix by each phase
# Reorganize `mget()` output by matrix_id, by chronological sequence
scenario1_projection_by_matrix_id <- pmap(list(spring_tillage,
                                               emergence_scenario1,
                                               summer_survival_scenario1,
                                               fecundity_2018,
                                               post_harvest_tillage,
                                               overwinter_scenario1), list) %>% 
  simplify() %>%
  map(.,
    ~{names(.) <-  c("spring_tillage",
                     "emergence_2019",
                     "summer_survival_Sosnoskie_2013",
                     "fecundity_2019",
                     "post_harvest_tillage",
                     "overwinter_Sosnoskie_2013"); .})

#works for one matrix_id

scenario1_stoch.sens0 <- stoch.sens(scenario1_projection_by_matrix_id$A4_conv) #but result is different from `pmap`

## all matrices at once
scenario1_stoch.sens1 <- scenario1_projection_by_matrix_id %>%
  map(., ~{stoch.sens(.)})

scenario1_stoch.sens[1] # disagree with scenario1_stoch.sens2 but consistent with scenario1_stoch.sens0

scenario1_stoch.sens2 <- map(scenario1_projection_by_matrix_id , ~{stoch.sens(.x)})

scenario1_stoch.sens2[1] #  


```


