---
output:
    bookdown::word_document2:
      toc: false
      fig_caption: yes
    reference_docx: style_template.docx
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(purrr) # for map2()
library(pracma)
library(popbio)
library(tidyverse)
```


```{r periodic-matrices-phase}
## Pre-planting tillage 
spring_tillage <-  readRDS("../2-Data/Clean/pre-planting-tillage.RData")

## Emergence 
emergence_scenario1 <- readRDS("../2-Data/Clean/emergence-prop-scenario1.RData")

## Seed survival and plant survival 
#### seed survival 

summer_seed_survival_scenario1  <- readRDS("../2-Data/Clean/summer-seed-survival-scenario1.RData")

#### plant survival
female_survival <- readRDS("../2-Data/Clean/summer-seedling-survival-scenario2.RData")
#### combine seed and plant survivals into one matrix with element-wise multiplication 
summer_survival_scenario1 <- purrr::map2(summer_seed_survival_scenario1 , female_survival, `*`)

## Fecundity scenario 1

fecundity_2019 <- readRDS("../2-Data/Clean/fecundity-mean-19-cohort.RData")

## Post-harvest tillage
post_harvest_tillage <- readRDS("../2-Data/Clean/post-harvest-tillage.RData")

## Overwinter survival 
overwinter_scenario1 <- readRDS("../2-Data/Clean/winter-seed-survival-scenario1.RData")


```

```{r phase-wise-projection-1}
# The model clock starts at spring tillage
#

scenario1_projection_by_matrix_id <- pmap(list(spring_tillage,
                                               emergence_scenario1,
                                               summer_survival_scenario1,
                                               fecundity_2019,
                                               post_harvest_tillage,
                                               overwinter_scenario1), list) %>% 
  simplify() %>%
  map(.,
    ~{names(.) <-  c("spring_tillage",
                     "emergence",
                     "summer_survival_Sosnoskie_2013",
                     "fecundity_2019",
                     "post_harvest_tillage",
                     "overwinter_Sosnoskie_2013"); .}) 

# assign row and column names
#https://stackoverflow.com/questions/71612217/error-in-assign-dimnames-to-all-matrices-in-a-list/71612339#71612339

scenario1_projection_by_matrix_id_dimnamed <- rapply(scenario1_projection_by_matrix_id, function(x)
  {dimnames(x) <- rep(list(c("seed_top","seed_bottom",
                             "plant_cohort_1", "plant_cohort_2",
                             "plant_cohort_3", "plant_cohort_4",
                             "plant_cohort_5", "plant_cohort_6")), 2); x}, how="list")



# multiply all the periodic matrices within a crop ID
scenario1_projection <- scenario1_projection_by_matrix_id  %>%
  map(., ~{Reduce( "%*%", .)}) #not crossprod, because crossprod(X,Y) = t(X)%*%Y

```


```{r scenario1-rotation-wise-project}
#### Improve: grab all elements with "4", "3", "2", ..., the shuffle conditionally 
### How would waterhemp population grow in each cropping system?
## Each rotation can be started at different crop phase
## Need other numbers than lambda: Suffix in each sequence tells where the cycle start, further work in -shuffle.Rmd

# rearrange scenario1_projection by rotation

scenario1_rotation_wise_4yr_conv <- scenario1_projection[c("A4_conv", "O4_conv", "S4_conv", "C4_conv")]

#4-year, low
scenario1_rotation_wise_4yr_low <- scenario1_projection[c("A4_low", "O4_low", "S4_low", "C4_low")]

#3-year, conventional
scenario1_rotation_wise_3yr_conv <- scenario1_projection[c("O3_conv", "S3_conv", "C3_conv")]

#3-year, low
scenario1_rotation_wise_3yr_low <- scenario1_projection[c("O3_low", "S3_low", "C3_low")]

#2year, conventional
scenario1_rotation_wise_2yr_conv <- scenario1_projection[c("S2_conv", "C2_conv")]

#2year, low
scenario1_rotation_wise_2yr_low <- scenario1_projection[c("S2_low","C2_low")]

# bind by rotation
scenario1_list_rotation <- list(scenario1_rotation_wise_4yr_conv,
                                     scenario1_rotation_wise_4yr_low,
                                     scenario1_rotation_wise_3yr_conv,
                                     scenario1_rotation_wise_3yr_low,
                                     scenario1_rotation_wise_2yr_conv,
                                     scenario1_rotation_wise_2yr_low) 
names(scenario1_list_rotation) <- c("4_year_conv",
                                    "4_year_low",
                                    "3_year_conv",
                                    "3_year_low",
                                    "2_year_conv",
                                    "2_year_low")

# Rotation-wise projection: 
lapply(scenario1_list_rotation, function(i){
  Reduce("%*%",i)
}) 

# the above lapply returned the same as the map below

scenario1_projection <- scenario1_list_rotation %>%
  map(., ~{Reduce( "%*%", .)})

# eigen analysis
scenario1_rotation_eigen <- scenario1_projection  %>%
  map(., ~{eigen.analysis(.)})
```

```{r scenario1-projection-test, include=FALSE}
## Testing if projection matrices turned out the same with different starting points in the current rotations: NO, starting phase affects projection matrices, returned the same lambda, but other statistics are different, such as repro.value, stable.stage, elasticities and sensitivities. 
scenario1_rotation_wise_2yr_low_corn <- scenario1_projection[c("S2_low","C2_low")]


scenario1_rotation_wise_2yr_low_soy <- scenario1_projection[c("C2_low","S2_low")]

l <- list(scenario1_rotation_wise_2yr_low_corn, scenario1_rotation_wise_2yr_low_soy)

l_project <- lapply(l, function(i){
  Reduce("%*%",i)
})

l_eigen <- lapply(l_project, function(i){
  eigen.analysis(i)
})

scenario1_list_rotation_4yr_test <-  mget(paste0(c("scenario1_rotation_wise_4yr_conv_corn",
                                           "scenario1_rotation_wise_4yr_low_corn",
                                          "scenario1_rotation_wise_4yr_conv_soybean",
                                           "scenario1_rotation_wise_4yr_low_soybean",
                                          "scenario1_rotation_wise_4yr_conv_oat",
                                           "scenario1_rotation_wise_4yr_low_oat",
                                          "scenario1_rotation_wise_4yr_conv_alfalfa",
                                           "scenario1_rotation_wise_4yr_low_alfalfa")))

scenario1_list_rotation_3yr_test <-  mget(paste0(c("scenario1_rotation_wise_3yr_conv_corn",
                                      "scenario1_rotation_wise_3yr_low_corn",
                                      "scenario1_rotation_wise_3yr_conv_soybean",
                                      "scenario1_rotation_wise_3yr_low_soybean",
                                      "scenario1_rotation_wise_3yr_conv_oat",
                                      "scenario1_rotation_wise_3yr_low_oat")))
                                      
                                      
scenario1_list_rotation_2yr <-  mget(paste0(c("scenario1_rotation_wise_2yr_conv_corn",
                                      "scenario1_rotation_wise_2yr_low_corn",
                                      "scenario1_rotation_wise_2yr_conv_soybean",
                                      "scenario1_rotation_wise_2yr_low_soybean")))


scenario1_project_4yr <- lapply(scenario1_list_rotation_4yr, function(i){
  Reduce("%*%",i)
})

scenario1_project_4yr_eigen <- lapply(scenario1_project_4yr, function(i){
  popbio::eigen.analysis(i)})

scenario1_project_3yr <- lapply(scenario1_list_rotation_3yr, function(i){
  Reduce("%*%",i)
})

scenario1_project_3yr_eigen <- lapply(scenario1_project_3yr, function(i){
  popbio::eigen.analysis(i)})

scenario1_project_2yr <- lapply(scenario1_list_rotation_2yr, function(i){
  Reduce("%*%",i)
})

scenario1_project_2yr_eigen <- lapply(scenario1_project_2yr, function(i){
  popbio::eigen.analysis(i)})

rapply(scenario1_project_4yr_eigen , function(x){nthroot(x,4)}, how = "list") # lambda = 0.755 starting at any point in the current sequence.  
```

```{r scenario1-lambda-annualized, include=FALSE}
# Improve efficiency: do the nthroot all at once
# https://stackoverflow.com/questions/13608336/lapply-over-nested-list-and-retain-naming-structure

#https://stackoverflow.com/questions/20428742/select-first-element-of-nested-list
scenario1_rotation_lambda <- lapply(scenario1_rotation_eigen, `[[`, 1)
# https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/rapply 

# stable.stage doesn't sum to 1 after nthroot, but sum to 1 before nthroot
scenario1_annualized_4yr_rot <- rapply(scenario1_rotation_lambda[1:2], function(x) nthroot(x,4), how = "list")


scenario1_annualized_3yr_rot <- rapply(scenario1_rotation_lambda[3:4], function(x) nthroot(x,3), how = "list")

scenario1_annualized_2yr_rot <- rapply(scenario1_rotation_lambda[5:6], function(x) nthroot(x,2), how = "list")

```





#### seed how seedbank progress
```{r}
## Read seed column data  
seed_column <- readRDS("../2-Data/Raw/seed-column-2019-list.RData")
```

```{r phase-wise-seeds-1}

stoch.projection(matrices, n0, tmax = 50, nreps = 5000, prob = NULL,
  nmax = NULL, sumweight = rep(1, length(n0)), verbose = FALSE)
```

```{r test-rapply-, include = FALSE}
# transfer this to rotation-wise
## how the population progress within a year, through each period
#rapply(scenario1_projection_by_matrix_id, lambda, how = "list")


# not working yet
n_initial <- c(1000, 5000, rep(0,6))

#rapply(scenario1_projection_by_matrix_id, pop.projection(.,n = n_initial, iterations = 20), how = "list")

#scenario1_projection_by_matrix_id %>% map(., ~{pop.projection(., n = n_initial, iterations = 20)})

# lapply(scenario1_projection_by_matrix_id, pop.projection(n = n_initial, iterations = 20))


# sapply(scenario1_projection_by_matrix_id, pop.projection(,n = n_initial, iterations = 20))

# lapply(split(scenario1_projection_by_matrix_id, names(scenario1_projection_by_matrix_id)),
#       function(x) pop.projection(x, n= n_initial, iterations = 20))

# this works
# pop.projection(scenario1_projection_by_matrix_id$A4_conv$spring_tillage, n= n_initial, iterations = 20) # see _geo for the list[[i]] iteration

# maybe try rapply again

# sapply(scenario1_projection_by_matrix_id, function(x) sapply(x, pop.projection(x, n= n_initial, iterations = 20)))
```


```{r phase-wise-projection-2}
fecundity_2018 <- readRDS("../2-Data/Clean/fecundity-mean-18-cohort.RData")

# The model clock starts at spring tillage
#

scenario2_projection_by_matrix_id <- pmap(list(spring_tillage,
                                               emergence_scenario1,
                                               summer_survival_scenario1,
                                               fecundity_2018,
                                               post_harvest_tillage,
                                               overwinter_scenario1), list) %>% 
  simplify() %>%
  map(.,
    ~{names(.) <-  c("spring_tillage",
                     "emergence",
                     "summer_survival_Sosnoskie_2013",
                     "fecundity_2018",
                     "post_harvest_tillage",
                     "overwinter_Sosnoskie_2013"); .}) 

# assign row and column names
#https://stackoverflow.com/questions/71612217/error-in-assign-dimnames-to-all-matrices-in-a-list/71612339#71612339

scenario2_projection_by_matrix_id_dimnamed <- rapply(scenario2_projection_by_matrix_id, function(x)
  {dimnames(x) <- rep(list(c("seed_top","seed_bottom",
                             "plant_cohort_1", "plant_cohort_2",
                             "plant_cohort_3", "plant_cohort_4",
                             "plant_cohort_5", "plant_cohort_6")), 2); x}, how="list")

```

```{r save-subsets}
scenario1_projection_by_matrix_id_dimnamed_subset <- scenario1_projection_by_matrix_id_dimnamed[c("C2_conv", "S2_conv")] 

saveRDS(scenario1_projection_by_matrix_id_dimnamed_subset , file="~/Documents/Dissertation/periodic-matrix-subset/subset1.RData")

write.csv(scenario1_projection_by_matrix_id_dimnamed_subset,
          "~/Documents/Dissertation/periodic-matrix-subset/subset1.csv")

scenario2_projection_by_matrix_id_dimnamed_subset <- scenario2_projection_by_matrix_id_dimnamed[c("C2_conv", "S2_conv")] 

saveRDS(scenario2_projection_by_matrix_id_dimnamed_subset , file="~/Documents/Dissertation/periodic-matrix-subset/subset2.RData")

write.csv(scenario2_projection_by_matrix_id_dimnamed_subset,
          "~/Documents/Dissertation/periodic-matrix-subset/subset2.csv")

```

