---
title: 'Q1: how low is seed production allowance - 2 year rotation'
output: html_document 
---

## General pattern: In a corn monoculture, aiming at 945 seeds/plant (sd on natural logarithm scale under 0.86) shall keep the original population of 1000 seeds per meter squared stable.

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(readr)
library(magrittr) # for %<>%
library(nlme) # for gls
library(emmeans) # for joint_tests
library(patchwork)
library(popbio)
set.seed(722)
```

### first seed column
```{r}
starting_point <-  c(1000, 0, 0, 0, 0, 0, 0, 0) #1000 seeds top soil, 0 seed deep soil,0 plants from cohorts 1 through 6
```


### tillage matrices  

```{r tillage-sim}
fall_tillage <-readRDS("../2-Data/Clean/mean-post-harvest-tillage.RData")

spring_tillage <-readRDS("../2-Data/Clean/mean-pre-planting-tillage.RData")
```

### overwinter survival matrix  

```{r overwinter-sim}
overwinter <- readRDS("../2-Data/Clean/mean-winter-seed-survival-Sosnoskie.RData")
```

### emergence matrix  

```{r emerge-sim, echo=FALSE}
emergence <-readRDS("../2-Data/Clean/mean-emergence-prop.RData")
emergence$C2_conv
```


### seed survival rate and seedling to maturity success rate 

```{r survive-sim, echo=FALSE}
summer_seed_survival <- readRDS("../2-Data/Clean/mean-summer-seed-survival-Sosnoskie.RData")

#### plant survival: literature data - named as scenario2, because scenario1 is the point-estimates from the experiment 
#female_survival <- readRDS("../2-Data/Clean/female-survival-rate-cohort-equal.RData")

female_survival <- readRDS("../2-Data/Clean/mean-summer-seedling-survival-Hartzler.RData")

#### combine seed and plant survivals into one matrix with element-wise multiplication: this is not computing, but arranging using 1's as placeholders 
summer_survival <- purrr::map2(summer_seed_survival, female_survival, `*`)

summer_survival$C2_conv
```

### fecundity manipulation plan  

```{r fecund-sim}
# First step: use a cumulative fecundity of all cohorts as `
#new_seeds_total`=  mature_plant_total * fecundity_sim
# change fecundity_sim  to get lambda as close to 1 as possible 

# Focus next: manipulate cohorts 1 and 2 in corn and soybean fecundity only because 1) these cohorts are more likely exposed to control measures and 2) they have higher survival rates than cohorts 3+ 

# cohort 3+ fecundity: estimated fecundity as in population projection 

# Final goal: flatten the fecundity distribution curve in corn and soybean to see seed production "allowance" in cohorts 1 and 2

### find good pairs of mean and sd for rlnorm in Q1-fecund-prep

fecundity18 <- readRDS("../2-Data/Clean/mean-fecundity-18-cohort.RData")
```



#### at t = 1: 1000 seeds, from t = 2: rlnorm(1, 6.85, 0.86)

```{r rot-2yr}
# event sequence: seed dropped - chisel - overwinter - field cultivator - emerge - survive - new seed

# create a function 
# vec: starting seed column
# poh: post-harvest tillage
# ow: over winter seed survival
# prt: pre-planting-tillage
# em: emergence
# sv: seed survival rate and seedling to maturity success rate
# poh_S, ow_S, prt_S, em_S, sv_S
rot_2year <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S){
  
  seed_C <- fecundity18$C2_conv
  seed_C[1,3] <- rlnorm(1, 4.88, 0.95)
  seed_C[2,3] <- rlnorm(1, 4.88, 0.95)
  
  seed_S <- fecundity18$S2_conv
  seed_S[1,3] <- rlnorm(1, 4.88, 0.95)
  seed_S[2,3] <- rlnorm(1, 4.88, 0.95)

    
#   after_corn <- seed_C %*% sv_C %*% em_C %*% prt_C %*%  ow_C %*%  poh_C %*% vec # corn phase dynamics

   after_soy <- seed_S %*% sv_S %*% em_S %*% prt_S %*%  ow_S %*%  poh_S %*% after_corn # soybean phase dynamics

#  full_cycle <-  seed_S %*% sv_S %*% em_S %*% prt_S %*%  ow_S %*%  poh_S %*% seed_C %*% sv_C %*% em_C %*% prt_C %*%  ow_C %*%  poh_C
  
#  lambda_cycle <- popbio::lambda(full_cycle)
  
#  lambda_cycle_annualized <- sqrt(lambda_cycle)
 
#  c(lambda_cycle,lambda_cycle_annualized)
   
   after_soy
}
```


```{r r2-conv-sim1}

t <- 50
N <- list() # blank dataframe to save loop output 
## Calculate N0
N0 <- rot_2year(vec = starting_point, 
#corn dynamics
   poh_C = fall_tillage$C2_conv,
   ow_C = overwinter$C2_conv,
   prt_C  = spring_tillage$C2_conv,
   em_C  = emergence$C2_conv,
   sv_C = summer_survival$C2_conv,

#soybean dynamics   
  poh_S = fall_tillage$S2_conv,
   ow_S = overwinter$S2_conv,
   prt_S  = spring_tillage$S2_conv,
   em_S  = emergence$S2_conv,
   sv_S = summer_survival$S2_conv)

# N0

 N[[1]] <- N0


#loop over the "corn" function for C2-conv for "t" times 

for (i in 2:t) { 
    N[[i]] = rot_2year(vec = N[[i-1]],
                  poh_C = fall_tillage$C2_conv,
   ow_C = overwinter$C2_conv,
   prt_C  = spring_tillage$C2_conv,
   em_C  = emergence$C2_conv,
   sv_C = summer_survival$C2_conv,

#soybean dynamics   
  poh_S = fall_tillage$S2_conv,
   ow_S = overwinter$S2_conv,
   prt_S  = spring_tillage$S2_conv,
   em_S  = emergence$S2_conv,
   sv_S = summer_survival$S2_conv)
}

View(N) 
```
 
```{r}
N_df <- N %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(no_ = ".") %>%
  dplyr::mutate(category = rep(c("seed_top", "seed_bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(category %in% c("seed_top", "seed_bottom")) %>%
 # dplyr::select(!rowname) %>%
  tidyr::pivot_wider(names_from = category,
                    values_from = no_,
                     values_fn = list) %>% 
    unnest(cols = everything() ) %>%
    mutate(cycle_no = seq(1:t))

#%>%
#  pivot_longer(!cycle_no, names_to = "stratum", values_to = "no_")
  

```

```{r sim1-plot}
N_df %>%
  ggplot() +
   aes(x = time_step, y = no_, group = stratum) +
  geom_line(aes(y = no_, linetype =  stratum)) +
  geom_point(aes(y  = no_, shape =  stratum))
```

