---
output:
#  bookdown::word_document2:
  bookdown::html_document2:
      toc: false
      fig_caption: yes
      keep_md: true
bibliography: WH-pop-dynamics.bib
csl: apa-no-ampersand.csl 
---

The data in the model projection was used in this simulation. 100 iterations of simulation were run per each rotation crossed with corn weed management regime.  

Goal: manipulate mature plant density for cohorts 1 through 3 via survival rate manipulation

```{r, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(readr)
library(magrittr) # for %<>%
library(nlme) # for gls
library(emmeans) # for joint_tests
library(patchwork)
library(pracma) #for nthroot
source("mature-plant-threshold-simulation-functions.R")
set.seed(722)
```


```{r, echo=FALSE}
starting_point <-  c(10000, 0, 0, 0, 0, 0, 0, 0) #10000 seeds top soil, 0 seed deep soil,0 plants from cohorts 1 through 6
t = 100
```

```{r tillage-sim-b, echo=FALSE}
fall_tillage <-readRDS("../2-Data/Clean/mean-post-harvest-tillage.RData")

spring_tillage <-readRDS("../2-Data/Clean/mean-pre-planting-tillage.RData")
```



```{r overwinter-sim-b, echo=FALSE}
overwinter <- readRDS("../2-Data/Clean/mean-winter-seed-survival-Sosnoskie.RData")
```



```{r emerge-sim-b, echo=FALSE}
emergence <-readRDS("../2-Data/Clean/mean-emergence-prop-adjusted.RData")
```



```{r survive-sim-b, echo=FALSE}
summer_seed_survival <- readRDS("../2-Data/Clean/mean-summer-seed-survival-Sosnoskie.RData")

#### plant survival: literature data - named as scenario2, because scenario1 is the point-estimates from the experiment 
#female_survival <- readRDS("../2-Data/Clean/female-survival-rate-cohort-equal.RData")

female_survival <- readRDS("../2-Data/Clean/mean-summer-seedling-survival-Hartzler.RData")

#### combine seed and plant survivals into one matrix with element-wise multiplication: this is not computing, but arranging using 1's as placeholders 
summer_survival <- purrr::map2(summer_seed_survival, female_survival, `*`)
```



```{r fecund-sim-b, echo=FALSE}
fecundity18 <- readRDS("../2-Data/Clean/mean-fecundity-18-cohort.RData")
```



```{r 2yr-lambda-sim-b, echo = TRUE}
# event sequence: seed dropped - field cultivator - emerge - survive - new seed - chisel - overwinter 
# create a function 
# vec: starting seed column
# prt: pre-planting-tillage
# em: emergence
# sv: seed survival rate and seedling to maturity success rate
# seed: fecundity
# poh: post-harvest tillage
# ow: over winter seed survival

##### with corn under conventional weed management {-}
N_2yr_conv_lambda <- list() # blank data frame to save loop output 
N_2yr_conv_lambda[[1]] <- starting_point 

for (i in 2:t) { 
  N_2yr_conv_lambda[[i]] = rot_2year_conv_lambda(vec = N_2yr_conv_lambda[[i-1]],
                              poh_C = fall_tillage$C2_conv,
                              ow_C = overwinter$C2_conv,
                              prt_C  = spring_tillage$C2_conv,
                              em_C  = emergence$C2_conv,
                              sv_C = summer_survival$C2_conv,
                              seed_C = fecundity18$C2_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S2_conv,
                              ow_S = overwinter$S2_conv,
                              prt_S  = spring_tillage$S2_conv,
                              em_S  = emergence$S2_conv,
                              sv_S = summer_survival$S2_conv,
                              seed_S = fecundity18$S2_conv)
}

N_2yr_conv_lambda_df <- N_2yr_conv_lambda %>% 
  unlist(recursive = TRUE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom", 
                                "cohort_1", "cohort_2", 
                                "cohort_3", "cohort_4",
                                "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything())  %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "2-year",
         Corn_weed_management = "conventional") 

##### with corn under low herbicide weed management {-}
N_2yr_low_lambda <- list() # blank dataframe to save loop output 

N_2yr_low_lambda[[1]] <- starting_point 
for (i in 2:t) { 
  N_2yr_low_lambda[[i]] = rot_2year_conv_lambda(vec = N_2yr_low_lambda[[i-1]],
                             poh_C = fall_tillage$C2_low,
                             ow_C = overwinter$C2_low,
                             prt_C  = spring_tillage$C2_low,
                             em_C  = emergence$C2_low,
                             sv_C = summer_survival$C2_low,
                             seed_C = fecundity18$C2_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S2_low,
                             ow_S = overwinter$S2_low,
                             prt_S  = spring_tillage$S2_low,
                             em_S  = emergence$S2_low,
                             sv_S = summer_survival$S2_low,
                             seed_S = fecundity18$S2_low)
}

N_2yr_low_lambda_df <-  N_2yr_low_lambda %>% 
  unlist(recursive = TRUE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom", 
                                "cohort_1", "cohort_2", 
                                "cohort_3", "cohort_4",
                                "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything())  %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "2-year",
         Corn_weed_management = "low") 
```


  
```{r 2yr-manipulated-outputs}
### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix
N_2yr_conv_manipulated <- rot_2year_conv_manipulated_outputs(vec = starting_point,
                              poh_C = fall_tillage$C2_conv,
                              ow_C = overwinter$C2_conv,
                              prt_C  = spring_tillage$C2_conv,
                              em_C  = emergence$C2_conv,
                              sv_C = summer_survival$C2_conv,
                              seed_C = fecundity18$C2_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S2_conv,
                              ow_S = overwinter$S2_conv,
                              prt_S  = spring_tillage$S2_conv,
                              em_S  = emergence$S2_conv,
                              sv_S = summer_survival$S2_conv,
                              seed_S = fecundity18$S2_conv)



N_2yr_conv_manipulated_df <- N_2yr_conv_manipulated %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(manipulated_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 6)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "conventional",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = manipulated_output, names_from = variable)

### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix

N_2yr_low_manipulated <- rot_2year_low_manipulated_outputs(vec = starting_point,
                             poh_C = fall_tillage$C2_low,
                             ow_C = overwinter$C2_low,
                             prt_C  = spring_tillage$C2_low,
                             em_C  = emergence$C2_low,
                             sv_C = summer_survival$C2_low,
                             seed_C = fecundity18$C2_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S2_low,
                             ow_S = overwinter$S2_low,
                             prt_S  = spring_tillage$S2_low,
                             em_S  = emergence$S2_low,
                             sv_S = summer_survival$S2_low,
                             seed_S = fecundity18$S2_low)


N_2yr_low_manipulated_df <- N_2yr_low_manipulated %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(manipulated_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 6)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "low",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = manipulated_output, names_from = variable)
```



```{r 2yr-original-outputs}
N_2yr_conv_original <- rot_2year_original_outputs(vec = starting_point,
                              poh_C = fall_tillage$C2_conv,
                              ow_C = overwinter$C2_conv,
                              prt_C  = spring_tillage$C2_conv,
                              em_C  = emergence$C2_conv,
                              sv_C = summer_survival$C2_conv,
                              seed_C = fecundity18$C2_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S2_conv,
                              ow_S = overwinter$S2_conv,
                              prt_S  = spring_tillage$S2_conv,
                              em_S  = emergence$S2_conv,
                              sv_S = summer_survival$S2_conv,
                              seed_S = fecundity18$S2_conv)



N_2yr_conv_original_df <- N_2yr_conv_original %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(original_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 6)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "conventional",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = original_output, names_from = variable)

### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix

N_2yr_low_original <- rot_2year_original_outputs(vec = starting_point,
                             poh_C = fall_tillage$C2_low,
                             ow_C = overwinter$C2_low,
                             prt_C  = spring_tillage$C2_low,
                             em_C  = emergence$C2_low,
                             sv_C = summer_survival$C2_low,
                             seed_C = fecundity18$C2_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S2_low,
                             ow_S = overwinter$S2_low,
                             prt_S  = spring_tillage$S2_low,
                             em_S  = emergence$S2_low,
                             sv_S = summer_survival$S2_low,
                             seed_S = fecundity18$S2_low)


N_2yr_low_original_df <- N_2yr_low_original %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(manipulated_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 6)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "low",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = manipulated_output, names_from = variable)
```


```{r 2-year-all-outputs-b}
N_2yr_conv_all <- N_2yr_conv_lambda_df %>%
  left_join(N_2yr_conv_manipulated_df) %>%
  left_join(N_2yr_conv_original_df)

N_2yr_low_all <- N_2yr_low_lambda_df %>% 
  left_join(N_2yr_low_manipulated_df) %>%
  left_join(N_2yr_low_original_df)
```


```{r 3yr-lambda-sim-b, echo=TRUE}
##### with corn under conventional weed management {-}
N_3yr_conv_lambda <- list() # blank dataframe to save loop output 

N_3yr_conv_lambda[[1]] <- starting_point 


for (i in 2:t) { 
  N_3yr_conv_lambda[[i]] = rot_3year_conv_lambda(vec = N_3yr_conv_lambda[[i-1]],
                              poh_C = fall_tillage$C3_conv,
                              ow_C = overwinter$C3_conv,
                              prt_C  = spring_tillage$C3_conv,
                              em_C  = emergence$C3_conv,
                              sv_C = summer_survival$C3_conv,
                              seed_C = fecundity18$C3_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S3_conv,
                              ow_S = overwinter$S3_conv,
                              prt_S  = spring_tillage$S3_conv,
                              em_S  = emergence$S3_conv,
                              sv_S = summer_survival$S3_conv,
                              seed_S = fecundity18$S3_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O3_conv,
                              ow_O = overwinter$O3_conv,
                              prt_O  = spring_tillage$O3_conv,
                              em_O  = emergence$O3_conv,
                              sv_O = summer_survival$O3_conv,
                              seed_O = fecundity18$O3_conv)
}

N_3yr_conv_lambda_df <-  N_3yr_conv_lambda %>% 
  unlist(recursive = TRUE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom",
                                "cohort_1", "cohort_2",
                                "cohort_3", "cohort_4",
                                "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything() ) %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "3-year",
         Corn_weed_management = "conventional") 

##### with corn under low herbicide weed management {-} 
N_3yr_low_lambda <- list() # blank dataframe to save loop output 

N_3yr_low_lambda[[1]] <- starting_point 


for (i in 2:t) { 
  N_3yr_low_lambda[[i]] = rot_3year_low_lambda(vec = N_3yr_low_lambda[[i-1]],
                             poh_C = fall_tillage$C3_conv,
                             ow_C = overwinter$C3_low,
                             prt_C  = spring_tillage$C3_low,
                             em_C  = emergence$C3_low,
                             sv_C = summer_survival$C3_low,
                             seed_C = fecundity18$C3_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S3_low,
                             ow_S = overwinter$S3_low,
                             prt_S  = spring_tillage$S3_low,
                             em_S  = emergence$S3_low,
                             sv_S = summer_survival$S3_low,
                             seed_S = fecundity18$S3_low,
                             
                             #oat dynamics   
                             poh_O = fall_tillage$O3_low,
                             ow_O = overwinter$O3_low,
                             prt_O  = spring_tillage$O3_low,
                             em_O  = emergence$O3_low,
                             sv_O = summer_survival$O3_low,
                             seed_O = fecundity18$O3_low)
}

N_3yr_low_lambda_df <-  N_3yr_low_lambda %>% 
  unlist(recursive = TRUE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom",
                                "cohort_1", "cohort_2",
                                "cohort_3", "cohort_4",
                                "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything() ) %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "3-year",
         Corn_weed_management = "low") 
```


```{r 3yr-manipulated-outputs}
### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix
N_3yr_conv_manipulated <- rot_3year_conv_manipulated_outputs(vec = starting_point,
                              poh_C = fall_tillage$C3_conv,
                              ow_C = overwinter$C3_conv,
                              prt_C  = spring_tillage$C3_conv,
                              em_C  = emergence$C3_conv,
                              sv_C = summer_survival$C3_conv,
                              seed_C = fecundity18$C3_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S3_conv,
                              ow_S = overwinter$S3_conv,
                              prt_S  = spring_tillage$S3_conv,
                              em_S  = emergence$S3_conv,
                              sv_S = summer_survival$S3_conv,
                              seed_S = fecundity18$S3_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O3_conv,
                              ow_O = overwinter$O3_conv,
                              prt_O  = spring_tillage$O3_conv,
                              em_O  = emergence$O3_conv,
                              sv_O = summer_survival$O3_conv,
                              seed_O = fecundity18$O3_conv)



N_3yr_conv_manipulated_df <- N_3yr_conv_manipulated %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(manipulated_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 9)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "conventional",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = manipulated_output, names_from = variable)

### Output: Survival rate,  mature plant densities until seed production and seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix

N_3yr_low_manipulated <- rot_3year_low_manipulated_outputs(vec = starting_point,
                             poh_C = fall_tillage$C3_conv,
                             ow_C = overwinter$C3_low,
                             prt_C  = spring_tillage$C3_low,
                             em_C  = emergence$C3_low,
                             sv_C = summer_survival$C3_low,
                             seed_C = fecundity18$C3_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S3_low,
                             ow_S = overwinter$S3_low,
                             prt_S  = spring_tillage$S3_low,
                             em_S  = emergence$S3_low,
                             sv_S = summer_survival$S3_low,
                             seed_S = fecundity18$S3_low,
                             
                             #oat dynamics   
                             poh_O = fall_tillage$O3_low,
                             ow_O = overwinter$O3_low,
                             prt_O  = spring_tillage$O3_low,
                             em_O  = emergence$O3_low,
                             sv_O = summer_survival$O3_low,
                             seed_O = fecundity18$O3_low)


N_3yr_low_manipulated_df <- N_3yr_low_manipulated %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(manipulated_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 9)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "low",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = manipulated_output, names_from = variable)
```


```{r 3yr-original-outputs}
N_3yr_conv_original <- rot_3year_original_outputs(vec = starting_point,
                            poh_C = fall_tillage$C3_conv,
                              ow_C = overwinter$C3_conv,
                              prt_C  = spring_tillage$C3_conv,
                              em_C  = emergence$C3_conv,
                              sv_C = summer_survival$C3_conv,
                              seed_C = fecundity18$C3_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S3_conv,
                              ow_S = overwinter$S3_conv,
                              prt_S  = spring_tillage$S3_conv,
                              em_S  = emergence$S3_conv,
                              sv_S = summer_survival$S3_conv,
                              seed_S = fecundity18$S3_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O3_conv,
                              ow_O = overwinter$O3_conv,
                              prt_O  = spring_tillage$O3_conv,
                              em_O  = emergence$O3_conv,
                              sv_O = summer_survival$O3_conv,
                              seed_O = fecundity18$O3_conv)


N_3yr_conv_original_df <- N_3yr_conv_original %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(original_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 9)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "conventional",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = original_output, names_from = variable)

### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix

N_3yr_low_original <- rot_3year_original_outputs(vec = starting_point,
                             poh_C = fall_tillage$C3_conv,
                             ow_C = overwinter$C3_low,
                             prt_C  = spring_tillage$C3_low,
                             em_C  = emergence$C3_low,
                             sv_C = summer_survival$C3_low,
                             seed_C = fecundity18$C3_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S3_low,
                             ow_S = overwinter$S3_low,
                             prt_S  = spring_tillage$S3_low,
                             em_S  = emergence$S3_low,
                             sv_S = summer_survival$S3_low,
                             seed_S = fecundity18$S3_low,
                             
                             #oat dynamics   
                             poh_O = fall_tillage$O3_low,
                             ow_O = overwinter$O3_low,
                             prt_O  = spring_tillage$O3_low,
                             em_O  = emergence$O3_low,
                             sv_O = summer_survival$O3_low,
                             seed_O = fecundity18$O3_low)


N_3yr_low_original_df <- N_3yr_low_original %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(manipulated_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 9)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "low",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = manipulated_output, names_from = variable)
```


```{r 3-year-all-outputs-b}
N_3yr_conv_all <- N_3yr_conv_lambda_df %>%
  left_join(N_3yr_conv_manipulated_df) %>%
  left_join(N_3yr_conv_original_df)

N_3yr_low_all <- N_3yr_low_lambda_df %>% 
  left_join(N_3yr_low_manipulated_df) %>%
  left_join(N_3yr_low_original_df)
```



```{r 4yr-lambda-sim-b, echo=TRUE}
##### with corn under conventional weed management {-}
N_4yr_conv_lambda <- list() # blank dataframe to save loop output 

N_4yr_conv_lambda[[1]] <- starting_point 

for (i in 2:t) { 
  N_4yr_conv_lambda[[i]] = rot_4year_conv_lambda(vec = N_4yr_conv_lambda[[i-1]],
                              poh_C = fall_tillage$C4_conv,
                              ow_C = overwinter$C4_conv,
                              prt_C  = spring_tillage$C4_conv,
                              em_C  = emergence$C4_conv,
                              sv_C = summer_survival$C4_conv,
                              seed_C = fecundity18$C4_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_conv,
                              ow_S = overwinter$S4_conv,
                              prt_S  = spring_tillage$S4_conv,
                              em_S  = emergence$S4_conv,
                              sv_S = summer_survival$S4_conv,
                              seed_S = fecundity18$S4_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_conv,
                              ow_O = overwinter$O4_conv,
                              prt_O  = spring_tillage$O4_conv,
                              em_O  = emergence$O4_conv,
                              sv_O = summer_survival$O4_conv,
                              seed_O = fecundity18$O4_conv,
                              
                              #alfalfa dynamics   
                          poh_A = fall_tillage$A4_conv,
                          ow_A = overwinter$A4_conv,
                          prt_A  = spring_tillage$A4_conv,
                          em_A  = emergence$A4_conv,
                          sv_A = summer_survival$A4_conv,
                          seed_A = fecundity18$A4_conv)
}

N_4yr_conv_lambda_df <-  N_4yr_conv_lambda %>% 
  unlist(recursive = TRUE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom",
                                "cohort_1", "cohort_2",
                                "cohort_3", "cohort_4",
                                "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything())  %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "4-year",
         Corn_weed_management = "conventional") 

##### with corn under low herbicide weed management {-} 
N_4yr_low_lambda <- list() # blank dataframe to save loop output 

N_4yr_low_lambda[[1]] <- starting_point 

for (i in 2:t) { 
  N_4yr_low_lambda[[i]] = rot_4year_low_lambda(vec = N_4yr_low_lambda[[i-1]],
                              poh_C = fall_tillage$C4_low,
                              ow_C = overwinter$C4_low,
                              prt_C  = spring_tillage$C4_low,
                              em_C  = emergence$C4_low,
                              sv_C = summer_survival$C4_low,
                              seed_C = fecundity18$C4_low,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_low,
                              ow_S = overwinter$S4_low,
                              prt_S  = spring_tillage$S4_low,
                              em_S  = emergence$S4_low,
                              sv_S = summer_survival$S4_low,
                              seed_S = fecundity18$S4_low,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_low,
                              ow_O = overwinter$O4_low,
                              prt_O  = spring_tillage$O4_low,
                              em_O  = emergence$O4_low,
                              sv_O = summer_survival$O4_low,
                              seed_O = fecundity18$O4_low,
                              
                              #alfalfa dynamics   
                              poh_A = fall_tillage$A4_low,
                              ow_A = overwinter$A4_low,
                              prt_A  = spring_tillage$A4_low,
                              em_A  = emergence$A4_low,
                              sv_A = summer_survival$A4_low,
                              seed_A = fecundity18$A4_low)
}

N_4yr_low_lambda_df <-  N_4yr_low_lambda %>% 
  unlist(recursive = TRUE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom",
                                "cohort_1", "cohort_2",
                                "cohort_3", "cohort_4",
                                "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything())  %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = nthroot(lambda_cycle, 4),
         Rotation = "4-year",
         Corn_weed_management = "low")
```


```{r 4yr-manipulated-outputs}
### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix
N_4yr_conv_manipulated <- rot_4year_conv_manipulated_outputs(vec = starting_point,
                             poh_C = fall_tillage$C4_conv,
                              ow_C = overwinter$C4_conv,
                              prt_C  = spring_tillage$C4_conv,
                              em_C  = emergence$C4_conv,
                              sv_C = summer_survival$C4_conv,
                              seed_C = fecundity18$C4_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_conv,
                              ow_S = overwinter$S4_conv,
                              prt_S  = spring_tillage$S4_conv,
                              em_S  = emergence$S4_conv,
                              sv_S = summer_survival$S4_conv,
                              seed_S = fecundity18$S4_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_conv,
                              ow_O = overwinter$O4_conv,
                              prt_O  = spring_tillage$O4_conv,
                              em_O  = emergence$O4_conv,
                              sv_O = summer_survival$O4_conv,
                              seed_O = fecundity18$O4_conv,
                              
                              #alfalfa dynamics   
                          poh_A = fall_tillage$A4_conv,
                          ow_A = overwinter$A4_conv,
                          prt_A  = spring_tillage$A4_conv,
                          em_A  = emergence$A4_conv,
                          sv_A = summer_survival$A4_conv,
                          seed_A = fecundity18$A4_conv)



N_4yr_conv_manipulated_df <- N_4yr_conv_manipulated %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(manipulated_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 12)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "conventional",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = manipulated_output, names_from = variable)

### Output: Survival rate,  mature plant densities until seed production and seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix

N_4yr_low_manipulated <- rot_4year_low_manipulated_outputs(vec = starting_point,
                            poh_C = fall_tillage$C4_low,
                              ow_C = overwinter$C4_low,
                              prt_C  = spring_tillage$C4_low,
                              em_C  = emergence$C4_low,
                              sv_C = summer_survival$C4_low,
                              seed_C = fecundity18$C4_low,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_low,
                              ow_S = overwinter$S4_low,
                              prt_S  = spring_tillage$S4_low,
                              em_S  = emergence$S4_low,
                              sv_S = summer_survival$S4_low,
                              seed_S = fecundity18$S4_low,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_low,
                              ow_O = overwinter$O4_low,
                              prt_O  = spring_tillage$O4_low,
                              em_O  = emergence$O4_low,
                              sv_O = summer_survival$O4_low,
                              seed_O = fecundity18$O4_low,
                              
                              #alfalfa dynamics   
                              poh_A = fall_tillage$A4_low,
                              ow_A = overwinter$A4_low,
                              prt_A  = spring_tillage$A4_low,
                              em_A  = emergence$A4_low,
                              sv_A = summer_survival$A4_low,
                              seed_A = fecundity18$A4_low)


N_4yr_low_manipulated_df <- N_4yr_low_manipulated %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(manipulated_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 12)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "low",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = manipulated_output, names_from = variable)
```


```{r 4yr-original-outputs}
N_4yr_conv_original <- rot_4year_original_outputs(vec = starting_point,
                            poh_C = fall_tillage$C4_conv,
                              ow_C = overwinter$C4_conv,
                              prt_C  = spring_tillage$C4_conv,
                              em_C  = emergence$C4_conv,
                              sv_C = summer_survival$C4_conv,
                              seed_C = fecundity18$C4_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_conv,
                              ow_S = overwinter$S4_conv,
                              prt_S  = spring_tillage$S4_conv,
                              em_S  = emergence$S4_conv,
                              sv_S = summer_survival$S4_conv,
                              seed_S = fecundity18$S4_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_conv,
                              ow_O = overwinter$O4_conv,
                              prt_O  = spring_tillage$O4_conv,
                              em_O  = emergence$O4_conv,
                              sv_O = summer_survival$O4_conv,
                              seed_O = fecundity18$O4_conv,
                              
                              #alfalfa dynamics   
                          poh_A = fall_tillage$A4_conv,
                          ow_A = overwinter$A4_conv,
                          prt_A  = spring_tillage$A4_conv,
                          em_A  = emergence$A4_conv,
                          sv_A = summer_survival$A4_conv,
                          seed_A = fecundity18$A4_conv)



N_4yr_conv_original_df <- N_4yr_conv_original %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(original_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 12)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "conventional",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = original_output, names_from = variable)

### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix

N_4yr_low_original <- rot_4year_original_outputs(vec = starting_point,
                             poh_C = fall_tillage$C4_low,
                              ow_C = overwinter$C4_low,
                              prt_C  = spring_tillage$C4_low,
                              em_C  = emergence$C4_low,
                              sv_C = summer_survival$C4_low,
                              seed_C = fecundity18$C4_low,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_low,
                              ow_S = overwinter$S4_low,
                              prt_S  = spring_tillage$S4_low,
                              em_S  = emergence$S4_low,
                              sv_S = summer_survival$S4_low,
                              seed_S = fecundity18$S4_low,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_low,
                              ow_O = overwinter$O4_low,
                              prt_O  = spring_tillage$O4_low,
                              em_O  = emergence$O4_low,
                              sv_O = summer_survival$O4_low,
                              seed_O = fecundity18$O4_low,
                              
                              #alfalfa dynamics   
                              poh_A = fall_tillage$A4_low,
                              ow_A = overwinter$A4_low,
                              prt_A  = spring_tillage$A4_low,
                              em_A  = emergence$A4_low,
                              sv_A = summer_survival$A4_low,
                              seed_A = fecundity18$A4_low)


N_4yr_low_original_df <- N_4yr_low_original %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>%
  tibble::rownames_to_column(., "variable") %>%
  dplyr::rename(manipulated_output = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 12)) %>%
   mutate(Crop_ID = substr(variable, 1, 2),
          Corn_weed_management = "low",
          variable = substr(variable, 4, 19)) %>%
  pivot_wider(values_from = manipulated_output, names_from = variable)
```


```{r 4-year-all-outputs-b}
N_4yr_conv_all <- N_4yr_conv_lambda_df %>%
  left_join(N_4yr_conv_manipulated_df) %>%
  left_join(N_4yr_conv_original_df)

N_4yr_low_all <- N_4yr_low_lambda_df %>% 
  left_join(N_4yr_low_manipulated_df) %>%
  left_join(N_4yr_low_original_df)
```


```{r, include=FALSE}
mature_plant_allowance_sim_df <- rbind(N_2yr_conv_all,
                                N_2yr_low_all,
                                N_3yr_conv_all,
                                N_3yr_low_all,
                                N_4yr_conv_all ,
                                N_4yr_low_all)
                              
mature_plant_allowance_sim_df <- mature_plant_allowance_sim_df %>%
  mutate(survival_manipulated = ifelse(manipulated_surv == original_survive, "no", "yes")) 
```

```{r mature-plant-threshold-tab}
mature_plant_allowance_sim_df %>%
  mutate(plant_control_efficacy = 1 - manipulated_surv) %>%
  group_by(Crop_ID, Corn_weed_management, cohort) %>%
  summarise(mean_efficacy = mean(plant_control_efficacy)) %>%
  pivot_wider(names_from = cohort, values_from = mean_efficacy) %>%
    mutate(phase_order = ifelse(str_detect(Crop_ID, "C"), 1,
                              ifelse(str_detect(Crop_ID, "S"), 2,
                                     ifelse(str_detect(Crop_ID, "O"), 3, 4)))) %>%
  mutate(Rot = substr(Crop_ID,2,2))%>%
  arrange(Rot, phase_order, Corn_weed_management) %>%
    mutate_at(vars(`1`:`6`), funs(round(., 2))) %>%
  select(Crop_ID, Corn_weed_management, `1`:`6`) %>%
  flextable() %>%
    set_caption("Manipulated control efficacy (with respect to seedling survival to maturity) averaged over 100 rotational cycles (the 2-year rotation cycled over two years and ended at the soybean phase, the 3-year rotation cycled over three years and ended at the oat phase, and the 4-year rotation cycled over four years and ended at the alfalfa phase). All simulations started with a seed column of 10000 female seeds in the top 0 - 2 cm soil stratum and 0 female seeds in the bottom 2 - 20 cm soil stratum.")  %>%
  set_header_labels(values = list(Crop_ID = "Crop ID",
                                  Corn_weed_management = "Corn weed management",
               `1` = "cohort 1",
               `2` = "cohort 2",
               `3` = "cohort 2",
               `4` = "cohort 4",
               `5` = "cohort 5",
               `6` = "cohort 6"))
  
```


```{r annualized-lambda-against-manipulated-survival, echo=FALSE, fig.cap= "Population size at the end of a rotation cycle over 100 rotational cycles (the 2-year rotation ended at the soybean phase, the 3-year rotation ended at the oat phase, and the 4-year rotation ended at the alfalfa phase). All simulations started with a seed column of 10000 female seeds in the top 0 - 2 cm soil stratum and 0 female seed in the bottom 2 - 20 cm soil stratum. The simulation applied improved weed control efficacy on cohorts 1 through 3 in corn and soybean only. The relationships of aboveground mass and fecundity in Nguyen and Liebman (2022a) were used to estimate cohort-based fecundity. It was expected that no waterhemp cohorts in any crop environments but only the cohorts 1 through 3 in corn and soybean had their survival rates manipulated to find the mature plant density thresholds. However, additional control efficacy was needed in some crop phases outside of the expected groups to reduced the mature plant densities. The crop phases marked with an asterik (*) are where control measures extended beyond the expected cohorts within the expected crop environments would be neccessary. Each panel was annotated with the average fecundity thresholds for the first three waterhemp cohorts in corn and soybean followed by the whole crop phase. The crop phases marked with an inverted comma (') are where no additional control was applied. The red horizontal line marks lambda = 1.", fig.height = 6, fig.width = 6}

mature_plant_allowance_sim_df$Crop_ID <- factor(mature_plant_allowance_sim_df$Crop_ID,
                                        levels = c("C2","S2",
                                                   "C3", "S3", "O3",
                                                   "C4", "S4", "O4", "A4"))


mature_plant_allowance_sim_df  %>%
    na.omit() %>%
     ggplot() +
   aes(x = 100*manipulated_surv, 
       y = lambda_annualized,
       group = survival_manipulated) +
   facet_grid(Crop_ID ~ cohort) +
    geom_hline(yintercept = 1, color = "black") +
    scale_color_brewer(palette = "Set1") +
  geom_point(aes(y  = lambda_annualized, 
                 color = survival_manipulated,
                 shape = Corn_weed_management)) +
  scale_shape_manual(values = c(1, 4)) +
  ylab("Annualized population growth rate") +
  xlab(expression(paste("Necessary control efficacy by cohort (%)"))) + 
  theme_bw() +
  guides(shape = guide_legend(title = "Corn \nweed management"),
         color = guide_legend(title = "Plant survival \nmanipulated")) +
  theme(legend.position = "top")
```






