---
output:
  bookdown::word_document2:
#  bookdown::html_document2:
      toc: false
      fig_caption: yes
      keep_md: true
bibliography: WH-pop-dynamics.bib
csl: apa-no-ampersand.csl 
---

The data in the model projection was used in this simulation. 100 iterations of simulation were run per each rotation crossed with corn weed management regime.  

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(readr)
library(magrittr) # for %<>%
library(nlme) # for gls
library(emmeans) # for joint_tests
library(patchwork)
library(pracma) #for nthroot
set.seed(722)
```


```{r, echo=FALSE}
starting_point <-  c(10000, 0, 0, 0, 0, 0, 0, 0) #10000 seeds top soil, 0 seed deep soil,0 plants from cohorts 1 through 6
```

```{r tillage-sim, echo=FALSE}
fall_tillage <-readRDS("../2-Data/Clean/mean-post-harvest-tillage.RData")

spring_tillage <-readRDS("../2-Data/Clean/mean-pre-planting-tillage.RData")
```



```{r overwinter-sim, echo=FALSE}
overwinter <- readRDS("../2-Data/Clean/mean-winter-seed-survival-Sosnoskie.RData")
```



```{r emerge-sim, echo=FALSE}
emergence <-readRDS("../2-Data/Clean/mean-emergence-prop.RData")
```



```{r survive-sim, echo=FALSE}
summer_seed_survival <- readRDS("../2-Data/Clean/mean-summer-seed-survival-Sosnoskie.RData")

#### plant survival: literature data - named as scenario2, because scenario1 is the point-estimates from the experiment 
#female_survival <- readRDS("../2-Data/Clean/female-survival-rate-cohort-equal.RData")

female_survival <- readRDS("../2-Data/Clean/mean-summer-seedling-survival-Hartzler.RData")

#### combine seed and plant survivals into one matrix with element-wise multiplication: this is not computing, but arranging using 1's as placeholders 
summer_survival <- purrr::map2(summer_seed_survival, female_survival, `*`)
```



```{r fecund-sim, echo=FALSE}
# First step: use a cumulative fecundity of all cohorts as `
#new_seeds_total`=  mature_plant_total * fecundity_sim
# change fecundity_sim  to get lambda as close to 1 as possible 

# Focus next: manipulate cohorts 1 and 2 in corn and soybean fecundity only because 1) these cohorts are more likely exposed to control measures and 2) they have higher survival rates than cohorts 3+ 

# cohort 3+ fecundity: estimated fecundity as in population projection 

# Final goal: flatten the fecundity distribution curve in corn and soybean to see seed production "allowance" in cohorts 1 and 2

### find good pairs of mean and sd for rlnorm in Q1-fecund-prep

fecundity18 <- readRDS("../2-Data/Clean/mean-fecundity-18-cohort.RData")
```



```{r rot-2yr-function, echo=TRUE}
# event sequence: seed dropped - chisel - overwinter - field cultivator - emerge - survive - new seed

# create a function 
# vec: starting seed column
# poh: post-harvest tillage
# ow: over winter seed survival
# prt: pre-planting-tillage
# em: emergence
# sv: seed survival rate and seedling to maturity success rate
# seed: fecundity

rot_2year_conv <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C, seed_C,
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S){
  

  seed_C[1,3] <- rlnorm(1, 2.65, 0.89)
  seed_C[1,4] <- rlnorm(1, 2.65, 0.89)
  seed_C[1,5] <- rlnorm(1, 2.65, 0.89) 


  seed_S[1,3] <- rlnorm(1, 2.65, 0.89)
  seed_S[1,4] <- rlnorm(1, 2.65, 0.89)
  seed_S[1,5] <- rlnorm(1, 2.65, 0.89)


 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
# soybean phase dynamics

   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S  %*% after_corn 

   after_soy
}

rot_2year_low <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C, seed_C,
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S){
  

  seed_C[1,3] <- rlnorm(1, 4.81, 0.56)
  seed_C[1,4] <- rlnorm(1, 4.81, 0.56)
  seed_C[1,5] <- rlnorm(1, 4.81, 0.56)


  seed_S[1,3] <- rlnorm(1,  4.81, 0.56)
  seed_S[1,4] <- rlnorm(1,  4.81, 0.56)
  seed_S[1,5] <- rlnorm(1,  4.81, 0.56)

 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C  %*% vec 
# soybean phase dynamics

   after_soy <-  ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%  after_corn 

   after_soy
}
```

```{r 2yr-conv-sim1, echo = TRUE}
##### with corn under conventional weed management {-}
t <- 100
N_2yr_conv <- list() # blank data frame to save loop output 
N_2yr_conv[[1]] <- starting_point 

for (i in 2:t) { 
  N_2yr_conv[[i]] = rot_2year_conv(vec = N_2yr_conv[[i-1]],
                              poh_C = fall_tillage$C2_conv,
                              ow_C = overwinter$C2_conv,
                              prt_C  = spring_tillage$C2_conv,
                              em_C  = emergence$C2_conv,
                              sv_C = summer_survival$C2_conv,
                              seed_C = fecundity18$C2_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S2_conv,
                              ow_S = overwinter$S2_conv,
                              prt_S  = spring_tillage$S2_conv,
                              em_S  = emergence$S2_conv,
                              sv_S = summer_survival$S2_conv,
                              seed_S = fecundity18$S2_conv)
}

N_2yr_conv_df <-  N_2yr_conv %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(counts = ".") %>%
  dplyr::mutate(category = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(category %in% c("top", "bottom")) %>%
    unnest(cols = everything() ) %>%
    mutate(cycle_no = rep(1:t, each = 2)) %>%
  group_by(category) %>%
  mutate(lambda_cycle = counts/lag(counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "2-year",
         Corn_weed_management = "conventional") %>%
    na.omit() 
```
 

 
```{r 2yr-low-sim1, echo=TRUE}
##### with corn under low herbicide weed management {-}
N_2yr_low <- list() # blank dataframe to save loop output 

N_2yr_low[[1]] <- starting_point 
for (i in 2:t) { 
  N_2yr_low[[i]] = rot_2year_low(vec = N_2yr_low[[i-1]],
                             poh_C = fall_tillage$C2_low,
                             ow_C = overwinter$C2_low,
                             prt_C  = spring_tillage$C2_low,
                             em_C  = emergence$C2_low,
                             sv_C = summer_survival$C2_low,
                             seed_C = fecundity18$C2_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S2_low,
                             ow_S = overwinter$S2_low,
                             prt_S  = spring_tillage$S2_low,
                             em_S  = emergence$S2_low,
                             sv_S = summer_survival$S2_low,
                             seed_S = fecundity18$S2_low)
}

N_2yr_low_df <-  N_2yr_low %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(counts = ".") %>%
  dplyr::mutate(category = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(category %in% c("top", "bottom")) %>%
    unnest(cols = everything() ) %>%
    mutate(cycle_no = rep(1:t, each = 2)) %>%
  group_by(category) %>%
  mutate(lambda_cycle = counts/lag(counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "2-year",
         Corn_weed_management = "low") %>%
    na.omit() 
```
  


```{r rot-3yr-function, echo=TRUE}
rot_3year_conv <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O){
  

  seed_C[1,3] <- rlnorm(1, 5.34, 0.5)
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5)
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5)


  seed_S[1,3] <- rlnorm(1, 5.34, 0.5)
  seed_S[1,4] <- rlnorm(1, 5.34, 0.5)
  seed_S[1,5] <- rlnorm(1, 5.34, 0.5)

# corn phase dynamics  
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*%  vec 
 # soybean phase dynamics
   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%   after_corn
# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
   
  after_oat
}

### low herbicide weed management
## Manipulation note: if cohorts 1 through 3 were reduced to rlnorm(1, 2.65, 0.89), alphas are around 0.5 --> super "safe", but hard
## cohorts 1 through 3 at rlnorm(1, 5.2, 0.51): more realistic
rot_3year_low <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O){
  

  seed_C[1,3] <- rlnorm(1, 5.34, 0.5)
#  seed_C[1,3] <- rlnorm(1, 2.65, 0.89)
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5)
#   seed_C[1,4] <- rlnorm(1, 2.65, 0.89)
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5)


  seed_S[1,3] <- rlnorm(1, 5.34, 0.5)
#  seed_S[1,3] <- rlnorm(1, 2.65, 0.89)
  seed_S[1,4] <- rlnorm(1, 5.34, 0.5)
#  seed_S[1,4] <-  rlnorm(1, 2.65, 0.89)
  seed_S[1,5] <- rlnorm(1, 5.34, 0.5)

# corn phase dynamics  
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*%  vec 
 # soybean phase dynamics
   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%   after_corn
# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
   
  after_oat
}
```

```{r 3yr-conv-sim1, echo=TRUE}
##### with corn under conventional weed management {-}
N_3yr_conv <- list() # blank dataframe to save loop output 

N_3yr_conv[[1]] <- starting_point 


for (i in 2:t) { 
  N_3yr_conv[[i]] = rot_3year_conv(vec = N_3yr_conv[[i-1]],
                              poh_C = fall_tillage$C3_conv,
                              ow_C = overwinter$C3_conv,
                              prt_C  = spring_tillage$C3_conv,
                              em_C  = emergence$C3_conv,
                              sv_C = summer_survival$C3_conv,
                              seed_C = fecundity18$C3_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S3_conv,
                              ow_S = overwinter$S3_conv,
                              prt_S  = spring_tillage$S3_conv,
                              em_S  = emergence$S3_conv,
                              sv_S = summer_survival$S3_conv,
                              seed_S = fecundity18$S3_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O3_conv,
                              ow_O = overwinter$O3_conv,
                              prt_O  = spring_tillage$O3_conv,
                              em_O  = emergence$O3_conv,
                              sv_O = summer_survival$O3_conv,
                              seed_O = fecundity18$O3_conv)
}

N_3yr_conv_df <-  N_3yr_conv %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(counts = ".") %>%
  dplyr::mutate(category = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(category %in% c("top", "bottom")) %>%
    unnest(cols = everything() ) %>%
    mutate(cycle_no = rep(1:t, each = 2)) %>%
  group_by(category) %>%
  mutate(lambda_cycle = counts/lag(counts),
         lambda_annualized = nthroot(lambda_cycle,3),
          Rotation = "3-year",
         Corn_weed_management = "conventional") %>%
    na.omit() 
```
 

```{r 3yr-low-sim1, echo=TRUE}
##### with corn under low herbicide weed management {-} 
N_3yr_low <- list() # blank dataframe to save loop output 

N_3yr_low[[1]] <- starting_point 


for (i in 2:t) { 
  N_3yr_low[[i]] = rot_3year_low(vec = N_3yr_low[[i-1]],
                             poh_C = fall_tillage$C3_conv,
                             ow_C = overwinter$C3_low,
                             prt_C  = spring_tillage$C3_low,
                             em_C  = emergence$C3_low,
                             sv_C = summer_survival$C3_low,
                             seed_C = fecundity18$C3_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S3_low,
                             ow_S = overwinter$S3_low,
                             prt_S  = spring_tillage$S3_low,
                             em_S  = emergence$S3_low,
                             sv_S = summer_survival$S3_low,
                             seed_S = fecundity18$S3_low,
                             
                             #oat dynamics   
                             poh_O = fall_tillage$O3_low,
                             ow_O = overwinter$O3_low,
                             prt_O  = spring_tillage$O3_low,
                             em_O  = emergence$O3_low,
                             sv_O = summer_survival$O3_low,
                             seed_O = fecundity18$O3_low)
}

N_3yr_low_df <-  N_3yr_low %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(counts = ".") %>%
  dplyr::mutate(category = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(category %in% c("top", "bottom")) %>%
    unnest(cols = everything() ) %>%
    mutate(cycle_no = rep(1:t, each = 2)) %>%
  group_by(category) %>%
  mutate(lambda_cycle = counts/lag(counts),
         lambda_annualized = nthroot(lambda_cycle,3),
          Rotation = "3-year",
         Corn_weed_management = "low") %>%
    na.omit()
```




```{r rot-4yr-function, echo=TRUE}
### conventional weed management
rot_4year_conv <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O,
                       poh_A, ow_A, prt_A, em_A, sv_A, seed_A){
  
  seed_C[1,3] <- rlnorm(1, 7.34, 0.44)
  seed_C[1,4] <- rlnorm(1, 5.75, 0.46)
  seed_C[1,5] <- rlnorm(1, 5.75, 0.46)


  seed_S[1,3] <- rlnorm(1, 7.34, 0.44)
  seed_S[1,4] <- rlnorm(1, 5.75, 0.46)
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46)

# corn phase dynamics  
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*%  vec 
 # soybean phase dynamics
   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%   after_corn
# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
# alfalfa phase dynamics
after_alfalfa <-   ow_A %*%  poh_A %*% seed_A %*% sv_A %*% em_A %*% prt_A %*% after_oat 
   
  after_alfalfa
}

### low herbicide weed management
rot_4year_low <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O,
                       poh_A, ow_A, prt_A, em_A, sv_A, seed_A){
  
  seed_C[1,3] <- rlnorm(1, 5.75, 0.46)
  seed_C[1,4] <- rlnorm(1, 5.75, 0.46)
  seed_C[1,5] <- rlnorm(1, 5.75, 0.46)


  seed_S[1,3] <- rlnorm(1, 5.75, 0.46)
  seed_S[1,4] <- rlnorm(1, 5.75, 0.46)
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46)

# corn phase dynamics  
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*%  vec 
 # soybean phase dynamics
   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%   after_corn
# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy  
# alfalfa phase dynamics
  after_alfalfa <-   ow_A %*%  poh_A %*% seed_A %*% sv_A %*% em_A %*% prt_A %*% after_oat 
   
  after_alfalfa
}
```

```{r 4yr-conv-sim1, echo=TRUE}
##### with corn under conventional weed management {-}
N_4yr_conv <- list() # blank dataframe to save loop output 

N_4yr_conv[[1]] <- starting_point 

for (i in 2:t) { 
  N_4yr_conv[[i]] = rot_4year_conv(vec = N_4yr_conv[[i-1]],
                              poh_C = fall_tillage$C4_conv,
                              ow_C = overwinter$C4_conv,
                              prt_C  = spring_tillage$C4_conv,
                              em_C  = emergence$C4_conv,
                              sv_C = summer_survival$C4_conv,
                              seed_C = fecundity18$C4_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_conv,
                              ow_S = overwinter$S4_conv,
                              prt_S  = spring_tillage$S4_conv,
                              em_S  = emergence$S4_conv,
                              sv_S = summer_survival$S4_conv,
                              seed_S = fecundity18$S4_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_conv,
                              ow_O = overwinter$O4_conv,
                              prt_O  = spring_tillage$O4_conv,
                              em_O  = emergence$O4_conv,
                              sv_O = summer_survival$O4_conv,
                              seed_O = fecundity18$O4_conv,
                              
                              #alfalfa dynamics   
                          poh_A = fall_tillage$A4_conv,
                          ow_A = overwinter$A4_conv,
                          prt_A  = spring_tillage$A4_conv,
                          em_A  = emergence$A4_conv,
                          sv_A = summer_survival$A4_conv,
                          seed_A = fecundity18$A4_conv)
}

N_4yr_conv_df <-  N_4yr_conv %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
  dplyr::rename(counts = ".") %>%
  dplyr::mutate(category = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
  filter(category %in% c("top", "bottom")) %>%
  unnest(cols = everything() ) %>%
  mutate(cycle_no = rep(1:t, each = 2)) %>%
  group_by(category) %>%
  mutate(lambda_cycle = counts/lag(counts),
         lambda_annualized = nthroot(lambda_cycle,4),
         Rotation = "4-year",
         Corn_weed_management = "conventional") %>%
  na.omit() 

```
 

```{r 4yr-low-sim1, echo=TRUE}
##### with corn under low herbicide weed management {-} 
N_4yr_low <- list() # blank dataframe to save loop output 

N_4yr_low[[1]] <- starting_point 

for (i in 2:t) { 
  N_4yr_low[[i]] = rot_4year_low(vec = N_4yr_low[[i-1]],
                              poh_C = fall_tillage$C4_low,
                              ow_C = overwinter$C4_low,
                              prt_C  = spring_tillage$C4_low,
                              em_C  = emergence$C4_low,
                              sv_C = summer_survival$C4_low,
                              seed_C = fecundity18$C4_low,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_low,
                              ow_S = overwinter$S4_low,
                              prt_S  = spring_tillage$S4_low,
                              em_S  = emergence$S4_low,
                              sv_S = summer_survival$S4_low,
                              seed_S = fecundity18$S4_low,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_low,
                              ow_O = overwinter$O4_low,
                              prt_O  = spring_tillage$O4_low,
                              em_O  = emergence$O4_low,
                              sv_O = summer_survival$O4_low,
                              seed_O = fecundity18$O4_low,
                              
                              #alfalfa dynamics   
                              poh_A = fall_tillage$A4_low,
                              ow_A = overwinter$A4_low,
                              prt_A  = spring_tillage$A4_low,
                              em_A  = emergence$A4_low,
                              sv_A = summer_survival$A4_low,
                              seed_A = fecundity18$A4_low)
}

N_4yr_low_df <-  N_4yr_low %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
  dplyr::rename(counts = ".") %>%
  dplyr::mutate(category = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
  filter(category %in% c("top", "bottom")) %>%
  unnest(cols = everything() ) %>%
  mutate(cycle_no = rep(1:t, each = 2)) %>%
  group_by(category) %>%
  mutate(lambda_cycle = counts/lag(counts),
         lambda_annualized = nthroot(lambda_cycle,4),
         Rotation = "4-year",
         Corn_weed_management = "low") %>%
  na.omit() 

```

```{r new-fecund, include = FALSE}
new_fecund <- read.csv("../2-Data/Clean/mean-fecundity-18-cohort-df.csv")

new_fecund_placeholder <- new_fecund %>%
  select(Crop_ID, Corn_weed_management, mean_seed,) %>%
  mutate(Cohort = rep(seq(1:6), 18))
C2_sim <- expand.grid(Crop_ID = "C2",
                      Corn_weed_management = c("conv", "low"),
                      Cohort = c(1:3),
                      ln_Seed = 2.66,
                      SE_ln_Seed = 0.21,
                      mean_seed = 13.58)

S2_sim <- C2_sim 
S2_sim$Crop_ID <- "S2"

C3_sim <- C2_sim
C3_sim$Crop_ID <- "C3"
C3_sim$ln_Seed <- rep(5.34, 3)
C3_sim$mean_seed <- rep(209,3)
C3_sim$SE_ln_Seed <- rep(0.21, 3)

S3_sim <- C3_sim; S3_sim$Crop_ID <- "S3"

C4_sim <- expand.grid(Crop_ID = "C4",
                      Corn_weed_management = c("conv", "low"),
                      Cohort = c(1:3),
                      ln_Seed = 0,
                      SE_ln_Seed = 0)

C4_sim$ln_Seed <- c(7.34, rep(5.75,5))
C4_sim$ln_Seed <- c(7.34, rep(5.75,5))
C4_sim$mean_seed <- c(1553, rep(317,5))

S4_sim <- C4_sim; S4_sim$Crop_ID <- "S4"

new_fecund_cool <- new_fecund_placeholder %>% filter(Crop_ID %in% c("O3", "O4", "A4"))

new_fecund_warm <- new_fecund_placeholder %>% 
  anti_join(new_fecund_cool) %>%
  filter(Cohort %in%c(4:6))

sim_fecund_warm <- rbind(C2_sim, S2_sim, C3_sim, S3_sim, C4_sim, S4_sim)

sim_fecund_warm_select <- sim_fecund_warm %>%
  select(Crop_ID, Corn_weed_management, Cohort, mean_seed)

sim_fecund <- rbind(new_fecund_cool, sim_fecund_warm_select, new_fecund_warm )

sim_fecund_sum <- sim_fecund %>%
  group_by(Crop_ID, Corn_weed_management) %>%
  summarize(total_seed = sum(mean_seed))

sim_fecund_3co <- sim_fecund_warm %>%
  group_by(Crop_ID, Corn_weed_management) %>%
  summarize(total_seed = sum(mean_seed))
sim_fecund_3co

sim_fecund_sum_rot <- sim_fecund_sum %>%
  mutate(Rotation = ifelse(Crop_ID %in% c("C2", "S2"), "2-year",
                           ifelse(Crop_ID %in% c("C3","S3","O3"), "3-year", "4-year"))) %>%
  group_by(Rotation, Corn_weed_management) %>%
  summarize(rot_total_seed = sum(total_seed))
```

```{r seed-allowance-sim-lambda-plot, echo=FALSE, fig.cap= "Population growth rates over 100 rotational cycles. All simulations started with a seed column of 10000 female seeds in the top 0 - 2 cm soil stratum and 0 female seed in the bottom 2 - 18 cm soil stratum. The simulation applied weed management on cohorts 1 through 3 in corn and soybean only. The relationships of aboveground mass and fecundity in Nguyen and Liebman (2022b) were used to estimate cohort-based fecundity. In corn and soybean, only the fecundity of cohorts 1 through 3 fecundity were manipulated to find the seed allowance in the corn and soybean environments, the fecundity of cohorts 4 and beyond were kept as they were measured from 2018. Each panel was annotated with the average fecundity allowance for the first three plant cohorts and the whole crop phase. The red horizontal line marks lambda = 1.", fig.height= 8, fig.width=8}
seed_allowance_sim_df <- rbind(N_2yr_conv_df,
                                N_2yr_low_df,
                               N_3yr_conv_df,
                                N_3yr_low_df,
                               N_4yr_conv_df,
                                N_4yr_low_df)

seed_allowance_sim_df$category <- factor(seed_allowance_sim_df$category, levels = c("top", "bottom"))
 # label = c("2-year, conv: 1356 \n C2: 41 (614); S2: 41 (741)" , 
 #           "3-year, low: 10206 \n C3: 627 (889); S3: 627 (785)",
 #           "4-year, conv: 102909 \n 2187 (4821); S4: 2187 (3017)",
 #           "2-year, low: 2171 \n C2: 41 (491); S2: 41 (1680)",
 #           "3-year, conv: 444331 \n C3: 627 (1101); S3: 627 (2531)",
 #           "4-year, low: 67729 \n C4: 951 (2394); S4: 951 (2672)"),
sim_label <- data.frame(
  label = c("C2: 41 (614) \n S2: 41 (741)" , 
            "C3: 627 (889) \n S3: 627 (785)",
            "C4: 2187 (4821) \n S4: 2187 (3017)",
            "C2: 41 (491) \n S2: 41 (1680)",
            "C3: 627 (1101) \n S3: 627 (2531)",
            "C4: 951 (2394) \n S4: 951 (2672)"),
  Rotation = rep(c("2-year", "3-year", "4-year"), 2),
  Corn_weed_management = rep(c("conventional", "low"), 3),
  category = rep("placeholder", 6)
  ) 

seed_allowance_sim_df %>%
   ggplot() +
   aes(x = cycle_no, y = lambda_annualized, group = category) +
 # geom_line(aes(y = lambda_annualized, color =  category)) +
#  geom_point(aes(y  = lambda_annualized, color =  category, alpha = 0.5)) +
  geom_point(aes(y  = lambda_annualized, shape =  category)) +
  scale_shape_manual(values = c(1, 4)) +
  scale_color_brewer(palette = "Set1") +
#  geom_hline(yintercept = 1, color = "black") +
  geom_hline(yintercept = 1, color = "red") +
  facet_grid(Rotation ~ Corn_weed_management ) + 
  ylab("Annualized population growth rate") +
  xlab("Cycle number") + 
   ylim(0.4, 2) +
  theme(legend.position = "bottom",
        legend.title = element_blank()) + 
    geom_text(data = sim_label, aes(label = label), size = 3, x = 50, y = 1.75) 
```


```{r seed-allowance-sim-N-plot, echo=FALSE, fig.cap= "Population size at the end of a rotation cycle over 100 rotational cycles (the 2-year rotation ended at the soybean phase, the 3-year rotation ended at the oat phase, and the 4-year rotation ended at the alfalfa phase). All simulations started with a seed column of 10000 female seeds in the top 0 - 2 cm soil stratum and 0 female seed in the bottom 2 - 18 cm soil stratum. The simulation applied weed management on cohorts 1 through 3 in corn and soybean only. The relationships of aboveground mass and fecundity in Nguyen and Liebman (2022b) were used to estimate cohort-based fecundity. In corn and soybean, only the fecundity of cohorts 1 through 3 fecundity were manipulated to find the seed allowance in the corn and soybean environments, the fecundity of cohorts 4 and beyond were kept as they were measured from 2018. Each panel was annotated with the average fecundity thresholds for the first three waterhemp cohorts and the whole crop phase. The red horizontal line marks lambda = 1.", fig.height= 8, fig.width=8}

seed_allowance_sim_df %>%
   ggplot() +
   aes(x = cycle_no, y = log(counts), group = category) +
 # geom_line(aes(y = lambda_annualized, color =  category)) +
#  geom_point(aes(y  = lambda_annualized, color =  category, alpha = 0.5)) +
  geom_point(aes(y  = log(counts), shape =  category)) +
  scale_shape_manual(values = c(1, 4)) +
  geom_hline(yintercept = log(10000), color = "red") +
  facet_grid(Rotation ~ Corn_weed_management) + 
  ylab(expression(paste("ln(Seed density (seeds",~m^-2,"))"))) +
  xlab("Simulation iteration") + 
  theme_bw() +
  theme(legend.position = "bottom",
        legend.title = element_blank()) + 
    geom_text(data = sim_label, aes(label = label), size = 3, x = 75, y = 25) 
```



