---
output:
  bookdown::word_document2:
 # bookdown::html_document2:
      toc: false
      fig_caption: yes
      keep_md: true
bibliography: WH-pop-dynamics.bib
csl: apa-no-ampersand.csl 
---

The data in the model projection was used in this simulation. 100 iterations of simulation were run per each rotation crossed with corn weed management regime.  

```{r, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(readr)
library(magrittr) # for %<>%
library(nlme) # for gls
library(emmeans) # for joint_tests
library(patchwork)
library(pracma) #for nthroot
set.seed(722)
```


```{r, echo=FALSE}
starting_point <-  c(10000, 0, 0, 0, 0, 0, 0, 0) #10000 seeds top soil, 0 seed deep soil,0 plants from cohorts 1 through 6
```

```{r tillage-sim-a, echo=FALSE}
fall_tillage <-readRDS("../2-Data/Clean/mean-post-harvest-tillage.RData")

spring_tillage <-readRDS("../2-Data/Clean/mean-pre-planting-tillage.RData")
```



```{r overwinter-sim-a, echo=FALSE}
overwinter <- readRDS("../2-Data/Clean/mean-winter-seed-survival-Sosnoskie.RData")
```



```{r emerge-sim-a, echo=FALSE}
emergence <-readRDS("../2-Data/Clean/adjusted-mean-emergence-prop.RData")
```



```{r survive-sim-a, echo=FALSE}
summer_seed_survival <- readRDS("../2-Data/Clean/mean-summer-seed-survival-Sosnoskie.RData")

#### plant survival: literature data - named as scenario2, because scenario1 is the point-estimates from the experiment 
#female_survival <- readRDS("../2-Data/Clean/female-survival-rate-cohort-equal.RData")

female_survival <- readRDS("../2-Data/Clean/mean-summer-seedling-survival-Hartzler.RData")

#### combine seed and plant survivals into one matrix with element-wise multiplication: this is not computing, but arranging using 1's as placeholders 
summer_survival <- purrr::map2(summer_seed_survival, female_survival, `*`)
```



```{r fecund-sim-a, echo=FALSE}
# First step: use a cumulative fecundity of all cohorts as `
#new_seeds_total`=  mature_plant_total * fecundity_sim
# change fecundity_sim  to get lambda as close to 1 as possible 

# Focus next: manipulate cohorts 1 and 2 in corn and soybean fecundity only because 1) these cohorts are more likely exposed to control measures and 2) they have higher survival rates than cohorts 3+ 

# cohort 3+ fecundity: estimated fecundity as in population projection 

# Final goal: flatten the fecundity distribution curve in corn and soybean to see seed production "allowance" in cohorts 1 and 2

### find good pairs of mean and sd for rlnorm in Q1-fecund-prep

fecundity18 <- readRDS("../2-Data/Clean/mean-fecundity-18-cohort.RData")
```



```{r rot-2yr-function-seebank-output}
# event sequence: seed dropped - field cultivator - emerge - survive - new seed - chisel - overwinter 

# create a function 
# vec: starting seed column
# prt: pre-planting-tillage
# em: emergence
# sv: seed survival rate and seedling to maturity success rate
# seed: fecundity
# poh: post-harvest tillage
# ow: over winter seed survival

rot_2year_conv <- function(vec, prt_C, em_C, sv_C, seed_C, poh_C, ow_C, 
                           prt_S, em_S, sv_S, seed_S, poh_S, ow_S){
  

  seed_C[1,3] <- rlnorm(1, 5.55, 0.48) #257.03 seeds/plant
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5) # 208.18 seeds/plant
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5) 


  seed_S[1,3] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,4] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46) #316.83


 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 

   
# soybean phase dynamics

   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S  %*% after_corn 

   after_soy
}

rot_2year_low <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C, seed_C,
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S){
  

  seed_C[1,3] <- rlnorm(1, 3.85, 0.7) # 46.55 seeds/plant
  seed_C[1,4] <- rlnorm(1, 3.44, 0.76) # 30.84 seeds/plant
  seed_C[1,5] <- rlnorm(1, 3.85, 0.7)

  seed_S[1,3] <- rlnorm(1, 3.85, 0.7)
  seed_S[1,4] <- rlnorm(1, 3.85, 0.7)
  seed_S[1,5] <- rlnorm(1, 4.22, 0.65) #67.56 seeds/plant

 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
# soybean phase dynamics

   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S  %*% after_corn 

   after_soy
}
```

```{r 2yr-lambda-sim-a}
##### with corn under conventional weed management {-}

### Output: seedbank at top and bottom strata at the end of each crop phase
t <- 100
N_2yr_conv <- list() # blank data frame to save loop output 
N_2yr_conv[[1]] <- starting_point 

for (i in 2:t) { 
  N_2yr_conv[[i]] = rot_2year_conv(vec = N_2yr_conv[[i-1]],
                              poh_C = fall_tillage$C2_conv,
                              ow_C = overwinter$C2_conv,
                              prt_C  = spring_tillage$C2_conv,
                              em_C  = emergence$C2_conv,
                              sv_C = summer_survival$C2_conv,
                              seed_C = fecundity18$C2_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S2_conv,
                              ow_S = overwinter$S2_conv,
                              prt_S  = spring_tillage$S2_conv,
                              em_S  = emergence$S2_conv,
                              sv_S = summer_survival$S2_conv,
                              seed_S = fecundity18$S2_conv)
}

N_2yr_conv_df <-  N_2yr_conv %>% 
  unlist(recursive = TRUE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything())  %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "2-year",
         Corn_weed_management = "conventional") 

##### with corn under low herbicide weed management {-}
N_2yr_low <- list() # blank dataframe to save loop output 

N_2yr_low[[1]] <- starting_point 
for (i in 2:t) { 
  N_2yr_low[[i]] = rot_2year_low(vec = N_2yr_low[[i-1]],
                             poh_C = fall_tillage$C2_low,
                             ow_C = overwinter$C2_low,
                             prt_C  = spring_tillage$C2_low,
                             em_C  = emergence$C2_low,
                             sv_C = summer_survival$C2_low,
                             seed_C = fecundity18$C2_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S2_low,
                             ow_S = overwinter$S2_low,
                             prt_S  = spring_tillage$S2_low,
                             em_S  = emergence$S2_low,
                             sv_S = summer_survival$S2_low,
                             seed_S = fecundity18$S2_low)
}

N_2yr_low_df <-  N_2yr_low %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything() ) %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "2-year",
         Corn_weed_management = "low") 
```



```{r 2yr-seed-production-per-capita}
### CONV Output: seed production, after manipulation by cohort x crop phase x iteration

rot_2year_conv_seed_production_per_cap <- function(seed_C, seed_S){
  

  seed_C[1,3] <- rlnorm(1, 5.55, 0.48) #257.03 seeds/plant
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5) # 208.18 seeds/plant
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5) 


  seed_S[1,3] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,4] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46) #316.83
  
  
  seed_production_count_corn <- seed_C[1,3:8] 

  seed_production_count_soy <- seed_S[1,3:8]  

# seed at harvest
   
  l <- list(seed_production_count_corn, seed_production_count_soy)

  names(l) <- c("C2", "S2")
  
  l 
  
}

N_2yr_conv_seed_production_per_capita <- list() # blank data frame to save loop output 


for (i in 1:t) { 
  N_2yr_conv_seed_production_per_capita[[i]] = rot_2year_conv_seed_production_per_cap(seed_C = fecundity18$C2_conv, seed_S = fecundity18$S2_conv)
}

# original per capita seed production in fecundity18$C2_conv[1,3:8] and fecundity18$S2_conv[1,3:8]
N_2yr_conv_seed_production_per_capita_df <- N_2yr_conv_seed_production_per_capita  %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>% #corn was listed before soybean in the customized f.
  dplyr::rename(seed_per_capita_threshold = ".") %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), t*2)) %>%
   mutate(cycle_no = as.character(rep(1:t, each = 12))) %>%
   mutate(Crop_ID = rep(c(rep("C2", 6), rep("S2", 6)), t)) %>%
  mutate(seed_per_capita_original = rep(c(fecundity18$C2_conv[1,3:8], fecundity18$S2_conv[1,3:8]), t))

### LOW output

rot_2year_low_seed_production_per_cap <- function(seed_C, seed_S){
  

  seed_C[1,3] <- rlnorm(1, 5.55, 0.48) #257.03 seeds/plant
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5) # 208.18 seeds/plant
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5) 


  seed_S[1,3] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,4] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46) #316.83
  
  
  seed_production_count_corn <- seed_C[1,3:8] 

  seed_production_count_soy <- seed_S[1,3:8]  

# seed at harvest
   
  l <- list(seed_production_count_corn, seed_production_count_soy)

  names(l) <- c("C2", "S2")
  
  l 
  
}

N_2yr_low_seed_production_per_capita <- list() # blank data frame to save loop output 


for (i in 1:t) { 
  N_2yr_low_seed_production_per_capita[[i]] = rot_2year_low_seed_production_per_cap(seed_C = fecundity18$C2_low, seed_S = fecundity18$S2_low)
}


N_2yr_low_seed_production_per_capita_df <- N_2yr_low_seed_production_per_capita  %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>% #corn was listed before soybean in the customized f.
  dplyr::rename(seed_per_capita_threshold = ".") %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), t*2)) %>%
   mutate(cycle_no = as.character(rep(1:t, each = 12))) %>%
   mutate(Crop_ID = rep(c(rep("C2", 6), rep("S2", 6)), t)) %>%
  mutate(seed_per_capita_original = rep(c(fecundity18$C2_low[1,3:8], fecundity18$S2_low[1,3:8]), t))
```


```{r 2yr-plant-density-fixed}
### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix

rot_2year_conv_plant_density_fixed <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C, seed_C,
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S){
  

  seed_C[1,3] <- rlnorm(1, 5.55, 0.48) #257.03 seeds/plant
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5) # 208.18 seeds/plant
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5) 


  seed_S[1,3] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,4] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46) #316.83 seeds/plant


 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
   
   pl_dens_corn <-  sv_C %*% em_C %*% prt_C %*% vec 

# soybean phase dynamics

  pl_dens_soy  <-  sv_S %*% em_S %*% prt_S  %*% after_corn 

   
  l <- list(pl_dens_corn[3:8], pl_dens_soy[3:8])

 names(l) <- c("C2", "S2")
 
 l
}


N_2yr_conv_mature_plant_density_fixed <- rot_2year_conv_plant_density_fixed(vec = starting_point ,
                              poh_C = fall_tillage$C2_conv,
                              ow_C = overwinter$C2_conv,
                              prt_C  = spring_tillage$C2_conv,
                              em_C  = emergence$C2_conv,
                              sv_C = summer_survival$C2_conv,
                              seed_C = fecundity18$C2_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S2_conv,
                              ow_S = overwinter$S2_conv,
                              prt_S  = spring_tillage$S2_conv,
                              em_S  = emergence$S2_conv,
                              sv_S = summer_survival$S2_conv,
                              seed_S = fecundity18$S2_conv)

N_2yr_conv_mature_plant_density_fixed_df <- N_2yr_conv_mature_plant_density_fixed  %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>% #corn was listed before soybean in the customized f.
  dplyr::rename(plant_counts_fixed = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"),2)) %>%
   mutate(Crop_ID = c(rep("C2", 6), rep("S2", 6)))


### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix

rot_2year_low_plant_density_fixed <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C, seed_C,
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S){
  

  seed_C[1,3] <- rlnorm(1, 5.55, 0.48) #257.03 seeds/plant
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5) # 208.18 seeds/plant
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5) 


  seed_S[1,3] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,4] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46) #316.83 seeds/plant


 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
   
   pl_dens_corn <-  sv_C %*% em_C %*% prt_C %*% vec 

# soybean phase dynamics

  pl_dens_soy  <-  sv_S %*% em_S %*% prt_S  %*% after_corn 

   
  l <- list(pl_dens_corn[3:8], pl_dens_soy[3:8])

 names(l) <- c("C2", "S2")
 
 l
}


N_2yr_low_mature_plant_density_fixed <- rot_2year_low_plant_density_fixed(vec = starting_point ,
                             poh_C = fall_tillage$C2_low,
                             ow_C = overwinter$C2_low,
                             prt_C  = spring_tillage$C2_low,
                             em_C  = emergence$C2_low,
                             sv_C = summer_survival$C2_low,
                             seed_C = fecundity18$C2_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S2_low,
                             ow_S = overwinter$S2_low,
                             prt_S  = spring_tillage$S2_low,
                             em_S  = emergence$S2_low,
                             sv_S = summer_survival$S2_low,
                             seed_S = fecundity18$S2_low)

N_2yr_low_mature_plant_density_fixed_df <- N_2yr_low_mature_plant_density_fixed  %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>% #corn was listed before soybean in the customized f.
  dplyr::rename(plant_counts_fixed = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"),2)) %>%
   mutate(Crop_ID = c(rep("C2", 6), rep("S2", 6)))

```



```{r 2yr-sim-a-all-output}
# total stratified seedbank density and lambdas in N_2yr_conv_df
# manipulated seed production in N_2yr_conv_seed_production_per_capita_df
# fixed mature plant density in N_2yr_conv_mature_plant_density_fixed_df 

N_2yr_conv_all_df <- N_2yr_conv_seed_production_per_capita_df %>% 
  left_join(N_2yr_conv_df, by = "cycle_no") %>%
  left_join(N_2yr_conv_mature_plant_density_fixed_df, by = c("Crop_ID", "cohort")) %>%
  mutate(seed_production_threshold = seed_per_capita_threshold*plant_counts_fixed) %>%
  mutate(seed_production_control_efficacy = 1 - seed_per_capita_threshold/seed_per_capita_original) 


N_2yr_low_all_df <- N_2yr_low_seed_production_per_capita_df %>% 
  left_join(N_2yr_low_df, by = "cycle_no") %>%
  left_join(N_2yr_low_mature_plant_density_fixed_df, by = c("Crop_ID", "cohort")) %>%
  mutate(seed_production_threshold = seed_per_capita_threshold*plant_counts_fixed) %>%
  mutate(seed_production_control_efficacy = 1 - seed_per_capita_threshold/seed_per_capita_original) 
```


```{r rot-3yr-function-seedbank-output}
rot_3year_conv <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O){
  

  seed_C[1,3] <- rlnorm(1, 2.66, 0.89)
  seed_C[1,4] <- rlnorm(1, 2.66, 0.89)
  seed_C[1,5] <- rlnorm(1, 2.66, 0.89)
 # seed_C[1,6] <- rlnorm(1, 2.66, 0.89)
#  seed_C[1,7] <- rlnorm(1, 2.66, 0.89)
# seed_C[1,8] <- rlnorm(1, 2.66, 0.89)

  seed_S[1,3] <- rlnorm(1, 2.66, 0.89)
  seed_S[1,4] <- rlnorm(1, 2.66, 0.89)
  seed_S[1,5] <- rlnorm(1, 2.66, 0.89)
#  seed_S[1,6] <- rlnorm(1, 2.66, 0.89)
#  seed_S[1,7] <- rlnorm(1, 2.66, 0.89)
 # seed_S[1,8] <- rlnorm(1, 2.66, 0.89)

# corn phase dynamics  
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*%  vec 
 # soybean phase dynamics
   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%   after_corn
# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
   
  after_oat
}

### low herbicide weed management
## Manipulation note: if cohorts 1 through 3 were reduced to rlnorm(1, 2.65, 0.89), alphas are around 0.5 --> super "safe", but hard
## cohorts 1 through 3 at rlnorm(1, 5.2, 0.51): more realistic
rot_3year_low <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O){
  

  seed_C[1,3] <- rlnorm(1, 2.66, 0.89)
  seed_C[1,4] <- rlnorm(1, 2.66, 0.89)
  seed_C[1,5] <- rlnorm(1, 5.05, 0.53)


  seed_S[1,3] <- rlnorm(1, 2.66, 0.89)
  seed_S[1,4] <- rlnorm(1, 2.66, 0.89)
  seed_S[1,5] <- rlnorm(1, 6.94, 0.43)

# corn phase dynamics  
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*%  vec 
 # soybean phase dynamics
   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%   after_corn
# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
   
  after_oat
}
```

```{r 3yr-lambda-sim-a, echo=TRUE}
##### with corn under conventional weed management {-}
N_3yr_conv <- list() # blank dataframe to save loop output 

N_3yr_conv[[1]] <- starting_point 


for (i in 2:t) { 
  N_3yr_conv[[i]] = rot_3year_conv(vec = N_3yr_conv[[i-1]],
                              poh_C = fall_tillage$C3_conv,
                              ow_C = overwinter$C3_conv,
                              prt_C  = spring_tillage$C3_conv,
                              em_C  = emergence$C3_conv,
                              sv_C = summer_survival$C3_conv,
                              seed_C = fecundity18$C3_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S3_conv,
                              ow_S = overwinter$S3_conv,
                              prt_S  = spring_tillage$S3_conv,
                              em_S  = emergence$S3_conv,
                              sv_S = summer_survival$S3_conv,
                              seed_S = fecundity18$S3_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O3_conv,
                              ow_O = overwinter$O3_conv,
                              prt_O  = spring_tillage$O3_conv,
                              em_O  = emergence$O3_conv,
                              sv_O = summer_survival$O3_conv,
                              seed_O = fecundity18$O3_conv)
}

N_3yr_conv_df <-  N_3yr_conv %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything() ) %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "3-year",
         Corn_weed_management = "conventional") 

##### with corn under low herbicide weed management {-} 
N_3yr_low <- list() # blank dataframe to save loop output 

N_3yr_low[[1]] <- starting_point 


for (i in 2:t) { 
  N_3yr_low[[i]] = rot_3year_low(vec = N_3yr_low[[i-1]],
                             poh_C = fall_tillage$C3_conv,
                             ow_C = overwinter$C3_low,
                             prt_C  = spring_tillage$C3_low,
                             em_C  = emergence$C3_low,
                             sv_C = summer_survival$C3_low,
                             seed_C = fecundity18$C3_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S3_low,
                             ow_S = overwinter$S3_low,
                             prt_S  = spring_tillage$S3_low,
                             em_S  = emergence$S3_low,
                             sv_S = summer_survival$S3_low,
                             seed_S = fecundity18$S3_low,
                             
                             #oat dynamics   
                             poh_O = fall_tillage$O3_low,
                             ow_O = overwinter$O3_low,
                             prt_O  = spring_tillage$O3_low,
                             em_O  = emergence$O3_low,
                             sv_O = summer_survival$O3_low,
                             seed_O = fecundity18$O3_low)
}

N_3yr_low_df <-  N_3yr_low %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything() ) %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "3-year",
         Corn_weed_management = "low") 
```


```{r 3yr-plant-density-fixed}
### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix

rot_3year_conv_plant_density_fixed <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C, seed_C,
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O){
  

  seed_C[1,3] <- rlnorm(1, 5.55, 0.48) #257.03 seeds/plant
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5) # 208.18 seeds/plant
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5) 


  seed_S[1,3] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,4] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46) #316.83 seeds/plant


 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
   
   pl_dens_corn <-  sv_C %*% em_C %*% prt_C %*% vec 

# soybean phase dynamics
   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S  %*% after_corn 

  pl_dens_soy  <-  sv_S %*% em_S %*% prt_S  %*% after_corn 

# oat phase dynamics 
  after_oat <-  ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
  
  pl_dens_oat  <-  sv_O %*% em_O %*% prt_O  %*% after_soy 
   
  l <- list(pl_dens_corn[3:8], pl_dens_soy[3:8], pl_dens_oat[3:8])

 names(l) <- c("C3", "S3", "O3")
 
 l
}


N_3yr_conv_mature_plant_density_fixed <- rot_3year_conv_plant_density_fixed(vec = starting_point ,
                              poh_C = fall_tillage$C3_conv,
                              ow_C = overwinter$C3_conv,
                              prt_C  = spring_tillage$C3_conv,
                              em_C  = emergence$C3_conv,
                              sv_C = summer_survival$C3_conv,
                              seed_C = fecundity18$C3_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S3_conv,
                              ow_S = overwinter$S3_conv,
                              prt_S  = spring_tillage$S3_conv,
                              em_S  = emergence$S3_conv,
                              sv_S = summer_survival$S3_conv,
                              seed_S = fecundity18$S3_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O3_conv,
                              ow_O = overwinter$O3_conv,
                              prt_O  = spring_tillage$O3_conv,
                              em_O  = emergence$O3_conv,
                              sv_O = summer_survival$O3_conv,
                              seed_O = fecundity18$O3_conv)

N_3yr_conv_mature_plant_density_fixed_df <- N_3yr_conv_mature_plant_density_fixed  %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>% #corn was listed before soybean in the customized f.
  dplyr::rename(plant_counts_fixed = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 3)) %>%
   mutate(Crop_ID = c(rep("C3", 6), rep("S3", 6), rep("03", 6)))


### Output: Mature plant densities until seed production (B_h = sv_C or sv_S)
### 1 iteration only because no randomization at any matrix

rot_3year_low_plant_density_fixed <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C, seed_C,
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O){
  

  seed_C[1,3] <- rlnorm(1, 5.55, 0.48) #257.03 seeds/plant
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5) # 208.18 seeds/plant
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5) 


  seed_S[1,3] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,4] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46) #316.83 seeds/plant


 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
   
   pl_dens_corn <-  sv_C %*% em_C %*% prt_C %*% vec 

# soybean phase dynamics
  after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S  %*% after_corn 

  pl_dens_soy  <-  sv_S %*% em_S %*% prt_S  %*% after_corn 


# oat phase dynamics 
  after_oat <-  ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
  
  pl_dens_oat  <-  sv_O %*% em_O %*% prt_O  %*% after_soy 
   
  l <- list(pl_dens_corn[3:8], pl_dens_soy[3:8], pl_dens_oat[3:8])

 names(l) <- c("C3", "S3", "O3")
 
 l
}


N_3yr_low_mature_plant_density_fixed <- rot_3year_low_plant_density_fixed(vec = starting_point ,
                             poh_C = fall_tillage$C3_low,
                             ow_C = overwinter$C3_low,
                             prt_C  = spring_tillage$C3_low,
                             em_C  = emergence$C3_low,
                             sv_C = summer_survival$C3_low,
                             seed_C = fecundity18$C3_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S3_low,
                             ow_S = overwinter$S3_low,
                             prt_S  = spring_tillage$S3_low,
                             em_S  = emergence$S3_low,
                             sv_S = summer_survival$S3_low,
                             seed_S = fecundity18$S3_low,
                             
                             #oat dynamics   
                             poh_O = fall_tillage$O3_low,
                             ow_O = overwinter$O3_low,
                             prt_O  = spring_tillage$O3_low,
                             em_O  = emergence$O3_low,
                             sv_O = summer_survival$O3_low,
                             seed_O = fecundity18$O3_low)

N_3yr_low_mature_plant_density_fixed_df <- N_3yr_low_mature_plant_density_fixed  %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>% #corn was listed before soybean in the customized f.
  dplyr::rename(plant_counts_fixed = ".")  %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), 3)) %>%
   mutate(Crop_ID = c(rep("C3", 6), rep("S3", 6), rep("03", 6)))

```



```{r 3yr-seed-production-per-capita}
### CONV Output: seed production, after manipulation by cohort x crop phase x iteration

rot_3year_conv_seed_production_per_cap <- function(seed_C, seed_S, seed_O){
  

  seed_C[1,3] <- rlnorm(1, 5.55, 0.48) #257.03 seeds/plant
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5) # 208.18 seeds/plant
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5) 


  seed_S[1,3] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,4] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46) #316.83
  
  
  seed_production_count_corn <- seed_C[1, 3:8] 

  seed_production_count_soy <- seed_S[1, 3:8]  
  
  seed_production_count_oat <- seed_O[1, 3:8]

# seed at harvest
   
  l <- list(seed_production_count_corn, seed_production_count_soy, seed_production_count_oat)

  names(l) <- c("C3", "S3", "O3")
  
  l 
  
}

N_3yr_conv_seed_production_per_capita <- list() # blank data frame to save loop output 


for (i in 1:t) { 
  N_3yr_conv_seed_production_per_capita[[i]] = rot_3year_conv_seed_production_per_cap(seed_C = fecundity18$C2_conv,
                                                                                      seed_S = fecundity18$S3_conv,
                                                                                      seed_O = fecundity18$O3_conv)
}

# original per capita seed production in fecundity18$C3_conv[1,3:8], fecundity18$S3_conv[1,3:8], and fecundity18$O3_conv
N_3yr_conv_seed_production_per_capita_df <- N_3yr_conv_seed_production_per_capita  %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>% #corn was listed before soybean in the customized f.
  dplyr::rename(seed_per_capita_threshold = ".") %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), t*3)) %>% #*3 for 3 phases
   mutate(cycle_no = as.character(rep(1:t, each = 18))) %>%
   mutate(Crop_ID = rep(c(rep("C3", 6), rep("S3", 6), rep("C3", 6)), t)) %>%
  mutate(seed_per_capita_original = rep(c(fecundity18$C3_conv[1,3:8],
                                          fecundity18$S3_conv[1,3:8],
                                          fecundity18$O3_conv[1,3:8]), t))

### LOW output

rot_3year_low_seed_production_per_cap <- function(seed_C, seed_S, seed_O){
  

  seed_C[1,3] <- rlnorm(1, 5.55, 0.48) #257.03 seeds/plant
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5) # 208.18 seeds/plant
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5) 


  seed_S[1,3] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,4] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46) #316.83
  
  
  seed_production_count_corn <- seed_C[1,3:8] 

  seed_production_count_soy <- seed_S[1,3:8]  

  seed_production_count_oat <- seed_O[1, 3:8]

# seed at harvest
   
  l <- list(seed_production_count_corn, seed_production_count_soy, seed_production_count_oat)

  names(l) <- c("C3", "S3", "O3")
  
  l 
  
}

N_3yr_low_seed_production_per_capita <- list() # blank data frame to save loop output 


for (i in 1:t) { 
  N_3yr_low_seed_production_per_capita[[i]] = rot_3year_low_seed_production_per_cap(seed_C = fecundity18$C3_low,
                                                                                    seed_S = fecundity18$S3_low,
                                                                                    seed_O = fecundity18$O3_low)
}


N_3yr_low_seed_production_per_capita_df <- N_3yr_low_seed_production_per_capita  %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>% #corn was listed before soybean in the customized f.
  dplyr::rename(seed_per_capita_threshold = ".") %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), t*3)) %>% #*3 for 3 phases
   mutate(cycle_no = as.character(rep(1:t, each = 18))) %>%
   mutate(Crop_ID = rep(c(rep("C3", 6), rep("S3", 6), rep("O3", 6)), t)) %>%
  mutate(seed_per_capita_original = rep(c(fecundity18$C3_low[1,3:8],
                                          fecundity18$S3_low[1,3:8],
                                          fecundity18$O3_low[1,3:8]), t))
```


```{r 3yr-sim-a-all-output}
# total stratified seedbank density and lambdas in N_3yr_conv_df
# manipulated seed production in N_3yr_conv_seed_production_per_capita_df
# fixed mature plant density in N_3yr_conv_mature_plant_density_fixed_df 

N_3yr_conv_all_df <- N_3yr_conv_seed_production_per_capita_df %>% 
  left_join(N_3yr_conv_df, by = "cycle_no") %>%
  left_join(N_3yr_conv_mature_plant_density_fixed_df, by = c("Crop_ID", "cohort")) %>%
  mutate(seed_production_threshold = seed_per_capita_threshold*plant_counts_fixed) %>%
  mutate(seed_production_control_efficacy = 1 - seed_per_capita_threshold/seed_per_capita_original) 


N_3yr_low_all_df <- N_3yr_low_seed_production_per_capita_df %>% 
  left_join(N_3yr_low_df, by = "cycle_no") %>%
  left_join(N_3yr_low_mature_plant_density_fixed_df, by = c("Crop_ID", "cohort")) %>%
  mutate(seed_production_threshold = seed_per_capita_threshold*plant_counts_fixed) %>%
  mutate(seed_production_control_efficacy = 1 - seed_per_capita_threshold/seed_per_capita_original) 
```



```{r rot-4yr-function-a}
### conventional weed management
rot_4year_conv <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O,
                       poh_A, ow_A, prt_A, em_A, sv_A, seed_A){
  
  seed_C[1,3] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,4] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,5] <- rlnorm(1,  2.66, 0.89)
 #fecundity was much lower after cohort 3, so focus on suppressing plant size in soybean


  seed_S[1,3] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,4] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,5] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,6] <- rlnorm(1,  7.34, 0.44)

# corn phase dynamics  
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*%  vec 
 # soybean phase dynamics
   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%   after_corn
# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
# alfalfa phase dynamics
after_alfalfa <-   ow_A %*%  poh_A %*% seed_A %*% sv_A %*% em_A %*% prt_A %*% after_oat 
  after_alfalfa
}

### low herbicide weed management
rot_4year_low <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O,
                       poh_A, ow_A, prt_A, em_A, sv_A, seed_A){
  
  seed_C[1,3] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,4] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,5] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,6] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,7] <- rlnorm(1,  2.66, 0.89)
 # seed_C[1,8] <- rlnorm(1,  2.66, 0.89)


  seed_S[1,3] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,4] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,5] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,6] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,7] <- rlnorm(1,  2.66, 0.89)
 # seed_S[1,8] <- rlnorm(1,  2.66, 0.89)

# corn phase dynamics  
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*%  vec 
 # soybean phase dynamics
   after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%   after_corn
# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
# alfalfa phase dynamics
after_alfalfa <-   ow_A %*%  poh_A %*% seed_A %*% sv_A %*% em_A %*% prt_A %*% after_oat 
   
  after_alfalfa
}
```

```{r 4yr-lambda-sim-a}
##### with corn under conventional weed management {-}
N_4yr_conv <- list() # blank dataframe to save loop output 

N_4yr_conv[[1]] <- starting_point 

for (i in 2:t) { 
  N_4yr_conv[[i]] = rot_4year_conv(vec = N_4yr_conv[[i-1]],
                              poh_C = fall_tillage$C4_conv,
                              ow_C = overwinter$C4_conv,
                              prt_C  = spring_tillage$C4_conv,
                              em_C  = emergence$C4_conv,
                              sv_C = summer_survival$C4_conv,
                              seed_C = fecundity18$C4_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_conv,
                              ow_S = overwinter$S4_conv,
                              prt_S  = spring_tillage$S4_conv,
                              em_S  = emergence$S4_conv,
                              sv_S = summer_survival$S4_conv,
                              seed_S = fecundity18$S4_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_conv,
                              ow_O = overwinter$O4_conv,
                              prt_O  = spring_tillage$O4_conv,
                              em_O  = emergence$O4_conv,
                              sv_O = summer_survival$O4_conv,
                              seed_O = fecundity18$O4_conv,
                              
                              #alfalfa dynamics   
                          poh_A = fall_tillage$A4_conv,
                          ow_A = overwinter$A4_conv,
                          prt_A  = spring_tillage$A4_conv,
                          em_A  = emergence$A4_conv,
                          sv_A = summer_survival$A4_conv,
                          seed_A = fecundity18$A4_conv)
}

N_4yr_conv_df <-  N_4yr_conv %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything())  %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = total_seedbank_counts/lag(total_seedbank_counts),
         lambda_annualized = sqrt(lambda_cycle),
          Rotation = "4-year",
         Corn_weed_management = "conventional") 

##### with corn under low herbicide weed management {-} 
N_4yr_low <- list() # blank dataframe to save loop output 

N_4yr_low[[1]] <- starting_point 

for (i in 2:t) { 
  N_4yr_low[[i]] = rot_4year_low(vec = N_4yr_low[[i-1]],
                              poh_C = fall_tillage$C4_low,
                              ow_C = overwinter$C4_low,
                              prt_C  = spring_tillage$C4_low,
                              em_C  = emergence$C4_low,
                              sv_C = summer_survival$C4_low,
                              seed_C = fecundity18$C4_low,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_low,
                              ow_S = overwinter$S4_low,
                              prt_S  = spring_tillage$S4_low,
                              em_S  = emergence$S4_low,
                              sv_S = summer_survival$S4_low,
                              seed_S = fecundity18$S4_low,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_low,
                              ow_O = overwinter$O4_low,
                              prt_O  = spring_tillage$O4_low,
                              em_O  = emergence$O4_low,
                              sv_O = summer_survival$O4_low,
                              seed_O = fecundity18$O4_low,
                              
                              #alfalfa dynamics   
                              poh_A = fall_tillage$A4_low,
                              ow_A = overwinter$A4_low,
                              prt_A  = spring_tillage$A4_low,
                              em_A  = emergence$A4_low,
                              sv_A = summer_survival$A4_low,
                              seed_A = fecundity18$A4_low)
}

N_4yr_low_df <-  N_4yr_low %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(seedbank_counts = ".") %>%
  dplyr::mutate(stratum = rep(c("top", "bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(stratum %in% c("top", "bottom")) %>%
    unnest(cols = everything())  %>%
    mutate(cycle_no = as.character(rep(1:t, each = 2))) %>%
  pivot_wider(names_from = stratum, values_from = seedbank_counts) %>%
  mutate(total_seedbank_counts = top + bottom) %>%
  mutate(lambda_cycle = counts/lag(counts),
         lambda_annualized = nthroot(lambda_cycle,4),
         Rotation = "4-year",
         Corn_weed_management = "low")

```


```{r seed-allowance-sim-lambda-plot, echo=FALSE, fig.cap= "Population growth rates over 100 rotational cycles. All simulations started with a seed column of 10000 female seeds in the top 0 - 2 cm soil stratum and 0 female seed in the bottom 2 - 20 cm soil stratum. The simulation applied weed management on cohorts 1 through 3 in corn and soybean only. The relationships of aboveground mass and fecundity in Nguyen and Liebman (2022b) were used to estimate cohort-based fecundity. In corn and soybean, only the fecundity of cohorts 1 through 3 fecundity were manipulated to find the seed thresholds in the corn and soybean environments, the fecundity of cohorts 4 and beyond were kept as they were measured from 2018. Each panel was annotated with the average fecundity threshold (seeds/m2) for the first three plant cohorts and the whole crop phase. The red horizontal line marks lambda = 1.", fig.height= 8, fig.width=8}
seed_allowance_sim_df <- rbind(N_2yr_conv_df,
                                N_2yr_low_df,
                               N_3yr_conv_df,
                                N_3yr_low_df,
                               N_4yr_conv_df,
                                N_4yr_low_df)

seed_allowance_sim_df$category <- factor(seed_allowance_sim_df$category, levels = c("top", "bottom"))
 # label = c("2-year, conv: 1356 \n C2: 41 (614); S2: 41 (741)" , 
 #           "3-year, low: 10206 \n C3: 627 (889); S3: 627 (785)",
 #           "4-year, conv: 102909 \n 2187 (4821); S4: 2187 (3017)",
 #           "2-year, low: 2171 \n C2: 41 (491); S2: 41 (1680)",
 #           "3-year, conv: 444331 \n C3: 627 (1101); S3: 627 (2531)",
 #           "4-year, low: 67729 \n C4: 951 (2394); S4: 951 (2672)"),
sim_label <- data.frame(
  label = c("Seed production threshold \n C2: 1464 (1470); S2: 39843 (51594)" , 
            "Seed production threshold \n C3: 4375 (4482); S3: 1048 (1235) \n 'O3: 429",
            "Seed production threshold \n *C4: 5264 (5282); *S4: 242 (287) \n 'O4: 197; 'A4: 3059",
            "Seed production threshold \n C2: 1403 (1486); S2: 1070 (2078)",
            "Seed production threshold \n *C3: 863 (863); *S3:  675 (1279) \n 'O3: 656",
            "Seed production threshold \n *C4: 7361 (7424); *S4: 90 (99) \n 'O4: 431; 'A4: 231"),
  Rotation = rep(c("2-year", "3-year", "4-year"), 2),
  Corn_weed_management = rep(c("conventional", "low"), 3),
  category = rep("placeholder", 6)
  ) 

seed_allowance_sim_df %>%
   ggplot() +
   aes(x = cycle_no, y = lambda_annualized, group = category) +
 # geom_line(aes(y = lambda_annualized, color =  category)) +
#  geom_point(aes(y  = lambda_annualized, color =  category, alpha = 0.5)) +
  geom_point(aes(y  = lambda_annualized, shape =  category)) +
  scale_shape_manual(values = c(1, 4)) +
  scale_color_brewer(palette = "Set1") +
#  geom_hline(yintercept = 1, color = "black") +
  geom_hline(yintercept = 1, color = "red") +
  facet_grid(Rotation ~ Corn_weed_management ) + 
  ylab("Annualized population growth rate") +
  xlab("Cycle number") + 
   ylim(0.7, 2) +
  theme(legend.position = "bottom",
        legend.title = element_blank()) + 
    geom_text(data = sim_label, aes(label = label), size = 3, x = 50, y = 1.75) 
```


```{r seed-allowance-sim-N-plot, echo=FALSE, fig.cap= "Population size at the end of a rotation cycle over 100 rotational cycles (the 2-year rotation ended at the soybean phase, the 3-year rotation ended at the oat phase, and the 4-year rotation ended at the alfalfa phase). All simulations started with a seed column of 10000 female seeds in the top 0 - 2 cm soil stratum and 0 female seed in the bottom 2 - 20 cm soil stratum. The simulation applied improved weed control efficacy on cohorts 1 through 3 in corn and soybean only. The relationships of aboveground mass and fecundity in Nguyen and Liebman (2022a) were used to estimate cohort-based fecundity. It was expected that no waterhemp cohorts in any crop environments but only the cohorts 1 through 3 in corn and soybean were manipulated to find the seed production thresholds. However, additional control efficacy was needed in some crop phases outside of the expected group to reduce seed production potentials. The crop phases marked with an asterisk (*) are where control measures extended beyond waterhemp cohort 3 would be neccessary. The crop phases marked with an inverted comma (') are where no additional control was applied. Each panel was annotated with the average fecundity thresholds for the first three waterhemp cohorts in corn and soybean followed by the whole crop phase.  The red horizontal line marks lambda = 1.", fig.height = 6, fig.width = 6}

seed_allowance_sim_df %>%
   ggplot() +
   aes(x = cycle_no, y = log(counts), group = category) +
 # geom_line(aes(y = lambda_annualized, color =  category)) +
#  geom_point(aes(y  = lambda_annualized, color =  category, alpha = 0.5)) +
  geom_point(aes(y  = log(counts), shape =  category)) +
  scale_shape_manual(values = c(1, 4)) +
  geom_hline(yintercept = log(10000), color = "red") +
  facet_grid(Rotation ~ Corn_weed_management) + 
  ylab(expression(paste("ln(Seed density (seeds",~m^-2,"))"))) +
  xlab("Simulation iteration") + 
  ylim(0, 15) +
  theme_bw() +
  guides(shape=guide_legend(title = "soil stratum")) +
  theme(legend.position = "top") + 
    geom_text(data = sim_label, aes(label = label), size = 2.5, x = 50, y = 12.5) 
```



```{r seed-allowance-sim-N-plot-no-ann, echo=FALSE, fig.cap= "Population size at the end of a rotation cycle over 100 rotational cycles (the 2-year rotation ended at the soybean phase, the 3-year rotation ended at the oat phase, and the 4-year rotation ended at the alfalfa phase). All simulations started with a seed column of 10000 female seeds in the top 0 - 2 cm soil stratum and 0 female seed in the bottom 2 - 20 cm soil stratum. The simulation applied improved weed control efficacy on cohorts 1 through 3 in corn and soybean only. The relationships of aboveground mass and fecundity in Nguyen and Liebman (2022a) were used to estimate cohort-based fecundity. It was expected that no waterhemp cohorts in any crop environments but only the cohorts 1 through 3 in corn and soybean were manipulated to find the seed production thresholds. However, additional control efficacy was needed in some crop phases outside of the expected group to reduce seed production potentials. The red horizontal line marks lambda = 1.", fig.height = 6, fig.width = 6}

seed_allowance_sim_df %>%
   ggplot() +
   aes(x = cycle_no, y = log(counts), group = category) +
 # geom_line(aes(y = lambda_annualized, color =  category)) +
#  geom_point(aes(y  = lambda_annualized, color =  category, alpha = 0.5)) +
  geom_point(aes(y  = log(counts), shape =  category)) +
  scale_shape_manual(values = c(1, 4)) +
  geom_hline(yintercept = log(10000), color = "red") +
  facet_grid(Rotation ~ Corn_weed_management) + 
  ylab(expression(paste("ln(Seed density (seeds",~m^-2,"))"))) +
  xlab("Simulation iteration") + 
  ylim(0, 15) +
  theme_bw() +
  guides(shape=guide_legend(title = "soil stratum")) +
  theme(legend.position = "top") 
```


 
```{r seed-production-threshold-sim-plot-manipulated}
#gather all corn and soybean

N_2yr_conv_all_df %>% 
  na.omit() %>%
     ggplot() +
   aes(x = seed_production, y = lambda_annualized, group = stratum) +
   facet_grid(Crop_ID ~ cohort , scales = "free") +
    geom_hline(yintercept = 1, color = "red") +
 # geom_line(aes(y = lambda_annualized, color =  category)) +
#  geom_point(aes(y  = lambda_annualized, color =  category, alpha = 0.5)) +
  geom_point(aes(y  = lambda_annualized, shape = stratum))
#  scale_shape_manual(values = c(1, 6))


#gather oat and alfalfa
```

```{r}
head(seed_allowance_sim_df) %>%
  flextable::flextable()
```
