---
title: "Q1 seed production allowance rotation draft"

output: html_document
---

2 - How long does it take for a population with 5% herbicide resistant seeds to reach total resistance?

##### Weed control efficacy {-}  
##### Time to total resistance {-}  


```{r gather-sim}
## gather all simulations to make a faceted plot ()

# calculate n[i+1]/n[i] for top and bottom seeds https://stackoverflow.com/questions/64027021/dividing-each-row-by-the-previous-one-in-r
N_df <- N %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(counts = ".") %>%
  dplyr::mutate(category = rep(c("seed_top", "seed_bottom", "cohort_1", "cohort_2", "cohort_3", "cohort_4", "cohort_5", "cohort_6"),t)) %>%
    filter(category %in% c("seed_top", "seed_bottom")) %>%
 # dplyr::select(!rowname) %>%
 # tidyr::pivot_wider(names_from = category,
#                    values_from = no_,
#                     values_fn = list) %>% 
    unnest(cols = everything() ) %>%
    mutate(cycle_no = rep(1:t, each = 2)) %>%
  group_by(category) %>%
  mutate(lambda_cycle = counts/lag(counts),
         lambda_annualized = sqrt(lambda_cycle)) %>%
    na.omit()

  

N_df %>%
  ggplot() +
   aes(x = cycle_no, y = lambda_annualized, group = category) +
  geom_line(aes(y = lambda_annualized, linetype =  category)) +
  geom_point(aes(y  = lambda_annualized, shape =  category)) +
  geom_hline(yintercept = 1, color = "red")  +
 xlim(1000, 1200)
```



#### at t = 1: 1000 seeds, from t = 2: rlnorm(1, 5.65, 0.95)

```{r corn2}
# to test mechanism
# event sequence: seed dropped - chisel - overwinter - field cultivator - emerge - survive - new seed

# create a function 
# em, sv, fe

corn2 <- function(vec, poh, ow, prt, em, sv){
   early_summer_sb <- prt %*%  ow %*%  poh %*% vec # post-harvest through pre-planting

   mature_plant_total <-  early_summer_sb[1]*em[3,1]*sv[[3,3]] + 
     early_summer_sb[1]*em[4,1]*sv[[4,4]] +
     early_summer_sb[1]*em[5,1]*sv[[5,5]] +
     early_summer_sb[1]*em[6,1]*sv[[6,6]] + 
     early_summer_sb[1]*em[7,1]*sv[[7,7]] + 
     early_summer_sb[1]*em[8,1]*sv[[8,8]]   # emerge through maturity 
   
    new_seeds_total <-  mature_plant_total * rlnorm(1, 5.65, 0.95) #whole-population annual fecundity
  
    summer_till_harvest_sb <- em[1:2,1:2] %*% early_summer_sb  # dormant seeds dynamics until new seeds
    
    post_harvest_sb <- c(new_seeds_total+summer_till_harvest_sb[1], summer_till_harvest_sb[2]) #add the newly produced seeds to the top layer seed only; vertical redistribution start again at the next time step.
   
   c(0, post_harvest_sb) # emerged not subtracted yet 
}
```


```{r c2-conv-sim2}

M <- list() # blank dataframe to save loop output 
## Calculate M0
M0 <- corn2(vec = starting_point[2:3], 
   poh = chisel, 
   ow = overwinter,
   prt = field_cultivator,
   em = emergence[["C2_conv"]],
   sv = summer_survival[["C2_conv"]])

 M[[1]] <- M0


#loop over the "corn" function for C2-conv for "t" times 

for (i in 2:t) { 
    M[[i]] = corn2(vec = M[[i-1]][2:3],
                  poh = chisel, 
                  ow = overwinter,
                  prt = notill,
                  em = emergence[["C2_conv"]],
                  sv = summer_survival[["C2_conv"]])
}
 
M_df <- M %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(no_ = ".") %>%
  dplyr::mutate(category = rep(c("plant", "seed_top", "seed_bottom"),t)) %>%
    filter(category != "plant") %>%
 # dplyr::select(!rowname) %>%
  tidyr::pivot_wider(names_from = category,
                     values_from = no_,
                     values_fn = list) %>% 
    unnest(cols = everything() ) %>%
    mutate(time_step = seq(1:t)) %>%
  pivot_longer(!time_step, names_to = "stratum", values_to = "no_")
  

```

```{r sim2-plot}
M_df %>%
  ggplot() +
   aes(x = time_step, y = no_, group = stratum) +
  geom_line(aes(y =  no_, linetype =  stratum)) +
  geom_point(aes(y  = no_, shape =  stratum)) +
  xlim(0, 50)
```

#### at t = 1: 1000 seeds, from t = 2: rlnorm(1, 6.7, 3.05)

```{r corn3}
# to test mechanism
# event sequence: seed dropped - chisel - overwinter - field cultivator - emerge - survive - new seed

# create a function 
# em, sv, fe

corn3 <- function(vec, poh, ow, prt, em, sv){
   early_summer_sb <- prt %*%  ow %*%  poh %*% vec # post-harvest through pre-planting

   mature_plant_total <-  early_summer_sb[1]*em[3,1]*sv[[3,3]] + 
     early_summer_sb[1]*em[4,1]*sv[[4,4]] +
     early_summer_sb[1]*em[5,1]*sv[[5,5]] +
     early_summer_sb[1]*em[6,1]*sv[[6,6]] + 
     early_summer_sb[1]*em[7,1]*sv[[7,7]] + 
     early_summer_sb[1]*em[8,1]*sv[[8,8]]   # emerge through maturity 
   
    new_seeds_total <-  mature_plant_total *  rlnorm(1, 6.7, 3.05)
  
    summer_till_harvest_sb <- em[1:2,1:2] %*% early_summer_sb  # dormant seeds dynamics until new seeds
    
    post_harvest_sb <- c(new_seeds_total+summer_till_harvest_sb[1], summer_till_harvest_sb[2])
   
   c(0, post_harvest_sb) # emerged not subtracted yet 
}
```


```{r c2-conv-sim3}
P <- list() # blank dataframe to save loop output 
  ## Calculate P0
P0 <- corn3(vec = starting_point[2:3], 
   poh = chisel, 
   ow = overwinter,
   prt = field_cultivator,
   em = emergence[["C2_conv"]],
   sv = summer_survival[["C2_conv"]])

P[[1]] <- P0


#loop over the "corn" function for C2-conv for "t" times 

for (i in 2:t) { 
    P[[i]] = corn3(vec = P[[i-1]][2:3],
                  poh = chisel, 
                  ow = overwinter,
                  prt = field_cultivator,
                  em = emergence[["C2_conv"]],
                  sv = summer_survival[["C2_conv"]])
}
 
P_df <- M %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(no_ = ".") %>%
  dplyr::mutate(category = rep(c("plant", "seed_top", "seed_bottom"),t)) %>%
    filter(category != "plant") %>%
 # dplyr::select(!rowname) %>%
  tidyr::pivot_wider(names_from = category,
                     values_from = no_,
                     values_fn = list) %>% 
    unnest(cols = everything() ) %>%
    mutate(time_step = seq(1:t)) %>%
  pivot_longer(!time_step, names_to = "stratum", values_to = "no_")
  

```

```{r sim3-plot}
P_df %>%
  ggplot() +
   aes(x = time_step, y = no_, group = stratum) +
  geom_line(aes(y =  no_, linetype =  stratum)) +
  geom_point(aes(y  = no_, shape =  stratum)) 

```

#### at t = 1: 1000 seeds, from t = 2: rlnorm(1, 6.2, 0.86)

```{r corn4}
# to test mechanism
# event sequence: seed dropped - chisel - overwinter - field cultivator - emerge - survive - new seed

# create a function 
# em, sv, fe

corn4 <- function(vec, poh, ow, prt, em, sv){
   early_summer_sb <- prt %*%  ow %*%  poh %*% vec # post-harvest through pre-planting

   mature_plant_total <-  early_summer_sb[1]*em[3,1]*sv[[3,3]] + 
     early_summer_sb[1]*em[4,1]*sv[[4,4]] +
     early_summer_sb[1]*em[5,1]*sv[[5,5]] +
     early_summer_sb[1]*em[6,1]*sv[[6,6]] + 
     early_summer_sb[1]*em[7,1]*sv[[7,7]] + 
     early_summer_sb[1]*em[8,1]*sv[[8,8]]   # emerge through maturity 
   
    new_seeds_total <-  mature_plant_total *  rlnorm(1, 6.75, 0.86)
  
    summer_till_harvest_sb <- em[1:2,1:2] %*% early_summer_sb  # dormant seeds dynamics until new seeds
    
    post_harvest_sb <- c(new_seeds_total+summer_till_harvest_sb[1], summer_till_harvest_sb[2])
   
   c(0, post_harvest_sb) # emerged not subtracted yet 
}
```


```{r c2-conv-sim4}

Q <- list() # blank dataframe to save loop output 
  ## Calculate P0
Q0 <- corn4(vec = starting_point[2:3], 
   poh = chisel, 
   ow = overwinter,
   prt = field_cultivator,
   em = emergence[["C2_conv"]],
   sv = summer_survival[["C2_conv"]])

Q[[1]] <- Q0


#loop over the "corn" function for C2-conv for "t" times 

for (i in 2:t) { 
    Q[[i]] = corn4(vec = Q[[i-1]][2:3],
                  poh = chisel, 
                  ow = overwinter,
                  prt = field_cultivator,
                  em = emergence[["C2_conv"]],
                  sv = summer_survival[["C2_conv"]])
}
 
Q_df <- Q %>% 
  unlist(recursive = FALSE) %>%
  data.frame() %>%
    dplyr::rename(no_ = ".") %>%
  dplyr::mutate(category = rep(c("plant", "seed_top", "seed_bottom"),t)) %>%
    filter(category != "plant") %>%
 # dplyr::select(!rowname) %>%
  tidyr::pivot_wider(names_from = category,
                     values_from = no_,
                     values_fn = list) %>% 
    unnest(cols = everything() ) %>%
    mutate(time_step = seq(1:t)) %>%
  pivot_longer(!time_step, names_to = "stratum", values_to = "no_")
  

```

```{r sim4-plot}
Q_df %>%
  ggplot() +
   aes(x = time_step, y = log(no_), group = stratum) +
  geom_line(aes(y =  log(no_), linetype =  stratum)) +
  geom_point(aes(y  = log(no_), shape =  stratum)) 


```