---
output:
 # bookdown::word_document2:
  bookdown::html_document2:
      toc: false
      fig_caption: yes
      keep_md: true
bibliography: WH-pop-dynamics.bib
csl: apa-no-ampersand.csl 
---
Goal: output the total seed production in each crop phase, for all 100 simulations.  

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(readr)
library(magrittr) # for %<>%
library(nlme) # for gls
library(emmeans) # for joint_tests
library(patchwork)
library(pracma) #for nthroot
set.seed(722)
```


```{r, echo=FALSE}
starting_point <-  c(10000, 0, 0, 0, 0, 0, 0, 0) #10000 seeds top soil, 0 seed deep soil,0 plants from cohorts 1 through 6
```

```{r tillage-sim, echo=FALSE}
fall_tillage <-readRDS("../2-Data/Clean/mean-post-harvest-tillage.RData")

spring_tillage <-readRDS("../2-Data/Clean/mean-pre-planting-tillage.RData")
```



```{r overwinter-sim, echo=FALSE}
overwinter <- readRDS("../2-Data/Clean/mean-winter-seed-survival-Sosnoskie.RData")
```



```{r emerge-sim, echo=FALSE}
emergence <-readRDS("../2-Data/Clean/mean-emergence-prop.RData")
```



```{r survive-sim, echo=FALSE}
summer_seed_survival <- readRDS("../2-Data/Clean/mean-summer-seed-survival-Sosnoskie.RData")

#### plant survival: literature data - named as scenario2, because scenario1 is the point-estimates from the experiment 
#female_survival <- readRDS("../2-Data/Clean/female-survival-rate-cohort-equal.RData")

female_survival <- readRDS("../2-Data/Clean/mean-summer-seedling-survival-Hartzler.RData")

#### combine seed and plant survivals into one matrix with element-wise multiplication: this is not computing, but arranging using 1's as placeholders 
summer_survival <- purrr::map2(summer_seed_survival, female_survival, `*`)
```



```{r fecund-sim, echo=FALSE}
# First step: use a cumulative fecundity of all cohorts as `
#new_seeds_total`=  mature_plant_total * fecundity_sim
# change fecundity_sim  to get lambda as close to 1 as possible 

# Focus next: manipulate cohorts 1 and 2 in corn and soybean fecundity only because 1) these cohorts are more likely exposed to control measures and 2) they have higher survival rates than cohorts 3+ 

# cohort 3+ fecundity: estimated fecundity as in population projection 

# Final goal: flatten the fecundity distribution curve in corn and soybean to see seed production "allowance" in cohorts 1 and 2

### find good pairs of mean and sd for rlnorm in Q1-fecund-prep

fecundity18 <- readRDS("../2-Data/Clean/mean-fecundity-18-cohort.RData")
```



```{r rot-2yr-function, echo=TRUE}
# event sequence: seed dropped - chisel - overwinter - field cultivator - emerge - survive - new seed

# create a function 
# vec: starting seed column
# poh: post-harvest tillage
# ow: over winter seed survival
# prt: pre-planting-tillage
# em: emergence
# sv: seed survival rate and seedling to maturity success rate
# seed: fecundity

rot_2year_conv_seed_threshold_count <- function(seed_C, seed_S){
  

  seed_C[1,3] <- rlnorm(1, 5.55, 0.48) #257.03 seeds/plant
  seed_C[1,4] <- rlnorm(1, 5.34, 0.5) # 208.18 seeds/plant
  seed_C[1,5] <- rlnorm(1, 5.34, 0.5) 


  seed_S[1,3] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,4] <- rlnorm(1, 5.55, 0.48) 
  seed_S[1,5] <- rlnorm(1, 5.75, 0.46) #316.83
  
  
  seed_threshold_count_corn <- seed_C[1,3:8] 

  seed_threshold_count_soy <- seed_S[1,3:8]  

# seed at harvest
   
  l <- list(seed_threshold_count_corn, seed_threshold_count_soy)

  names(l) <- c("corn", "soybean")
  
  l 
  
}

rot_2year_low <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C, seed_C,
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S){
  

  seed_C[1,3] <- rlnorm(1, 3.85, 0.7) # 46.55 seeds/plant
  seed_C[1,4] <- rlnorm(1, 3.44, 0.76) # 30.84 seeds/plant
  seed_C[1,5] <- rlnorm(1, 3.85, 0.7)

  seed_S[1,3] <- rlnorm(1, 3.85, 0.7)
  seed_S[1,4] <- rlnorm(1, 3.85, 0.7)
  seed_S[1,5] <- rlnorm(1, 4.22, 0.65) #67.56 seeds/plant

 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
   
   pl_dens_corn <-  sv_C %*% em_C %*% prt_C %*% vec 
   seed_dens_corn <- seed_C[1,3:8] * pl_dens_corn[3:8]
# soybean phase dynamics

  pl_dens_soy  <-  sv_S %*% em_S %*% prt_S  %*% after_corn 
   
   seed_dens_soy <- seed_S[1,3:8] * pl_dens_soy[3:8] 

# seed at harvest
   list(seed_dens_corn, seed_dens_soy)
# l <-  list(pl_dens_corn[3:8], pl_dens_soy[3:8], 
#             sum(seed_dens_corn[1:3]), sum(seed_dens_corn),
#            sum(seed_dens_soy[1:3]), sum(seed_dens_soy),
#            sum(seed_dens_corn, seed_dens_soy))
# names(l) <- c("plant density in corn", "plant density in soybean",
#               "corn_first3", "corn_total",
#               "soybean_first3", "soybean_total", "rotation_total")
# l
}
```

```{r 2yr-conv-sim1-seed-production-threshold, echo = TRUE}
##### with corn under conventional weed management {-}
t <- 100
N_2yr_conv_seed_production <- list() # blank data frame to save loop output 


for (i in 1:t) { 
  N_2yr_conv_seed_production[[i]] = rot_2year_conv(seed_C = fecundity18$C2_conv,
                seed_S = fecundity18$S2_conv)
}

N_2yr_conv_seed_production  %>% 
  unlist(recursive = TRUE) %>% # make a long table
  data.frame() %>% #corn was listed before soybean in the customized f.
  dplyr::rename(counts = ".") %>%
  dplyr::mutate(cohort = rep(c("1", "2", "3", "4", "5", "6"), t*2)) %>%
   mutate(cycle_no = as.character(rep(1:t, each = 12))) %>%
   mutate(phase = rep(c(rep("corn", 6), rep("soybean", 6)), t))
```


 

 
```{r 2yr-low-sim1, echo=TRUE}
##### with corn under low herbicide weed management {-}
rot_2year_low(vec = starting_point ,
                             poh_C = fall_tillage$C2_low,
                             ow_C = overwinter$C2_low,
                             prt_C  = spring_tillage$C2_low,
                             em_C  = emergence$C2_low,
                             sv_C = summer_survival$C2_low,
                             seed_C = fecundity18$C2_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S2_low,
                             ow_S = overwinter$S2_low,
                             prt_S  = spring_tillage$S2_low,
                             em_S  = emergence$S2_low,
                             sv_S = summer_survival$S2_low,
                             seed_S = fecundity18$S2_low)

```
  


```{r rot-3yr-function, echo=TRUE}
rot_3year_conv <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O){
  

  seed_C[1,3] <- rlnorm(1, 2.66, 0.89)
  seed_C[1,4] <- rlnorm(1, 2.66, 0.89)
  seed_C[1,5] <- rlnorm(1, 2.66, 0.89)
  seed_C[1,6] <- rlnorm(1, 2.66, 0.89)
  seed_C[1,7] <- rlnorm(1, 2.66, 0.89)
 # seed_C[1,8] <- rlnorm(1, 2.66, 0.89)

  seed_S[1,3] <- rlnorm(1, 2.66, 0.89)
  seed_S[1,4] <- rlnorm(1, 2.66, 0.89)
  seed_S[1,5] <- rlnorm(1, 2.66, 0.89)
  seed_S[1,6] <- rlnorm(1, 2.66, 0.89)
  seed_S[1,7] <- rlnorm(1, 2.66, 0.89)
 # seed_S[1,8] <- rlnorm(1, 2.66, 0.89)

 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
   
   pl_dens_corn <-  sv_C %*% em_C %*% prt_C %*% vec 
   seed_dens_corn <- seed_C[1,3:8] * pl_dens_corn[3:8]
# soybean phase dynamics
after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%  after_corn

  pl_dens_soy <-  sv_S %*% em_S %*% prt_S  %*% after_corn 
   
   seed_dens_soy <- seed_S[1,3:8] * pl_dens_soy[3:8] 

# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
   
  pl_dens_oat <-  sv_O %*% em_O %*% prt_O %*% after_soy 
   
   seed_dens_oat <- seed_O[1,3:8] * pl_dens_oat[3:8] 
   
   # seed at harvest
   
  list(seed_dens_corn, seed_dens_soy, seed_dens_oat) 
#  l <-  list( pl_dens_corn[3:8],  pl_dens_soy[3:8], pl_dens_oat[3:8],
#             sum(seed_dens_corn[1:3]), seed_dens_corn[4], seed_dens_corn[5], sum(seed_dens_corn),
#             sum(seed_dens_soy[1:3]), seed_dens_soy[4], seed_dens_soy[5], sum(seed_dens_soy),
#             sum(seed_dens_oat), 
#             sum(seed_dens_corn, seed_dens_soy, seed_dens_oat))
# names(l) <- c("plant density in corn", "plant density in soybean", "plant density in oat", 
#               "corn_first3", "corn_4", "corn_5", "corn_total",
#               "soybean_first3", "soybean_4", "soybean_5" ,"soybean_total", 
#               "oat_total", "rotation_total")
# l
}

### low herbicide weed management
## Manipulation note: if cohorts 1 through 3 were reduced to rlnorm(1, 2.65, 0.89), alphas are around 0.5 --> super "safe", but hard
## cohorts 1 through 3 at rlnorm(1, 5.2, 0.51): more realistic
rot_3year_low <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O){
  


  seed_C[1,3] <- rlnorm(1, 2.66, 0.89)
  seed_C[1,4] <- rlnorm(1, 2.66, 0.89)
  seed_C[1,5] <- rlnorm(1, 5.05, 0.53)


  seed_S[1,3] <- rlnorm(1, 2.66, 0.89)
  seed_S[1,4] <- rlnorm(1, 2.66, 0.89)
  seed_S[1,5] <- rlnorm(1, 6.94, 0.43)

 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
   
   pl_dens_corn <-  sv_C %*% em_C %*% prt_C %*% vec 
   seed_dens_corn <- seed_C[1,3:8] * pl_dens_corn[3:8]
# soybean phase dynamics
after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%  after_corn

  pl_dens_soy <-  sv_S %*% em_S %*% prt_S  %*% after_corn 
   
   seed_dens_soy <- seed_S[1,3:8] * pl_dens_soy[3:8] 

# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
   
  pl_dens_oat <-  sv_O %*% em_O %*% prt_O %*% after_soy 
   
   seed_dens_oat <- seed_O[1,3:8] * pl_dens_oat[3:8] 
   
   # seed at harvest
  list(seed_dens_corn, seed_dens_soy, seed_dens_oat) 
#  l <-  list( pl_dens_corn[3:8],  pl_dens_soy[3:8], pl_dens_oat[3:8],
#             sum(seed_dens_corn[1:3]), seed_dens_corn[4], seed_dens_corn[5], sum(seed_dens_corn),
#             sum(seed_dens_soy[1:3]), seed_dens_soy[4], seed_dens_soy[5], sum(seed_dens_soy),
#             sum(seed_dens_oat), 
#             sum(seed_dens_corn, seed_dens_soy, seed_dens_oat))
# names(l) <- c("plant density in corn", "plant density in soybean", "plant density in oat", 
#               "corn_first3", "corn_4", "corn_5", "corn_total",
#               "soybean_first3", "soybean_4", "soybean_5" ,"soybean_total", 
#               "oat_total", "rotation_total")
# l
}
```

```{r 3yr-conv-sim1, echo=TRUE}
rot_3year_conv(vec = starting_point,
                              poh_C = fall_tillage$C3_conv,
                              ow_C = overwinter$C3_conv,
                              prt_C  = spring_tillage$C3_conv,
                              em_C  = emergence$C3_conv,
                              sv_C = summer_survival$C3_conv,
                              seed_C = fecundity18$C3_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S3_conv,
                              ow_S = overwinter$S3_conv,
                              prt_S  = spring_tillage$S3_conv,
                              em_S  = emergence$S3_conv,
                              sv_S = summer_survival$S3_conv,
                              seed_S = fecundity18$S3_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O3_conv,
                              ow_O = overwinter$O3_conv,
                              prt_O  = spring_tillage$O3_conv,
                              em_O  = emergence$O3_conv,
                              sv_O = summer_survival$O3_conv,
                              seed_O = fecundity18$O3_conv)

```
 

```{r 3yr-low-sim1, echo=TRUE}
##### with corn under low herbicide weed management {-} 
 rot_3year_low(vec = starting_point,
                             poh_C = fall_tillage$C3_conv,
                             ow_C = overwinter$C3_low,
                             prt_C  = spring_tillage$C3_low,
                             em_C  = emergence$C3_low,
                             sv_C = summer_survival$C3_low,
                             seed_C = fecundity18$C3_low,
                             
                             #soybean dynamics   
                             poh_S = fall_tillage$S3_low,
                             ow_S = overwinter$S3_low,
                             prt_S  = spring_tillage$S3_low,
                             em_S  = emergence$S3_low,
                             sv_S = summer_survival$S3_low,
                             seed_S = fecundity18$S3_low,
                             
                             #oat dynamics   
                             poh_O = fall_tillage$O3_low,
                             ow_O = overwinter$O3_low,
                             prt_O  = spring_tillage$O3_low,
                             em_O  = emergence$O3_low,
                             sv_O = summer_survival$O3_low,
                             seed_O = fecundity18$O3_low)

```




```{r rot-4yr-function, echo=TRUE}
### conventional weed management
rot_4year_conv <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O,
                       poh_A, ow_A, prt_A, em_A, sv_A, seed_A){
  
  seed_C[1,3] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,4] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,5] <- rlnorm(1,  2.66, 0.89)
 #fecundity was much lower after cohort 3, so focus on supressing plant size in soybean


  seed_S[1,3] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,4] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,5] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,6] <- rlnorm(1,  7.34, 0.44)
  
 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
   
   pl_dens_corn <-  sv_C %*% em_C %*% prt_C %*% vec 
   seed_dens_corn <- seed_C[1,3:8] * pl_dens_corn[3:8]
# soybean phase dynamics
after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%  after_corn

  pl_dens_soy <-  sv_S %*% em_S %*% prt_S  %*% after_corn 
   
   seed_dens_soy <- seed_S[1,3:8] * pl_dens_soy[3:8] 

# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
   
  pl_dens_oat <-  sv_O %*% em_O %*% prt_O %*% after_soy 
   
   seed_dens_oat <- seed_O[1,3:8] * pl_dens_oat[3:8] 
# alfalfa phase dynamics
after_alfalfa <-   ow_A %*%  poh_A %*% seed_A %*% sv_A %*% em_A %*% prt_A %*% after_oat 

  pl_dens_alfalfa <-  sv_A %*% em_A %*% prt_A %*% after_oat 
   
   seed_dens_alfalfa <- seed_A[1,3:8] * pl_dens_alfalfa[3:8] 
      # seed at harvest
   list(seed_dens_corn, seed_dens_soy, seed_dens_oat, seed_dens_alfalfa)
   
#  l <-  list( pl_dens_corn[3:8], pl_dens_soy[3:8], pl_dens_oat[3:8], pl_dens_alfalfa[3:8],
#             sum(seed_dens_corn[1:3]), seed_dens_corn[4], sum(seed_dens_corn),
#             sum(seed_dens_soy[1:3]), seed_dens_soy[4], sum(seed_dens_soy),
#             sum(seed_dens_oat), sum(seed_dens_alfalfa),
#             sum(seed_dens_corn, seed_dens_soy, seed_dens_oat, seed_dens_alfalfa))
             
# names(l) <- c("plant density in corn", "plant density in soybean", "plant density in oat", "plant density in alfalfa",
#   "corn_first3", "corn_4", "corn_total",
#               "soybean_first3", "soybean_4",  "soybean_total", 
#                "oat_total", "alfalfa_total",
#               "rotation_total")
# l

}

### low herbicide weed management
rot_4year_low <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C,  seed_C, 
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S ,
                           poh_O, ow_O, prt_O, em_O, sv_O, seed_O,
                       poh_A, ow_A, prt_A, em_A, sv_A, seed_A){
  
  seed_C[1,3] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,4] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,5] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,6] <- rlnorm(1,  2.66, 0.89)
  seed_C[1,7] <- rlnorm(1,  2.66, 0.89)
 # seed_C[1,8] <- rlnorm(1,  2.66, 0.89)


  seed_S[1,3] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,4] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,5] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,6] <- rlnorm(1,  2.66, 0.89)
  seed_S[1,7] <- rlnorm(1,  2.66, 0.89)
 # seed_S[1,8] <- rlnorm(1,  2.66, 0.89)

 # corn phase dynamics   
   after_corn <- ow_C %*%  poh_C %*% seed_C %*% sv_C %*% em_C %*% prt_C %*% vec 
   
   pl_dens_corn <-  sv_C %*% em_C %*% prt_C %*% vec 
   seed_dens_corn <- seed_C[1,3:8] * pl_dens_corn[3:8]
# soybean phase dynamics
after_soy <- ow_S %*%  poh_S %*% seed_S %*% sv_S %*% em_S %*% prt_S %*%  after_corn

  pl_dens_soy <-  sv_S %*% em_S %*% prt_S  %*% after_corn 
   
   seed_dens_soy <- seed_S[1,3:8] * pl_dens_soy[3:8] 

# oat phase dynamics
   after_oat <-   ow_O %*%  poh_O %*% seed_O %*% sv_O %*% em_O %*% prt_O %*% after_soy 
   
  pl_dens_oat <-  sv_O %*% em_O %*% prt_O %*% after_soy 
   
   seed_dens_oat <- seed_O[1,3:8] * pl_dens_oat[3:8] 
# alfalfa phase dynamics
after_alfalfa <-   ow_A %*%  poh_A %*% seed_A %*% sv_A %*% em_A %*% prt_A %*% after_oat 

  pl_dens_alfalfa <-  sv_A %*% em_A %*% prt_A %*% after_oat 
   
   seed_dens_alfalfa <- seed_A[1,3:8] * pl_dens_alfalfa[3:8] 
      # seed at harvest
   list(seed_dens_corn, seed_dens_soy, seed_dens_oat, seed_dens_alfalfa)
   
#  l <-  list( pl_dens_corn[3:8], pl_dens_soy[3:8], pl_dens_oat[3:8], pl_dens_alfalfa[3:8],
#             sum(seed_dens_corn[1:3]), seed_dens_corn[4], sum(seed_dens_corn),
#             sum(seed_dens_soy[1:3]), seed_dens_soy[4], sum(seed_dens_soy),
#             sum(seed_dens_oat), sum(seed_dens_alfalfa),
#             sum(seed_dens_corn, seed_dens_soy, seed_dens_oat, seed_dens_alfalfa))
             
# names(l) <- c("plant density in corn", "plant density in soybean", "plant density in oat", "plant density in alfalfa",
#   "corn_first3", "corn_4", "corn_total",
#               "soybean_first3", "soybean_4",  "soybean_total", 
#                "oat_total", "alfalfa_total",
#               "rotation_total")
# l
}
```

```{r 4yr-conv-sim1, echo=TRUE}
##### with corn under conventional weed management {-}
 rot_4year_conv(vec = starting_point,
                              poh_C = fall_tillage$C4_conv,
                              ow_C = overwinter$C4_conv,
                              prt_C  = spring_tillage$C4_conv,
                              em_C  = emergence$C4_conv,
                              sv_C = summer_survival$C4_conv,
                              seed_C = fecundity18$C4_conv,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_conv,
                              ow_S = overwinter$S4_conv,
                              prt_S  = spring_tillage$S4_conv,
                              em_S  = emergence$S4_conv,
                              sv_S = summer_survival$S4_conv,
                              seed_S = fecundity18$S4_conv,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_conv,
                              ow_O = overwinter$O4_conv,
                              prt_O  = spring_tillage$O4_conv,
                              em_O  = emergence$O4_conv,
                              sv_O = summer_survival$O4_conv,
                              seed_O = fecundity18$O4_conv,
                              
                              #alfalfa dynamics   
                          poh_A = fall_tillage$A4_conv,
                          ow_A = overwinter$A4_conv,
                          prt_A  = spring_tillage$A4_conv,
                          em_A  = emergence$A4_conv,
                          sv_A = summer_survival$A4_conv,
                          seed_A = fecundity18$A4_conv)


```
 

```{r 4yr-low-sim1, echo=TRUE}
##### with corn under low herbicide weed management {-} 
rot_4year_low(vec = starting_point,
                              poh_C = fall_tillage$C4_low,
                              ow_C = overwinter$C4_low,
                              prt_C  = spring_tillage$C4_low,
                              em_C  = emergence$C4_low,
                              sv_C = summer_survival$C4_low,
                              seed_C = fecundity18$C4_low,
                              
                              #soybean dynamics   
                              poh_S = fall_tillage$S4_low,
                              ow_S = overwinter$S4_low,
                              prt_S  = spring_tillage$S4_low,
                              em_S  = emergence$S4_low,
                              sv_S = summer_survival$S4_low,
                              seed_S = fecundity18$S4_low,
                              
                              #oat dynamics   
                              poh_O = fall_tillage$O4_low,
                              ow_O = overwinter$O4_low,
                              prt_O  = spring_tillage$O4_low,
                              em_O  = emergence$O4_low,
                              sv_O = summer_survival$O4_low,
                              seed_O = fecundity18$O4_low,
                              
                              #alfalfa dynamics   
                              poh_A = fall_tillage$A4_low,
                              ow_A = overwinter$A4_low,
                              prt_A  = spring_tillage$A4_low,
                              em_A  = emergence$A4_low,
                              sv_A = summer_survival$A4_low,
                              seed_A = fecundity18$A4_low)

```


## old graphs 

```{r seed-allowance-sim-lambda-plot, echo=FALSE, fig.cap= "Population growth rates over 100 rotational cycles. All simulations started with a seed column of 10000 female seeds in the top 0 - 2 cm soil stratum and 0 female seed in the bottom 2 - 20 cm soil stratum. The simulation applied weed management on cohorts 1 through 3 in corn and soybean only. The relationships of aboveground mass and fecundity in Nguyen and Liebman (2022b) were used to estimate cohort-based fecundity. In corn and soybean, only the fecundity of cohorts 1 through 3 fecundity were manipulated to find the seed thresholds in the corn and soybean environments, the fecundity of cohorts 4 and beyond were kept as they were measured from 2018. Each panel was annotated with the average fecundity threshold (seeds/m2) for the first three plant cohorts and the whole crop phase. The red horizontal line marks lambda = 1.", fig.height= 8, fig.width=8}


 # label = c("2-year, conv: 1356 \n C2: 41 (614); S2: 41 (741)" , 
 #           "3-year, low: 10206 \n C3: 627 (889); S3: 627 (785)",
 #           "4-year, conv: 102909 \n 2187 (4821); S4: 2187 (3017)",
 #           "2-year, low: 2171 \n C2: 41 (491); S2: 41 (1680)",
 #           "3-year, conv: 444331 \n C3: 627 (1101); S3: 627 (2531)",
 #           "4-year, low: 67729 \n C4: 951 (2394); S4: 951 (2672)"),
sim_label <- data.frame(
  label = c("Seed production threshold \n C2: 1464 (1470); S2: 39843 (51594)" , 
            "Seed production threshold \n C3: 4375 (4482); S3: 1048 (1235) \n 'O3: 429",
            "Seed production threshold \n *C4: 5264 (5282); *S4: 242 (287) \n 'O4: 197; 'A4: 3059",
            "Seed production threshold \n C2: 1403 (1486); S2: 1070 (2078)",
            "Seed production threshold \n *C3: 863 (863); *S3:  675 (1279) \n 'O3: 656",
            "Seed production threshold \n *C4: 7361 (7424); *S4: 90 (99) \n 'O4: 431; 'A4: 231"),
  Rotation = rep(c("2-year", "3-year", "4-year"), 2),
  Corn_weed_management = rep(c("conventional", "low"), 3),
  category = rep("placeholder", 6)
  ) 

seed_allowance_sim_df %>%
   ggplot() +
   aes(x = cycle_no, y = lambda_annualized, group = category) +
 # geom_line(aes(y = lambda_annualized, color =  category)) +
#  geom_point(aes(y  = lambda_annualized, color =  category, alpha = 0.5)) +
  geom_point(aes(y  = lambda_annualized, shape =  category)) +
  scale_shape_manual(values = c(1, 4)) +
  scale_color_brewer(palette = "Set1") +
#  geom_hline(yintercept = 1, color = "black") +
  geom_hline(yintercept = 1, color = "red") +
  facet_grid(Rotation ~ Corn_weed_management ) + 
  ylab("Annualized population growth rate") +
  xlab("Cycle number") + 
   ylim(0.7, 2) +
  theme(legend.position = "bottom",
        legend.title = element_blank()) + 
    geom_text(data = sim_label, aes(label = label), size = 3, x = 50, y = 1.75) 
```


```{r seed-allowance-sim-N-plot, echo=FALSE, fig.cap= "Population size at the end of a rotation cycle over 100 rotational cycles (the 2-year rotation ended at the soybean phase, the 3-year rotation ended at the oat phase, and the 4-year rotation ended at the alfalfa phase). All simulations started with a seed column of 10000 female seeds in the top 0 - 2 cm soil stratum and 0 female seed in the bottom 2 - 20 cm soil stratum. The simulation applied improved weed control efficacy on cohorts 1 through 3 in corn and soybean only. The relationships of aboveground mass and fecundity in Nguyen and Liebman (2022a) were used to estimate cohort-based fecundity. It was expected that no waterhemp cohorts in any crop environments but only the cohorts 1 through 3 in corn and soybean were manipulated to find the seed production thresholds. However, additional control efficacy was needed in some crop phases outside of the expected group to reduce seed production potentials. The crop phases marked with an asterisk (*) are where control measures extended beyond waterhemp cohort 3 would be neccessary. The crop phases marked with an inverted comma (') are where no additional control was applied. Each panel was annotated with the average fecundity thresholds for the first three waterhemp cohorts in corn and soybean followed by the whole crop phase.  The red horizontal line marks lambda = 1.", fig.height = 6, fig.width = 6}

seed_allowance_sim_df %>%
   ggplot() +
   aes(x = cycle_no, y = log(counts), group = category) +
 # geom_line(aes(y = lambda_annualized, color =  category)) +
#  geom_point(aes(y  = lambda_annualized, color =  category, alpha = 0.5)) +
  geom_point(aes(y  = log(counts), shape =  category)) +
  scale_shape_manual(values = c(1, 4)) +
  geom_hline(yintercept = log(10000), color = "red") +
  facet_grid(Rotation ~ Corn_weed_management) + 
  ylab(expression(paste("ln(Seed density (seeds",~m^-2,"))"))) +
  xlab("Simulation iteration") + 
  ylim(0, 15) +
  theme_bw() +
  guides(shape=guide_legend(title = "soil stratum")) +
  theme(legend.position = "top") + 
    geom_text(data = sim_label, aes(label = label), size = 2.5, x = 50, y = 12.5) 
```



```{r seed-allowance-sim-N-plot-no-ann, echo=FALSE, fig.cap= "Population size at the end of a rotation cycle over 100 rotational cycles (the 2-year rotation ended at the soybean phase, the 3-year rotation ended at the oat phase, and the 4-year rotation ended at the alfalfa phase). All simulations started with a seed column of 10000 female seeds in the top 0 - 2 cm soil stratum and 0 female seed in the bottom 2 - 20 cm soil stratum. The simulation applied improved weed control efficacy on cohorts 1 through 3 in corn and soybean only. The relationships of aboveground mass and fecundity in Nguyen and Liebman (2022a) were used to estimate cohort-based fecundity. It was expected that no waterhemp cohorts in any crop environments but only the cohorts 1 through 3 in corn and soybean were manipulated to find the seed production thresholds. However, additional control efficacy was needed in some crop phases outside of the expected group to reduce seed production potentials. The red horizontal line marks lambda = 1.", fig.height = 6, fig.width = 6}

seed_allowance_sim_df %>%
   ggplot() +
   aes(x = cycle_no, y = log(counts), group = category) +
 # geom_line(aes(y = lambda_annualized, color =  category)) +
#  geom_point(aes(y  = lambda_annualized, color =  category, alpha = 0.5)) +
  geom_point(aes(y  = log(counts), shape =  category)) +
  scale_shape_manual(values = c(1, 4)) +
  geom_hline(yintercept = log(10000), color = "red") +
  facet_grid(Rotation ~ Corn_weed_management) + 
  ylab(expression(paste("ln(Seed density (seeds",~m^-2,"))"))) +
  xlab("Simulation iteration") + 
  ylim(0, 15) +
  theme_bw() +
  guides(shape=guide_legend(title = "soil stratum")) +
  theme(legend.position = "top") 
```




