---
title: 'Q2: how long until total resistance'
output: html_document
---

```{r, include=FALSE}

set.seed(722)
```

```{r, echo=FALSE}
resistant_prop <- 0.05
susceptible_prop <- 1 - resistant_prop

profile_start <- c(resistant_prop, susceptible_prop)

starting_point <-  c(10000, 0, 0, 0, 0, 0, 0, 0) #10000 seeds top soil, 0 seed deep soil,0 plants from cohorts 1 through 6
```

```{r tillage-sim2, include=FALSE}
fall_tillage <-readRDS("../2-Data/Clean/mean-post-harvest-tillage.RData")

spring_tillage <-readRDS("../2-Data/Clean/mean-pre-planting-tillage.RData")
```

### overwinter survival matrix  

```{r overwinter-sim2}
overwinter <- readRDS("../2-Data/Clean/mean-winter-seed-survival-Sosnoskie.RData")
```

### emergence matrix  

```{r emerge-sim2, echo=FALSE}
emergence <-readRDS("../2-Data/Clean/mean-emergence-prop.RData")
```

### seed survival rate and seedling to maturity success rate 

```{r survive-sim2, echo=FALSE}
summer_seed_survival <- readRDS("../2-Data/Clean/mean-summer-seed-survival-Sosnoskie.RData")

#### plant survival: literature data - named as scenario2, because scenario1 is the point-estimates from the experiment 

female_survival <- readRDS("../2-Data/Clean/mean-summer-seedling-survival-Hartzler.RData")

#### combine seed and plant survivals into one matrix with element-wise multiplication: this is not computing, but arranging using 1's as placeholders 
summer_survival <- purrr::map2(summer_seed_survival, female_survival, `*`)
```


```{r fecund-sim2, echo=FALSE}
### Scenario 1 fecundity
fecundity_scenario1 <- readRDS("../2-Data/Clean/mean-fecundity-18-cohort.RData")

### Scenario 2 fecundity
fecundity_scenario2 <- readRDS("../2-Data/Clean/mean-fecundity-19-cohort.RData")
```

```{r rot-2yr-function, echo=FALSE}
# event sequence: seed dropped - chisel - overwinter - field cultivator - emerge - survive - new seed

# create a function 
# vec: starting seed column
# poh: post-harvest tillage
# ow: over winter seed survival
# prt: pre-planting-tillage
# em: emergence
# sv: seed survival rate and seedling to maturity success rate
# seed: fecundity

rot_2year_resistance <- function(vec, poh_C, ow_C, prt_C, em_C, sv_C, seed_C,
                           poh_S, ow_S, prt_S, em_S, sv_S, seed_S){
  
 # corn phase dynamics   
   after_corn <- seed_C %*% sv_C %*% em_C %*% prt_C %*%  ow_C %*%  poh_C %*% vec 
# soybean phase dynamics

   after_soy <- seed_S %*% sv_S %*% em_S %*% prt_S %*%  ow_S %*%  poh_S %*% after_corn 

   after_soy
}

```
