---
title: "Q2-draft"
author: "Huong Nguyen"
date: '2022-07-25'
output: html_document
---



Assumptions:
In conventional herbicide treatment: 100% of the RR plants survive, but 1% of the SS plants survive
In low herbicide treatment: 50% of the RR plants survive and 50% of the SS plants survive
When no herbicide was applied: 50% of the RR plants survive and 50% of the SS plants survive

$$
R_n = R_0 * (1 - \frac{F\alpha}{b})^n
$$
where,  

n is the number of generation that the population is under selection pressure,  
$R_n$ is the fraction of resistant seeds after n generations,  
$R_o$ is the initial frequency of resistant seeds,  
F is the fecundity of surviving plants
$\alpha$ is the ratio of resistant versus susceptible plants that survived after a generation of exposure  
b is the number of years that a seed remains viable in the soil seedbank  



- Resistance to the active ingredient of interest is conferred by a single-locus gene with two alleles.
- Allele S, that confer susceptibility, is totally dominant over allele R that confers resistance, therefore, all the RS and SS genotypes are killed by herbicide when exposed (this assumption is made for simplicity, but the survival rate of SR can be higher than SS as detailed in Chapter 8 of @cousensDynamicsWeedPopulations1995),  
- New seeds of cohorts 1 through 3: 50% RR and 50% SR, because all the SS and SR in cohorts 1 through 3 are killed, but SS and SR plants are available in cohorts 4 through 6,  
- Population sex ratio does not affect gamete sex ratio, meaning the female plants in the female-biased population does not make more female gamete,  
- New seeds of cohorts 4 through 6 are of the same allele frequency as the original seed population : 0.05 RR and 0.95 Sx.   

RR_genotype <- 0.05 
resistant_freq  <- sqrt(RR_genotype)

SS_genotype <- (1 - resistant_freq)^2 #homozygotic susceptible

SR_genotype <- 1 - RR_genotype - SS_genotype

Sx_genotype <- 1 - RR_genotype  # homo- and heterozygotic susceptible


profile_start <- c(resistant_prop, susceptible_prop)
```{r RR-tally}
### scalar calculation of allele frequency 
#begin 
start_prop_RR <- 0.05  # r^2 in the H-W equation
start_prop_R <- sqrt(start_prop_RR)

start_prop_S <- 1 - start_prop_R
start_prop_SS <- start_prop_S^2 # s^2 in the H-W equation

start_prop_SR = 1 - (start_prop_RR + start_prop_SS) #2rs in the H-W equation



# Assumption: 
# All the RS and SS genotypes are killed by herbicide when exposed;
# New seeds of cohorts 1 through 3: 50% RR and 50% SR, because all the SS and SR in cohorts 1 through 3 are killed, but SS and SR plants are available in cohorts 4 through 6
# Population sex ratio does not affect gamete sex ratio, meaning the female plants in the female-biased population does not make more female gamete.
# New seeds of cohorts 4 through 6 are of the same allele frequency as the original seed population : 0.05 RR and 0.95 Sx

# A matrix to pick out the RR prop after the starting_point population has completed a generation
after_corn_RR_prop <- matrix(1, nrow = 8, ncol = 8)

after_corn_RR_prop[1, 3:8] <- c(.5, .5, .5, 0.05, 0.05, 0.05)

after_corn_RR_prop[2, 2] <- 0.05
```



