---
title: "S-B-graphs"
author: "Huong Nguyen"
date: '2022-05-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Exclude from final text after this point #### 

```{r scenario1-lambda-annualized, include=FALSE, fig.cap= "Annualized waterhemp population growth rate using 2019 fecundity rate."}
#View(scenario1_annualized_lambda_and_var)
x_labs <- c("2-year", "3-year", "4-year")

ggplot(scenario1_annualized_lambda_and_var, aes(y = annualized_lambda, x = .id , fill = Corn_weed_management)) + 
  geom_bar(stat = "identity", position = "dodge") +
  ylab("Annualized population growth rate with 2019 fecundity") +
  xlab("Rotation") +
  scale_x_discrete(labels= x_labs) +
  theme_bw()
```

```{r S-B-spring-tillage-contribution-2yr, fig.cap="Contribution of each entry element in the spring tillage sub-annual matrix to lambda.", include=FALSE}

S_B_contribution_2yr_spring_tillage <- S_B_contribution_2yr[c("C2_mean_spring_tillage_contribution", "S2_mean_spring_tillage_contribution")]

# https://stackoverflow.com/questions/62949713/unlisting-nested-lists-and-plotting-using-ggplot
# melt the list will return Var1 = row 1 in the original matrix, Var = 2 column in the original matrix, and L1 = list name in the original matrix 
reshape2::melt(S_B_contribution_2yr_spring_tillage) %>%
 rename(original_matrix_row = Var1, original_matrix_col = Var2) %>%
  filter(original_matrix_col < 3) %>%
  ggplot(aes(x =  original_matrix_row, y = value, color = as.factor(original_matrix_col))) +
  #geom_point() +
  geom_jitter() +
  facet_grid(~ L1) +
  xlab("to seed stratum or plant group") +
  labs(colour = "from seed stratum or plant group") + 
  ylab("contribution to lambda sensitivity") +
  scale_color_discrete(breaks=c("1", "2"),
                           labels=c("Top", "Bottom")) +
  scale_x_discrete(limits=c("top st. seed","bottom  st. seed","seedling co. 1", "seedling co. 2",
                            "seedling co. 3", "seedling co. 4", "seedling co. 5", "seedling co. 6")) +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(legend.position="top")
```

```{r S-B-emerge-contribution-2yr, fig.cap="Contribution of each entry element in the emergence sub-annual matrix to lambda.", include=FALSE}
## subletting removes names
S_B_contribution_2yr_emerge <- S_B_contribution_2yr[c("C2_mean_emergence_scenario1_contribution", "S2_mean_emergence_scenario1_contribution")]

# https://stackoverflow.com/questions/62949713/unlisting-nested-lists-and-plotting-using-ggplot
# melt the list will return Var1 = row 1 in the original matrix, Var = 2 column in the original matrix, and L1 = list name in the original matrix 
reshape2::melt(S_B_contribution_2yr_emerge) %>%
 rename(original_matrix_row = Var1, original_matrix_col = Var2) %>%
  filter(original_matrix_col < 3) %>%
  ggplot(aes(x =  original_matrix_row, y = value, color = as.factor(original_matrix_col))) +
  #geom_point() +
  geom_jitter() +
  facet_grid(~ L1) +
  xlab("to seed stratum or plant group") +
  labs(colour = "from seed stratum or plant group") + 
  ylab("contribution to lambda sensitivity") +
  scale_color_discrete(breaks=c("1", "2"),
                           labels=c("Top", "Bottom")) +
  scale_x_discrete(limits=c("top st. seed","bottom  st. seed","seedling co. 1", "seedling co. 2",
                            "seedling co. 3", "seedling co. 4", "seedling co. 5", "seedling co. 6")) +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(legend.position="top")
```

```{r S-B-summer-survival-contribution-2yr, fig.cap="Contribution of each entry element in the emergence sub-annual matrix to lambda.", include=FALSE}
## subletting removes names
S_B_contribution_2yr_summer_survival <- S_B_contribution_2yr[c("C2_mean_summer_survival_scenario1_contribution", "S2_mean_summer_survival_scenario1_contribution")]

# https://stackoverflow.com/questions/62949713/unlisting-nested-lists-and-plotting-using-ggplot
# melt the list will return Var1 = row 1 in the original matrix, Var = 2 column in the original matrix, and L1 = list name in the original matrix 
reshape2::melt(S_B_contribution_2yr_summer_survival) %>%
 rename(original_matrix_row = Var1, original_matrix_col = Var2) %>%
  filter(original_matrix_col < 3) %>%
  ggplot(aes(x =  original_matrix_row, y = value, color = as.factor(original_matrix_col))) +
  #geom_point() +
  geom_jitter() +
  facet_grid(~ L1) +
  xlab("to seed stratum or plant group") +
  labs(colour = "from seed stratum or plant group") + 
  ylab("contribution to lambda sensitivity") +
  scale_color_discrete(breaks=c("1", "2"),
                           labels=c("Top", "Bottom")) +
  scale_x_discrete(limits=c("top st. seed","bottom  st. seed","seedling co. 1", "seedling co. 2",
                            "seedling co. 3", "seedling co. 4", "seedling co. 5", "seedling co. 6")) +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(legend.position="top")
```

```{r S-B-post-harvest-contribution-2yr, fig.cap="Contribution of each entry element in the post harvest tillage sub-annual matrix to lambda.", include = FALSE}
S_B_contribution_2yr_post_harvest_tillage <- S_B_contribution_2yr[c("C2_mean_post_harvest_tillage_contribution", "S2_mean_post_harvest_tillage_contribution")]

# https://stackoverflow.com/questions/62949713/unlisting-nested-lists-and-plotting-using-ggplot
# melt the list will return Var1 = row 1 in the original matrix, Var = 2 column in the original matrix, and L1 = list name in the original matrix 
reshape2::melt(S_B_contribution_2yr_post_harvest_tillage) %>%
  rename(original_matrix_row = Var1, original_matrix_col = Var2) %>%
  filter(original_matrix_col < 3) %>%
  ggplot(aes(x =  original_matrix_row, y = value, color = as.factor(original_matrix_col))) +
  #geom_point() +
  geom_jitter() +
  facet_grid(~ L1) +
  xlab("to seed or plant group") +
  labs(colour = "from seed stratum or plant group") + 
  ylab("contribution to lambda sensitivity") +
  scale_color_discrete(breaks=c("1", "2"),
                           labels=c("Top", "Bottom")) +
  scale_x_discrete(limits=c("top st. seed","bottom st. seed","plant co. 1", "plant co. 2",
                            "plant co. 3", "plant co. 4", "plant co. 5", "plant co. 6")) +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(legend.position="top")

```

```{r S-B-overwinter-contribution-2yr, fig.cap="Contribution of each entry element in the overwinter sub-annual matrix to lambda.", include=FALSE}
## subletting removes names
S_B_contribution_2yr_overwinter <- S_B_contribution_2yr[c("C2_mean_overwinter_scenario1_contribution", "S2_mean_overwinter_scenario1_contribution")]

# https://stackoverflow.com/questions/62949713/unlisting-nested-lists-and-plotting-using-ggplot
# melt the list will return Var1 = row 1 in the original matrix, Var = 2 column in the original matrix, and L1 = list name in the original matrix 
reshape2::melt(S_B_contribution_2yr_overwinter) %>%
 rename(original_matrix_row = Var1, original_matrix_col = Var2) %>%
  filter(original_matrix_col < 3) %>%
  ggplot(aes(x =  original_matrix_row, y = value, color = as.factor(original_matrix_col))) +
  #geom_point() +
  geom_jitter() +
  facet_grid(~ L1) +
  xlab("to seed stratum or plant group") +
  labs(colour = "from seed stratum or plant group") + 
  ylab("contribution to lambda sensitivity") +
  scale_color_discrete(breaks=c("1", "2"),
                           labels=c("Top", "Bottom")) +
  scale_x_discrete(limits=c("top st. seed","bottom  st. seed","seedling co. 1", "seedling co. 2",
                            "seedling co. 3", "seedling co. 4", "seedling co. 5", "seedling co. 6")) +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(legend.position="top")
```
