my_split_fun <- function(x, labs, digits, varlen, faclen){
  labs <- gsub("index", "index", labs)
  labs <- gsub("site.num", "Site ID", labs)
  labs <- gsub("prop.res.plt", "Proportion Resistant", labs)
  labs <- gsub("mgt.data", "Management History", labs)
  labs <- gsub("res.rank", "Resistance Rank", labs)
  labs <- gsub("nw.lat", "Latitude", labs)
  labs <- gsub("nw.lon", "Longidude", labs)
  labs <- gsub("elev.m", "Elevation (m)", labs)
  labs <- gsub("max.slope", "Maximum Slope", labs)
  labs <- gsub("tot.border.m", "Field Border (m)", labs)
  labs <- gsub("p.trees.bord", "Tree Border (proportion)", labs)
  labs <- gsub("p.treerow.bord", "Tree Border (proportion)", labs)
  labs <- gsub("p.forest.bord", "Forest Border (proportion)", labs)  
  labs <- gsub("p.ag.bord", "Agriculture Border\n(proportion)", labs)
  labs <- gsub("p.house.bord", "House Border (proportion)", labs)
  labs <- gsub("p.road", "Road Border (proportion)", labs)
  labs <- gsub("closest.forest.m", "Distance to Forest (m)", labs)
  labs <- gsub("closest.road.m", "Distance to Road (m)", labs)
  labs <- gsub("bare.patch.m", "Max. Bare Patch\nLength (m)", labs)
  labs <- gsub("bare.patch.num", "Number of Bare Patches", labs)
  labs <- gsub("grs.wtwy", "Grass Waterway in Field", labs)
  labs <- gsub("trans.grswtwy", "Grass Waterway Transects Field", labs)
  labs <- gsub("grass.waterway.m", "Length Grass\nWaterway (m)", labs)
  labs <- gsub("nearest.stream.m", "Distance to Stream (m)", labs)
  labs <- gsub("num.fld.corners", "Number of Field Corners", labs)
  labs <- gsub("perim.m", "Field Perimeter (m)", labs)
  labs <- gsub("ha", "Field Area (ha)", labs)
  labs <- gsub("edge.interior", "Edge:Interior", labs)
  labs <- gsub("amata.sd.m2", "AMATA seeds\n per m^2", labs)
  labs <- gsub("SOC.pc", "Soil Organic Carbon (%)", labs)
  labs <- gsub("P.ppm", "Soil P (ppm)", labs)
  labs <- gsub("K.ppm", "Soil K (ppm)", labs)
  labs <- gsub("Mg.ppm", "Soil Mg (ppm)", labs)
  labs <- gsub("Ca.ppm", "Soil Ca (ppm)", labs)
  labs <- gsub("pH", "Soil pH", labs)
  labs <- gsub("buff.pH", "soil buffer pH", labs)
  labs <- gsub("CEC", "Cation Exchange Capacity", labs)
  labs <- gsub("K.pc", "Soil K (%)", labs)
  labs <- gsub("Mg.pc", "Soil Mg (%)", labs)
  labs <- gsub("Ca.pc", "Soil Ca (%)", labs)
  labs <- gsub("S.ppm", "Soil S (ppm)", labs)
  labs <- gsub("Zn.ppm", "Soil Zn (ppm)", labs)
  labs <- gsub("Mn.ppm", "Soil Mn (ppm)", labs)
  labs <- gsub("Fe.ppm", "Soil Fe (ppm)", labs)
  labs <- gsub("Cu.ppm", "Soil Cu (ppm)", labs)
  labs <- gsub("B.ppm", "Soil B (ppm)", labs)
  labs <- gsub("NO3.ppm", "Soil NO3 (ppm)", labs)
  labs <- gsub("NH4.ppm", "Soil NH4 (ppm)", labs)
  labs <- gsub("c.n.ratio", "Total C:N", labs)
  labs <- gsub("som.pc.comb", "Soil Organic Carbon (%)", labs)
  labs <- gsub("totN.pc", "Total N (%)", labs)
  labs <- gsub("bulk.dens", "Soil Bulk Density (g/cm3)", labs)
  labs <- gsub("sand.pc", "Sand (%)", labs)
  labs <- gsub("silt.pc", "Silt (%)", labs)
  labs <- gsub("clay.pc", "Clay (%)", labs)
  labs <- gsub("texture", "Soil Texture", labs)
  labs <- gsub("whc.0.33.bar", "Soil Psi (-0.033 mPa)", labs)
  labs <- gsub("whc.15.bar", "Soil Psi (-1.5 mPa)", labs)
  labs <- gsub("low.spot", "Wet Spots in Field", labs)
  labs <- gsub("watercourse.infld", "Watercourse in Field", labs)
  labs <- gsub("watercourse.side", "Watercourse on Field Edge", labs)
  labs <- gsub("manure", "Manure Applied?", labs)
  labs <- gsub("crop.2010", "2010 Crop", labs)
  labs <- gsub("crop.sampled", "Sampled Crop", labs)
  labs <- gsub("border.wh.2010", "AMATA Along Edge", labs)
  labs <- gsub("amata.infest.2010", "AMATA Infestation\nLevel", labs)
  labs <- gsub("amata.absent.2010", "AMATA Absetnt", labs)
  labs <- gsub("amata.high.2010", "High AMATA Abundance", labs)
  labs <- gsub("ABUTH.2010", "Velvetleaf Present", labs)
  labs <- gsub("AMAsp.2010", "Amaranthus Present", labs)
  labs <- gsub("AMBEL.2010", "Common Ragweed Present", labs)
  labs <- gsub("AMBTR.2010", "Giant Rageweed Present", labs)
  labs <- gsub("CHEAL.2010", "Common Lambsquarters Present", labs)
  labs <- gsub("ERICA.2010", "Marestail Present", labs)
  labs <- gsub("grass.2010", "Weedy Grasses\nPresent", labs)
  labs <- gsub("IPOHE.2010", "Ivyleaf Morningglory Present", labs)
  labs <- gsub("SIDSP.2010", "Prickly Sida Present", labs)
  labs <- gsub("XANST.2010", "Cocklebur Present", labs)
  labs <- gsub("moa.across.yrs", "Total Herbicide MOA\nAcross Years", labs)
  labs <- gsub("data.years", "Years of Data Provided", labs)
  labs <- gsub("tot.moa.div.yr", "Herbicide MOA/Year", labs)
  labs <- gsub("glyph.apps", "Total Glyphosate Applications Across Years", labs)
  labs <- gsub("mean.moa.per.yr", "Mean Herbicide MOA/Year", labs)
  labs <- gsub("max.moa.yr", "Maximum Herbicide MOA/Year", labs)
  labs <- gsub("tot.pre.yrs", "Preemergent Herbicide\n(total years)", labs)  
  labs <- gsub("prop.pre.yrs", "Preemergent Herbicide (proportion of years)", labs)  
  labs <- gsub("mean.gly.apps.yr", "Glyphosate\nApplications/Year", labs)
  labs <- gsub("prop.gly.years", "Proportion Glyphosate\nYears", labs)
  labs <- gsub("prop.corn.years", "Proportion Corn Years", labs)
  labs <- gsub("near.infect", "Nearest Infected\nField (km)", labs)
  labs <- gsub("dm_turnover", "Herbicide Turnover\nIndex", labs)
  labs <- gsub("betaH1.B", "Harrison's Beta 1 (2004-2006)", labs)
  labs <- gsub("betaW.B", "Whittaker's Beta (2004-2006)", labs)
  labs <- gsub("betaT.B", "MOA Turnover (2004-2006)", labs)
  labs <- gsub("betaH1", "Harrison's Beta 1", labs)
  labs <- gsub("betaW", "Whittaker's Beta", labs)
  labs <- gsub("beta", "MOA Turnover", labs)
  labs}
